### ISSUE TITLE
Implement fsync for rclone mount

### ISSUE THREAD

**Issue by tcf909** [ncw/rclone#1045]
Hello,

I was hoping to use Borgbackup as a encryption / dedupe / compression layer on top of an rclone mount to ACD. 

I ran in to an error right away. Given the power and awesomeness that is borgbackup, this could be an awesome use case.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.35

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04 (container)

> Which cloud storage system are you using? (eg Google Drive)
ACD

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
rclone mount ACD:Vault_Backups /mnt/ACD-Vault_Backup/ --dir-cache-time 60s -v --debug-fuse --log-file /mnt/rclone.log &
borgbackup init /mnt/ACD-Vault_Backup/
```

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
```
root@ws-term:/mnt# fusermount -u ACD-Vault_Backup/
[1]+  Done                    rclone mount ACD:Vault_Backups /mnt/ACD-Vault_Backup/ --dir-cache-time 60s
root@ws-term:/mnt# rclone mount ACD:Vault_Backups /mnt/ACD-Vault_Backup/ --dir-cache-time 60s -v --debug-fuse --log-file /mnt/rclone.log &
[1] 3652
root@ws-term:/mnt# borgbackup init /mnt/ACD-Vault_Backup/
Enter new passphrase:
Enter same passphrase again:
Do you want your passphrase to be displayed for verification? [yN]: n
Exception ignored in: <bound method Repository.__del__ of <Repository /mnt/ACD-Vault_Backup>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 72, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 192, in close
    self.lock.release()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 298, in release
    self._roster.modify(EXCLUSIVE, REMOVE)
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 216, in modify
    elements.remove(self.id)
KeyError: (('ws-term', 3661, 0),)
Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 85, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 131, in do_init
    manifest.write()
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 139, in write
    self.repository.put(self.MANIFEST_ID, self.key.encrypt(data))
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 535, in put
    segment, offset = self.io.write_put(id, data)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 784, in write_put
    fd = self.get_write_fd(raise_full=raise_full)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 668, in get_write_fd
    sync_dir(os.path.join(self.path, 'data'))
  File "/usr/lib/python3/dist-packages/borg/platform.py", line 10, in sync_dir
    os.fsync(fd)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1684, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1621, in run
    return args.func(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 85, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 94, in __exit__
    self.close()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 192, in close
    self.lock.release()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 301, in release
    self._lock.release()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 154, in release
    os.unlink(self.unique_name)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/ACD-Vault_Backup/lock.exclusive/ws-term.3661-0'

Platform: Linux ws-term 4.4.36-k8s #1 SMP Mon Dec 5 00:55:01 UTC 2016 x86_64 x86_64
Linux: Ubuntu 16.04 xenial
Borg: 1.0.7  Python: CPython 3.5.2
PID: 3661  CWD: /mnt
sys.argv: ['/usr/bin/borgbackup', 'init', '/mnt/ACD-Vault_Backup/']
SSH_ORIGINAL_COMMAND: None
```

Rclone Logs:
```
2017/01/17 22:45:29 rclone: Version "v1.35" starting with parameters ["rclone" "mount" "ACD:Vault_Backups" "/mnt/ACD-Vault_Backup/" "--dir-cache-time" "60s" "-v" "--debug-fuse" "--log-file" "/mnt/rclone.log"]
2017/01/17 22:45:30 amazon drive root 'Vault_Backups': Modify window not supported
2017/01/17 22:45:30 amazon drive root 'Vault_Backups': Mounting on "/mnt/ACD-Vault_Backup/"
2017/01/17 22:45:30 amazon drive root 'Vault_Backups': Root()
2017/01/17 22:45:38 fuse: <- Getattr [ID=0x2 Node=0x1 Uid=0 Gid=0 Pid=3133] 0x0 fl=0
2017/01/17 22:45:38 : Dir.Attr
2017/01/17 22:45:38 fuse: -> [ID=0x2] Getattr valid=1m0s ino=1 size=0 mode=drwxr-xr-x
2017/01/17 22:45:38 fuse: <- Open [ID=0x3 Node=0x1 Uid=0 Gid=0 Pid=3133] dir=true fl=OpenReadOnly+OpenDirectory+OpenNonblock
2017/01/17 22:45:38 fuse: -> [ID=0x3] Open 0x1 fl=0
2017/01/17 22:45:38 fuse: <- Read [ID=0x4 Node=0x1 Uid=0 Gid=0 Pid=3133] 0x1 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock
2017/01/17 22:45:38 : Dir.ReadDirAll
2017/01/17 22:45:38 : Reading directory
2017/01/17 22:45:38 : Dir.ReadDirAll OK with 0 entries
2017/01/17 22:45:38 fuse: -> [ID=0x4] Read 0
2017/01/17 22:45:38 fuse: <- Release [ID=0x5 Node=0x1 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenReadOnly+OpenDirectory+OpenNonblock rfl=0x2 owner=0x70054662
2017/01/17 22:45:38 fuse: -> [ID=0x5] Release
2017/01/17 22:45:38 fuse: <- Getattr [ID=0x6 Node=0x1 Uid=0 Gid=0 Pid=3133] 0x0 fl=0
2017/01/17 22:45:38 : Dir.Attr
2017/01/17 22:45:38 fuse: -> [ID=0x6] Getattr valid=1m0s ino=1 size=0 mode=drwxr-xr-x
2017/01/17 22:45:38 fuse: <- Lookup [ID=0x7 Node=0x1 Uid=0 Gid=0 Pid=3133] "README"
2017/01/17 22:45:38 README: Dir.Lookup
2017/01/17 22:45:38 fuse: -> [ID=0x7] Lookup error=ENOENT
2017/01/17 22:45:38 fuse: <- Create [ID=0x8 Node=0x1 Uid=0 Gid=0 Pid=3133] "README" fl=OpenWriteOnly+OpenCreate+OpenTruncate mode=-rw------- umask=----rwxrwx
2017/01/17 22:45:38 README: Dir.Create
2017/01/17 22:45:38 README: Dir.Create OK
2017/01/17 22:45:38 File.Attr
2017/01/17 22:45:38 fuse: -> [ID=0x8] Create {0x2 gen=0 valid=1m0s attr={valid=1m0s ino=12725298794585788734 size=0 mode=-rw-r--r--}} {0x1 fl=0}
2017/01/17 22:45:38 fuse: No opcode 39
2017/01/17 22:45:38 fuse: <- ID=0x9 Node=0x2 Uid=0 Gid=0 Pid=3133
2017/01/17 22:45:38 fuse: -> [ID=0x9] Header error=ENOSYS
2017/01/17 22:45:38 fuse: No opcode 39
2017/01/17 22:45:38 fuse: <- ID=0xa Node=0x2 Uid=0 Gid=0 Pid=3133
2017/01/17 22:45:38 fuse: -> [ID=0xa] Header error=ENOSYS
2017/01/17 22:45:38 fuse: <- Getxattr [ID=0xb Node=0x2 Uid=0 Gid=0 Pid=3133] "security.capability" 0 @0
2017/01/17 22:45:38 fuse: -> [ID=0xb] Getxattr error=operation not supported
2017/01/17 22:45:38 fuse: <- Write [ID=0xc Node=0x2 Uid=0 Gid=0 Pid=3133] 0x1 26 @0 fl=0 lock=0 ffl=OpenWriteOnly
2017/01/17 22:45:38 README: WriteFileHandle.Write len=26
2017/01/17 22:45:38 README: WriteFileHandle.Write OK (26 bytes written)
2017/01/17 22:45:38 fuse: -> [ID=0xc] Write 26
2017/01/17 22:45:38 fuse: <- Flush [ID=0xd Node=0x2 Uid=0 Gid=0 Pid=3133] 0x1 fl=0x0 lk=0x25d1f70e33215b50
2017/01/17 22:45:38 README: WriteFileHandle.Flush
2017/01/17 22:45:38 README: WriteFileHandle.Flush OK
2017/01/17 22:45:38 fuse: -> [ID=0xd] Flush
2017/01/17 22:45:38 fuse: <- Release [ID=0xe Node=0x2 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenWriteOnly rfl=0x2 owner=0xe2e80946
2017/01/17 22:45:38 README: WriteFileHandle.Release nothing to do
2017/01/17 22:45:38 fuse: -> [ID=0xe] Release
2017/01/17 22:45:38 fuse: <- Lookup [ID=0xf Node=0x1 Uid=0 Gid=0 Pid=3133] "data"
2017/01/17 22:45:38 data: Dir.Lookup
2017/01/17 22:45:38 fuse: -> [ID=0xf] Lookup error=ENOENT
2017/01/17 22:45:38 fuse: <- Mkdir [ID=0x10 Node=0x1 Uid=0 Gid=0 Pid=3133] "data" mode=drwx------ umask=----rwxrwx
2017/01/17 22:45:38 data: Dir.Mkdir
2017/01/17 22:45:38 data: Dir.Mkdir OK
2017/01/17 22:45:38 data: Dir.Attr
2017/01/17 22:45:38 fuse: -> [ID=0x10] Mkdir 0x3 gen=0 valid=1m0s attr={valid=1m0s ino=15215112422504144876 size=0 mode=drwxr-xr-x}
2017/01/17 22:45:38 fuse: <- Lookup [ID=0x11 Node=0x1 Uid=0 Gid=0 Pid=3133] "config"
2017/01/17 22:45:38 config: Dir.Lookup
2017/01/17 22:45:38 fuse: -> [ID=0x11] Lookup error=ENOENT
2017/01/17 22:45:38 fuse: <- Create [ID=0x12 Node=0x1 Uid=0 Gid=0 Pid=3133] "config" fl=OpenWriteOnly+OpenCreate+OpenTruncate mode=-rw------- umask=----rwxrwx
2017/01/17 22:45:38 config: Dir.Create
2017/01/17 22:45:38 config: Dir.Create OK
2017/01/17 22:45:38 File.Attr
2017/01/17 22:45:38 fuse: -> [ID=0x12] Create {0x4 gen=0 valid=1m0s attr={valid=1m0s ino=13635685484877411234 size=0 mode=-rw-r--r--}} {0x1 fl=0}
2017/01/17 22:45:38 fuse: No opcode 39
2017/01/17 22:45:38 fuse: <- ID=0x13 Node=0x4 Uid=0 Gid=0 Pid=3133
2017/01/17 22:45:38 fuse: -> [ID=0x13] Header error=ENOSYS
2017/01/17 22:45:38 fuse: No opcode 39
2017/01/17 22:45:38 fuse: <- ID=0x14 Node=0x4 Uid=0 Gid=0 Pid=3133
2017/01/17 22:45:38 fuse: -> [ID=0x14] Header error=ENOSYS
2017/01/17 22:45:38 fuse: <- Getxattr [ID=0x15 Node=0x4 Uid=0 Gid=0 Pid=3133] "security.capability" 0 @0
2017/01/17 22:45:38 fuse: -> [ID=0x15] Getxattr error=operation not supported
2017/01/17 22:45:38 fuse: <- Write [ID=0x16 Node=0x4 Uid=0 Gid=0 Pid=3133] 0x1 164 @0 fl=0 lock=0 ffl=OpenWriteOnly
2017/01/17 22:45:38 config: WriteFileHandle.Write len=164
2017/01/17 22:45:38 config: WriteFileHandle.Write OK (164 bytes written)
2017/01/17 22:45:38 fuse: -> [ID=0x16] Write 164
2017/01/17 22:45:38 fuse: <- Flush [ID=0x17 Node=0x4 Uid=0 Gid=0 Pid=3133] 0x1 fl=0x0 lk=0x25d1f70e33215b50
2017/01/17 22:45:38 config: WriteFileHandle.Flush
2017/01/17 22:45:39 config: WriteFileHandle.Flush OK
2017/01/17 22:45:39 fuse: -> [ID=0x17] Flush
2017/01/17 22:45:39 fuse: <- Release [ID=0x18 Node=0x4 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenWriteOnly rfl=0x2 owner=0x6866dc84
2017/01/17 22:45:39 config: WriteFileHandle.Release nothing to do
2017/01/17 22:45:39 fuse: -> [ID=0x18] Release
2017/01/17 22:45:39 fuse: <- Getattr [ID=0x19 Node=0x1 Uid=0 Gid=0 Pid=3133] 0x0 fl=0
2017/01/17 22:45:39 : Dir.Attr
2017/01/17 22:45:39 fuse: -> [ID=0x19] Getattr valid=1m0s ino=1 size=0 mode=drwxr-xr-x
2017/01/17 22:45:39 fuse: <- Lookup [ID=0x1a Node=0x1 Uid=0 Gid=0 Pid=3133] "lock.exclusive"
2017/01/17 22:45:39 lock.exclusive: Dir.Lookup
2017/01/17 22:45:39 fuse: -> [ID=0x1a] Lookup error=ENOENT
2017/01/17 22:45:39 fuse: <- Mkdir [ID=0x1b Node=0x1 Uid=0 Gid=0 Pid=3133] "lock.exclusive" mode=drwx------ umask=----rwxrwx
2017/01/17 22:45:39 lock.exclusive: Dir.Mkdir
2017/01/17 22:45:39 lock.exclusive: Dir.Mkdir OK
2017/01/17 22:45:39 lock.exclusive: Dir.Attr
2017/01/17 22:45:39 fuse: -> [ID=0x1b] Mkdir 0x5 gen=0 valid=1m0s attr={valid=1m0s ino=10321337070849226685 size=0 mode=drwxr-xr-x}
2017/01/17 22:45:39 fuse: <- Lookup [ID=0x1c Node=0x5 Uid=0 Gid=0 Pid=3133] "ws-term.3661-0"
2017/01/17 22:45:39 lock.exclusive/ws-term.3661-0: Dir.Lookup
2017/01/17 22:45:39 lock.exclusive: Reading directory
2017/01/17 22:45:39 fuse: -> [ID=0x1c] Lookup error=ENOENT
2017/01/17 22:45:39 fuse: <- Create [ID=0x1d Node=0x5 Uid=0 Gid=0 Pid=3133] "ws-term.3661-0" fl=OpenWriteOnly+OpenCreate+OpenTruncate mode=-rw------- umask=----rwxrwx
2017/01/17 22:45:39 lock.exclusive/ws-term.3661-0: Dir.Create
2017/01/17 22:45:39 lock.exclusive/ws-term.3661-0: Dir.Create OK
2017/01/17 22:45:39 File.Attr
2017/01/17 22:45:39 fuse: -> [ID=0x1d] Create {0x6 gen=0 valid=1m0s attr={valid=1m0s ino=13536385407099829648 size=0 mode=-rw-r--r--}} {0x1 fl=0}
2017/01/17 22:45:39 fuse: No opcode 39
2017/01/17 22:45:39 fuse: <- ID=0x1e Node=0x6 Uid=0 Gid=0 Pid=3133
2017/01/17 22:45:39 fuse: -> [ID=0x1e] Header error=ENOSYS
2017/01/17 22:45:39 fuse: <- Flush [ID=0x1f Node=0x6 Uid=0 Gid=0 Pid=3133] 0x1 fl=0x0 lk=0x25d1f70e33215b50
2017/01/17 22:45:39 lock.exclusive/ws-term.3661-0: WriteFileHandle.Flush
2017/01/17 22:45:39 lock.exclusive/ws-term.3661-0: WriteFileHandle.Flush ignoring flush on unwritten handle
2017/01/17 22:45:39 fuse: -> [ID=0x1f] Flush
2017/01/17 22:45:39 fuse: <- Release [ID=0x20 Node=0x6 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenWriteOnly rfl=0 owner=0x0
2017/01/17 22:45:39 lock.exclusive/ws-term.3661-0: WriteFileHandle.Release closing
2017/01/17 22:45:39 fuse: <- Lookup [ID=0x21 Node=0x1 Uid=0 Gid=0 Pid=3133] "lock.roster"
2017/01/17 22:45:39 lock.roster: Dir.Lookup
2017/01/17 22:45:39 fuse: -> [ID=0x21] Lookup error=ENOENT
2017/01/17 22:45:39 fuse: <- Lookup [ID=0x22 Node=0x1 Uid=0 Gid=0 Pid=3133] "lock.roster"
2017/01/17 22:45:39 lock.roster: Dir.Lookup
2017/01/17 22:45:39 fuse: -> [ID=0x22] Lookup error=ENOENT
2017/01/17 22:45:39 fuse: <- Lookup [ID=0x23 Node=0x1 Uid=0 Gid=0 Pid=3133] "lock.roster"
2017/01/17 22:45:39 lock.roster: Dir.Lookup
2017/01/17 22:45:39 fuse: -> [ID=0x23] Lookup error=ENOENT
2017/01/17 22:45:39 fuse: <- Create [ID=0x24 Node=0x1 Uid=0 Gid=0 Pid=3133] "lock.roster" fl=OpenWriteOnly+OpenCreate+OpenTruncate mode=-rw------- umask=----rwxrwx
2017/01/17 22:45:39 lock.roster: Dir.Create
2017/01/17 22:45:39 lock.roster: Dir.Create OK
2017/01/17 22:45:39 File.Attr
2017/01/17 22:45:39 fuse: -> [ID=0x24] Create {0x7 gen=0 valid=1m0s attr={valid=1m0s ino=9490043697873932996 size=0 mode=-rw-r--r--}} {0x1 fl=0}
2017/01/17 22:45:39 fuse: No opcode 39
2017/01/17 22:45:39 fuse: <- ID=0x25 Node=0x7 Uid=0 Gid=0 Pid=3133
2017/01/17 22:45:39 fuse: -> [ID=0x25] Header error=ENOSYS
2017/01/17 22:45:39 fuse: No opcode 39
2017/01/17 22:45:39 fuse: <- ID=0x26 Node=0x7 Uid=0 Gid=0 Pid=3133
2017/01/17 22:45:39 fuse: -> [ID=0x26] Header error=ENOSYS
2017/01/17 22:45:39 fuse: <- Getxattr [ID=0x27 Node=0x7 Uid=0 Gid=0 Pid=3133] "security.capability" 0 @0
2017/01/17 22:45:39 fuse: -> [ID=0x27] Getxattr error=operation not supported
2017/01/17 22:45:39 fuse: <- Write [ID=0x28 Node=0x7 Uid=0 Gid=0 Pid=3133] 0x1 37 @0 fl=0 lock=0 ffl=OpenWriteOnly
2017/01/17 22:45:39 lock.roster: WriteFileHandle.Write len=37
2017/01/17 22:45:39 lock.roster: WriteFileHandle.Write OK (37 bytes written)
2017/01/17 22:45:39 fuse: -> [ID=0x28] Write 37
2017/01/17 22:45:39 fuse: <- Flush [ID=0x29 Node=0x7 Uid=0 Gid=0 Pid=3133] 0x1 fl=0x0 lk=0x25d1f70e33215b50
2017/01/17 22:45:39 lock.roster: WriteFileHandle.Flush
2017/01/17 22:45:39 lock.exclusive/ws-term.3661-0: Error detected after finished upload - waiting to see if object was uploaded correctly: HTTP code 429: "429 Too Many Requests": response body: "{\"logref\":\"ab4ed001-dd06-11e6-b5a7-797d40453ad1\",\"message\":\"Rate exceeded\",\"code\":\"\"}" ("429 Too Many Requests")
2017/01/17 22:45:39 lock.exclusive/ws-term.3661-0: Giving up waiting for object - returning original error: HTTP code 429: "429 Too Many Requests": response body: "{\"logref\":\"ab4ed001-dd06-11e6-b5a7-797d40453ad1\",\"message\":\"Rate exceeded\",\"code\":\"\"}" ("429 Too Many Requests")
2017/01/17 22:45:39 pacer: Rate limited, sleeping for 539.813105ms (1 consecutive low level retries)
2017/01/17 22:45:39 pacer: low level retry 1/1 (error HTTP code 429: "429 Too Many Requests": response body: "{\"logref\":\"ab4ed001-dd06-11e6-b5a7-797d40453ad1\",\"message\":\"Rate exceeded\",\"code\":\"\"}")
2017/01/17 22:45:39 lock.exclusive/ws-term.3661-0: WriteFileHandle.Release error: HTTP code 429: "429 Too Many Requests": response body: "{\"logref\":\"ab4ed001-dd06-11e6-b5a7-797d40453ad1\",\"message\":\"Rate exceeded\",\"code\":\"\"}"
2017/01/17 22:45:39 fuse: -> [ID=0x20] Release error=EIO: HTTP code 429: "429 Too Many Requests": response body: "{\"logref\":\"ab4ed001-dd06-11e6-b5a7-797d40453ad1\",\"message\":\"Rate exceeded\",\"code\":\"\"}"
2017/01/17 22:45:42 pacer: Resetting sleep to minimum 20ms on success
2017/01/17 22:45:42 lock.roster: WriteFileHandle.Flush OK
2017/01/17 22:45:42 fuse: -> [ID=0x29] Flush
2017/01/17 22:45:42 fuse: <- Open [ID=0x2b Node=0x4 Uid=0 Gid=0 Pid=3133] dir=false fl=OpenReadOnly
2017/01/17 22:45:42 config: File.Open
2017/01/17 22:45:42 fuse: <- Release [ID=0x2a Node=0x7 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenWriteOnly rfl=0 owner=0x0
2017/01/17 22:45:42 lock.roster: WriteFileHandle.Release nothing to do
2017/01/17 22:45:42 fuse: -> [ID=0x2a] Release
2017/01/17 22:45:42 fuse: -> [ID=0x2b] Open 0x1 fl=0
2017/01/17 22:45:42 fuse: <- Getattr [ID=0x2c Node=0x4 Uid=0 Gid=0 Pid=3133] 0x0 fl=0
2017/01/17 22:45:42 config: File.Attr
2017/01/17 22:45:42 fuse: -> [ID=0x2c] Getattr valid=1m0s ino=13635685484877411234 size=164 mode=-rw-r--r--
2017/01/17 22:45:42 fuse: No opcode 39
2017/01/17 22:45:42 fuse: <- ID=0x2d Node=0x4 Uid=0 Gid=0 Pid=3133
2017/01/17 22:45:42 fuse: -> [ID=0x2d] Header error=ENOSYS
2017/01/17 22:45:42 fuse: No opcode 39
2017/01/17 22:45:42 fuse: <- ID=0x2e Node=0x4 Uid=0 Gid=0 Pid=3133
2017/01/17 22:45:42 fuse: -> [ID=0x2e] Header error=ENOSYS
2017/01/17 22:45:42 fuse: <- Read [ID=0x2f Node=0x4 Uid=0 Gid=0 Pid=3133] 0x1 4096 @0x0 dir=false fl=0 lock=0 ffl=OpenReadOnly
2017/01/17 22:45:42 config: ReadFileHandle.Read size 4096 offset 0
2017/01/17 22:45:42 config: ReadFileHandle.Read OK
2017/01/17 22:45:42 fuse: -> [ID=0x2f] Read 164
2017/01/17 22:45:42 fuse: <- Getattr [ID=0x30 Node=0x4 Uid=0 Gid=0 Pid=3133] 0x1 fl=GetattrFh
2017/01/17 22:45:42 config: File.Attr
2017/01/17 22:45:42 fuse: -> [ID=0x30] Getattr valid=1m0s ino=13635685484877411234 size=164 mode=-rw-r--r--
2017/01/17 22:45:42 fuse: <- Flush [ID=0x31 Node=0x4 Uid=0 Gid=0 Pid=3133] 0x1 fl=0x0 lk=0x25d1f70e33215b50
2017/01/17 22:45:42 config: ReadFileHandle.Flush
2017/01/17 22:45:42 config: ReadFileHandle.Flush OK
2017/01/17 22:45:42 fuse: -> [ID=0x31] Flush
2017/01/17 22:45:42 fuse: <- Release [ID=0x32 Node=0x4 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenReadOnly rfl=0 owner=0x0
2017/01/17 22:45:42 config: ReadFileHandle.Release closing
2017/01/17 22:45:42 config: ReadFileHandle.Release OK
2017/01/17 22:45:42 fuse: -> [ID=0x32] Release
2017/01/17 22:45:49 fuse: <- Open [ID=0x33 Node=0x4 Uid=0 Gid=0 Pid=3133] dir=false fl=OpenWriteOnly
2017/01/17 22:45:49 config: File.Open
2017/01/17 22:45:49 fuse: -> [ID=0x33] Open 0x1 fl=OpenNonSeekable
2017/01/17 22:45:49 fuse: <- Getxattr [ID=0x34 Node=0x4 Uid=0 Gid=0 Pid=3133] "security.capability" 0 @0
2017/01/17 22:45:49 fuse: -> [ID=0x34] Getxattr error=operation not supported
2017/01/17 22:45:49 fuse: <- Setattr [ID=0x35 Node=0x4 Uid=0 Gid=0 Pid=3133] size=0 handle=INVALID-0x0 lockowner
2017/01/17 22:45:49 config: File.Attr
2017/01/17 22:45:49 fuse: -> [ID=0x35] Setattr valid=1m0s ino=13635685484877411234 size=164 mode=-rw-r--r--
2017/01/17 22:45:49 fuse: No opcode 39
2017/01/17 22:45:49 fuse: <- ID=0x36 Node=0x4 Uid=0 Gid=0 Pid=3133
2017/01/17 22:45:49 fuse: -> [ID=0x36] Header error=ENOSYS
2017/01/17 22:45:49 fuse: No opcode 39
2017/01/17 22:45:49 fuse: <- ID=0x37 Node=0x4 Uid=0 Gid=0 Pid=3133
2017/01/17 22:45:49 fuse: -> [ID=0x37] Header error=ENOSYS
2017/01/17 22:45:49 fuse: <- Getxattr [ID=0x38 Node=0x4 Uid=0 Gid=0 Pid=3133] "security.capability" 0 @0
2017/01/17 22:45:49 fuse: -> [ID=0x38] Getxattr error=operation not supported
2017/01/17 22:45:49 fuse: <- Write [ID=0x39 Node=0x4 Uid=0 Gid=0 Pid=3133] 0x1 635 @0 fl=0 lock=0 ffl=OpenWriteOnly
2017/01/17 22:45:49 config: WriteFileHandle.Write len=635
2017/01/17 22:45:49 config: WriteFileHandle.Write OK (635 bytes written)
2017/01/17 22:45:49 fuse: -> [ID=0x39] Write 635
2017/01/17 22:45:49 fuse: <- Flush [ID=0x3a Node=0x4 Uid=0 Gid=0 Pid=3133] 0x1 fl=0x0 lk=0x25d1f70e33215b50
2017/01/17 22:45:49 config: WriteFileHandle.Flush
2017/01/17 22:45:50 config: WriteFileHandle.Flush OK
2017/01/17 22:45:50 fuse: -> [ID=0x3a] Flush
2017/01/17 22:45:50 fuse: <- Release [ID=0x3b Node=0x4 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenWriteOnly rfl=0x2 owner=0x1dfcf231
2017/01/17 22:45:50 config: WriteFileHandle.Release nothing to do
2017/01/17 22:45:50 fuse: -> [ID=0x3b] Release
2017/01/17 22:45:50 fuse: <- Open [ID=0x3c Node=0x1 Uid=0 Gid=0 Pid=3133] dir=true fl=OpenReadOnly+OpenDirectory+OpenNonblock
2017/01/17 22:45:50 fuse: -> [ID=0x3c] Open 0x1 fl=0
2017/01/17 22:45:50 fuse: <- Getattr [ID=0x3d Node=0x1 Uid=0 Gid=0 Pid=3133] 0x0 fl=0
2017/01/17 22:45:50 : Dir.Attr
2017/01/17 22:45:50 fuse: -> [ID=0x3d] Getattr valid=1m0s ino=1 size=0 mode=drwxr-xr-x
2017/01/17 22:45:50 fuse: <- Read [ID=0x3e Node=0x1 Uid=0 Gid=0 Pid=3133] 0x1 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock
2017/01/17 22:45:50 : Dir.ReadDirAll
2017/01/17 22:45:50 : Dir.ReadDirAll OK with 5 entries
2017/01/17 22:45:50 fuse: -> [ID=0x3e] Read 176
2017/01/17 22:45:50 fuse: <- Read [ID=0x3f Node=0x1 Uid=0 Gid=0 Pid=3133] 0x1 4096 @0xb0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock
2017/01/17 22:45:50 fuse: -> [ID=0x3f] Read 0
2017/01/17 22:45:50 fuse: <- Release [ID=0x40 Node=0x1 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenReadOnly+OpenDirectory+OpenNonblock rfl=0x2 owner=0xb9ca22ec
2017/01/17 22:45:50 fuse: -> [ID=0x40] Release
2017/01/17 22:45:50 fuse: <- Open [ID=0x41 Node=0x3 Uid=0 Gid=0 Pid=3133] dir=true fl=OpenReadOnly+OpenDirectory+OpenNonblock
2017/01/17 22:45:50 fuse: -> [ID=0x41] Open 0x1 fl=0
2017/01/17 22:45:50 fuse: <- Read [ID=0x42 Node=0x3 Uid=0 Gid=0 Pid=3133] 0x1 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock
2017/01/17 22:45:50 data: Dir.ReadDirAll
2017/01/17 22:45:50 data: Reading directory
2017/01/17 22:45:50 data: Dir.ReadDirAll OK with 0 entries
2017/01/17 22:45:50 fuse: -> [ID=0x42] Read 0
2017/01/17 22:45:50 fuse: <- Release [ID=0x43 Node=0x3 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenReadOnly+OpenDirectory+OpenNonblock rfl=0x2 owner=0x8af603ea
2017/01/17 22:45:50 fuse: -> [ID=0x43] Release
2017/01/17 22:45:50 fuse: <- Open [ID=0x44 Node=0x1 Uid=0 Gid=0 Pid=3133] dir=true fl=OpenReadOnly+OpenDirectory+OpenNonblock
2017/01/17 22:45:50 fuse: -> [ID=0x44] Open 0x1 fl=0
2017/01/17 22:45:50 fuse: <- Getattr [ID=0x45 Node=0x1 Uid=0 Gid=0 Pid=3133] 0x0 fl=0
2017/01/17 22:45:50 : Dir.Attr
2017/01/17 22:45:50 fuse: -> [ID=0x45] Getattr valid=1m0s ino=1 size=0 mode=drwxr-xr-x
2017/01/17 22:45:50 fuse: <- Read [ID=0x46 Node=0x1 Uid=0 Gid=0 Pid=3133] 0x1 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock
2017/01/17 22:45:50 : Dir.ReadDirAll
2017/01/17 22:45:50 : Dir.ReadDirAll OK with 5 entries
2017/01/17 22:45:50 fuse: -> [ID=0x46] Read 176
2017/01/17 22:45:50 fuse: <- Read [ID=0x47 Node=0x1 Uid=0 Gid=0 Pid=3133] 0x1 4096 @0xb0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock
2017/01/17 22:45:50 fuse: -> [ID=0x47] Read 0
2017/01/17 22:45:50 fuse: <- Release [ID=0x48 Node=0x1 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenReadOnly+OpenDirectory+OpenNonblock rfl=0x2 owner=0x94ed84ea
2017/01/17 22:45:50 fuse: -> [ID=0x48] Release
2017/01/17 22:45:50 fuse: <- Getattr [ID=0x49 Node=0x5 Uid=0 Gid=0 Pid=3133] 0x0 fl=0
2017/01/17 22:45:50 lock.exclusive: Dir.Attr
2017/01/17 22:45:50 fuse: -> [ID=0x49] Getattr valid=1m0s ino=10321337070849226685 size=0 mode=drwxr-xr-x
2017/01/17 22:45:50 fuse: <- Lookup [ID=0x4a Node=0x3 Uid=0 Gid=0 Pid=3133] "0"
2017/01/17 22:45:50 data/0: Dir.Lookup
2017/01/17 22:45:50 fuse: -> [ID=0x4a] Lookup error=ENOENT
2017/01/17 22:45:50 fuse: <- Lookup [ID=0x4b Node=0x3 Uid=0 Gid=0 Pid=3133] "0"
2017/01/17 22:45:50 data/0: Dir.Lookup
2017/01/17 22:45:50 fuse: -> [ID=0x4b] Lookup error=ENOENT
2017/01/17 22:45:50 fuse: <- Mkdir [ID=0x4c Node=0x3 Uid=0 Gid=0 Pid=3133] "0" mode=drwx------ umask=----rwxrwx
2017/01/17 22:45:50 data/0: Dir.Mkdir
2017/01/17 22:45:50 data/0: Dir.Mkdir OK
2017/01/17 22:45:50 data/0: Dir.Attr
2017/01/17 22:45:50 fuse: -> [ID=0x4c] Mkdir 0x8 gen=0 valid=1m0s attr={valid=1m0s ino=3785014639147058449 size=0 mode=drwxr-xr-x}
2017/01/17 22:45:50 fuse: <- Open [ID=0x4d Node=0x3 Uid=0 Gid=0 Pid=3133] dir=true fl=OpenReadOnly
2017/01/17 22:45:50 fuse: -> [ID=0x4d] Open 0x1 fl=0
2017/01/17 22:45:50 fuse: <- Fsync [ID=0x4e Node=0x3 Uid=0 Gid=0 Pid=3133] Handle 0x1 Flags 0
2017/01/17 22:45:50 fuse: -> [ID=0x4e] Fsync error=EIO
2017/01/17 22:45:50 fuse: <- Release [ID=0x4f Node=0x3 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenReadOnly rfl=0x2 owner=0xbba1c41c
2017/01/17 22:45:50 fuse: -> [ID=0x4f] Release
2017/01/17 22:45:50 fuse: <- Open [ID=0x50 Node=0x7 Uid=0 Gid=0 Pid=3133] dir=false fl=OpenReadOnly
2017/01/17 22:45:50 lock.roster: File.Open
2017/01/17 22:45:50 fuse: -> [ID=0x50] Open 0x1 fl=0
2017/01/17 22:45:50 fuse: <- Getattr [ID=0x51 Node=0x7 Uid=0 Gid=0 Pid=3133] 0x0 fl=0
2017/01/17 22:45:50 lock.roster: File.Attr
2017/01/17 22:45:50 fuse: -> [ID=0x51] Getattr valid=1m0s ino=9490043697873932996 size=37 mode=-rw-r--r--
2017/01/17 22:45:50 fuse: No opcode 39
2017/01/17 22:45:50 fuse: <- ID=0x52 Node=0x7 Uid=0 Gid=0 Pid=3133
2017/01/17 22:45:50 fuse: -> [ID=0x52] Header error=ENOSYS
2017/01/17 22:45:50 fuse: No opcode 39
2017/01/17 22:45:50 fuse: <- ID=0x53 Node=0x7 Uid=0 Gid=0 Pid=3133
2017/01/17 22:45:50 fuse: -> [ID=0x53] Header error=ENOSYS
2017/01/17 22:45:50 fuse: <- Read [ID=0x54 Node=0x7 Uid=0 Gid=0 Pid=3133] 0x1 4096 @0x0 dir=false fl=0 lock=0 ffl=OpenReadOnly
2017/01/17 22:45:50 lock.roster: ReadFileHandle.Read size 4096 offset 0
2017/01/17 22:45:50 lock.roster: ReadFileHandle.Read OK
2017/01/17 22:45:50 fuse: -> [ID=0x54] Read 37
2017/01/17 22:45:50 fuse: <- Getattr [ID=0x55 Node=0x7 Uid=0 Gid=0 Pid=3133] 0x1 fl=GetattrFh
2017/01/17 22:45:50 lock.roster: File.Attr
2017/01/17 22:45:50 fuse: -> [ID=0x55] Getattr valid=1m0s ino=9490043697873932996 size=37 mode=-rw-r--r--
2017/01/17 22:45:50 fuse: <- Flush [ID=0x56 Node=0x7 Uid=0 Gid=0 Pid=3133] 0x1 fl=0x0 lk=0x25d1f70e33215b50
2017/01/17 22:45:50 lock.roster: ReadFileHandle.Flush
2017/01/17 22:45:50 lock.roster: ReadFileHandle.Flush OK
2017/01/17 22:45:50 fuse: -> [ID=0x56] Flush
2017/01/17 22:45:50 fuse: <- Release [ID=0x57 Node=0x7 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenReadOnly rfl=0x2 owner=0xc7055952
2017/01/17 22:45:50 lock.roster: ReadFileHandle.Release closing
2017/01/17 22:45:50 lock.roster: ReadFileHandle.Release OK
2017/01/17 22:45:50 fuse: -> [ID=0x57] Release
2017/01/17 22:45:50 fuse: <- Open [ID=0x58 Node=0x7 Uid=0 Gid=0 Pid=3133] dir=false fl=OpenWriteOnly
2017/01/17 22:45:50 lock.roster: File.Open
2017/01/17 22:45:50 fuse: -> [ID=0x58] Open 0x1 fl=OpenNonSeekable
2017/01/17 22:45:50 fuse: <- Getxattr [ID=0x59 Node=0x7 Uid=0 Gid=0 Pid=3133] "security.capability" 0 @0
2017/01/17 22:45:50 fuse: -> [ID=0x59] Getxattr error=operation not supported
2017/01/17 22:45:50 fuse: <- Setattr [ID=0x5a Node=0x7 Uid=0 Gid=0 Pid=3133] size=0 handle=INVALID-0x0 lockowner
2017/01/17 22:45:50 lock.roster: File.Attr
2017/01/17 22:45:50 fuse: -> [ID=0x5a] Setattr valid=1m0s ino=9490043697873932996 size=37 mode=-rw-r--r--
2017/01/17 22:45:50 fuse: No opcode 39
2017/01/17 22:45:50 fuse: <- ID=0x5b Node=0x7 Uid=0 Gid=0 Pid=3133
2017/01/17 22:45:50 fuse: -> [ID=0x5b] Header error=ENOSYS
2017/01/17 22:45:50 fuse: No opcode 39
2017/01/17 22:45:50 fuse: <- ID=0x5c Node=0x7 Uid=0 Gid=0 Pid=3133
2017/01/17 22:45:50 fuse: -> [ID=0x5c] Header error=ENOSYS
2017/01/17 22:45:50 fuse: <- Getxattr [ID=0x5d Node=0x7 Uid=0 Gid=0 Pid=3133] "security.capability" 0 @0
2017/01/17 22:45:50 fuse: -> [ID=0x5d] Getxattr error=operation not supported
2017/01/17 22:45:50 fuse: <- Write [ID=0x5e Node=0x7 Uid=0 Gid=0 Pid=3133] 0x1 17 @0 fl=0 lock=0 ffl=OpenWriteOnly
2017/01/17 22:45:50 lock.roster: WriteFileHandle.Write len=17
2017/01/17 22:45:50 lock.roster: WriteFileHandle.Write OK (17 bytes written)
2017/01/17 22:45:50 fuse: -> [ID=0x5e] Write 17
2017/01/17 22:45:50 fuse: <- Flush [ID=0x5f Node=0x7 Uid=0 Gid=0 Pid=3133] 0x1 fl=0x0 lk=0x25d1f70e33215b50
2017/01/17 22:45:50 lock.roster: WriteFileHandle.Flush
2017/01/17 22:45:52 lock.roster: WriteFileHandle.Flush OK
2017/01/17 22:45:52 fuse: -> [ID=0x5f] Flush
2017/01/17 22:45:52 fuse: <- Release [ID=0x60 Node=0x7 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenWriteOnly rfl=0x2 owner=0x71c5507d
2017/01/17 22:45:52 lock.roster: WriteFileHandle.Release nothing to do
2017/01/17 22:45:52 fuse: -> [ID=0x60] Release
2017/01/17 22:45:52 fuse: <- Open [ID=0x61 Node=0x7 Uid=0 Gid=0 Pid=3133] dir=false fl=OpenReadOnly
2017/01/17 22:45:52 lock.roster: File.Open
2017/01/17 22:45:52 fuse: -> [ID=0x61] Open 0x1 fl=0
2017/01/17 22:45:52 fuse: <- Getattr [ID=0x62 Node=0x7 Uid=0 Gid=0 Pid=3133] 0x0 fl=0
2017/01/17 22:45:52 lock.roster: File.Attr
2017/01/17 22:45:52 fuse: -> [ID=0x62] Getattr valid=1m0s ino=9490043697873932996 size=17 mode=-rw-r--r--
2017/01/17 22:45:52 fuse: No opcode 39
2017/01/17 22:45:52 fuse: <- ID=0x63 Node=0x7 Uid=0 Gid=0 Pid=3133
2017/01/17 22:45:52 fuse: -> [ID=0x63] Header error=ENOSYS
2017/01/17 22:45:52 fuse: No opcode 39
2017/01/17 22:45:52 fuse: <- ID=0x64 Node=0x7 Uid=0 Gid=0 Pid=3133
2017/01/17 22:45:52 fuse: -> [ID=0x64] Header error=ENOSYS
2017/01/17 22:45:52 fuse: <- Read [ID=0x65 Node=0x7 Uid=0 Gid=0 Pid=3133] 0x1 4096 @0x0 dir=false fl=0 lock=0 ffl=OpenReadOnly
2017/01/17 22:45:52 lock.roster: ReadFileHandle.Read size 4096 offset 0
2017/01/17 22:45:52 lock.roster: ReadFileHandle.Read OK
2017/01/17 22:45:52 fuse: -> [ID=0x65] Read 17
2017/01/17 22:45:52 fuse: <- Getattr [ID=0x66 Node=0x7 Uid=0 Gid=0 Pid=3133] 0x1 fl=GetattrFh
2017/01/17 22:45:52 lock.roster: File.Attr
2017/01/17 22:45:52 fuse: -> [ID=0x66] Getattr valid=1m0s ino=9490043697873932996 size=17 mode=-rw-r--r--
2017/01/17 22:45:52 fuse: <- Flush [ID=0x67 Node=0x7 Uid=0 Gid=0 Pid=3133] 0x1 fl=0x0 lk=0x25d1f70e33215b50
2017/01/17 22:45:52 lock.roster: ReadFileHandle.Flush
2017/01/17 22:45:52 lock.roster: ReadFileHandle.Flush OK
2017/01/17 22:45:52 fuse: -> [ID=0x67] Flush
2017/01/17 22:45:52 fuse: <- Release [ID=0x68 Node=0x7 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenReadOnly rfl=0x2 owner=0x16cea34f
2017/01/17 22:45:52 lock.roster: ReadFileHandle.Release closing
2017/01/17 22:45:52 lock.roster: ReadFileHandle.Release OK
2017/01/17 22:45:52 fuse: -> [ID=0x68] Release
2017/01/17 22:45:52 fuse: <- Open [ID=0x69 Node=0x7 Uid=0 Gid=0 Pid=3133] dir=false fl=OpenReadOnly
2017/01/17 22:45:52 lock.roster: File.Open
2017/01/17 22:45:52 fuse: -> [ID=0x69] Open 0x1 fl=0
2017/01/17 22:45:52 fuse: No opcode 39
2017/01/17 22:45:52 fuse: <- ID=0x6a Node=0x7 Uid=0 Gid=0 Pid=3133
2017/01/17 22:45:52 fuse: -> [ID=0x6a] Header error=ENOSYS
2017/01/17 22:45:52 fuse: No opcode 39
2017/01/17 22:45:52 fuse: <- ID=0x6b Node=0x7 Uid=0 Gid=0 Pid=3133
2017/01/17 22:45:52 fuse: -> [ID=0x6b] Header error=ENOSYS
2017/01/17 22:45:52 fuse: <- Read [ID=0x6c Node=0x7 Uid=0 Gid=0 Pid=3133] 0x1 4096 @0x0 dir=false fl=0 lock=0 ffl=OpenReadOnly
2017/01/17 22:45:52 lock.roster: ReadFileHandle.Read size 4096 offset 0
2017/01/17 22:45:52 lock.roster: ReadFileHandle.Read OK
2017/01/17 22:45:52 fuse: -> [ID=0x6c] Read 17
2017/01/17 22:45:52 fuse: <- Getattr [ID=0x6d Node=0x7 Uid=0 Gid=0 Pid=3133] 0x1 fl=GetattrFh
2017/01/17 22:45:52 lock.roster: File.Attr
2017/01/17 22:45:52 fuse: -> [ID=0x6d] Getattr valid=1m0s ino=9490043697873932996 size=17 mode=-rw-r--r--
2017/01/17 22:45:52 fuse: <- Flush [ID=0x6e Node=0x7 Uid=0 Gid=0 Pid=3133] 0x1 fl=0x0 lk=0x25d1f70e33215b50
2017/01/17 22:45:52 lock.roster: ReadFileHandle.Flush
2017/01/17 22:45:52 lock.roster: ReadFileHandle.Flush OK
2017/01/17 22:45:52 fuse: -> [ID=0x6e] Flush
2017/01/17 22:45:52 fuse: <- Release [ID=0x6f Node=0x7 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenReadOnly rfl=0x2 owner=0x501470c0
2017/01/17 22:45:52 lock.roster: ReadFileHandle.Release closing
2017/01/17 22:45:52 lock.roster: ReadFileHandle.Release OK
2017/01/17 22:45:52 fuse: -> [ID=0x6f] Release
2017/01/17 22:45:52 fuse: <- Remove [ID=0x70 Node=0x1 Uid=0 Gid=0 Pid=3133] "lock.roster" dir=false
2017/01/17 22:45:52 lock.roster: Dir.Remove
2017/01/17 22:45:52 lock.roster: Dir.Remove OK
2017/01/17 22:45:52 fuse: -> [ID=0x70] Remove
2017/01/17 22:45:52 fuse: <- Forget [ID=0x71 Node=0x7 Uid=0 Gid=0 Pid=0] 1
2017/01/17 22:45:52 fuse: -> [ID=0x71] Forget
2017/01/17 22:45:52 fuse: <- Remove [ID=0x72 Node=0x5 Uid=0 Gid=0 Pid=3133] "ws-term.3661-0" dir=false
2017/01/17 22:45:52 lock.exclusive/ws-term.3661-0: Dir.Remove
2017/01/17 22:45:52 lock.exclusive/ws-term.3661-0: Dir.Remove error: no such file or directory
2017/01/17 22:45:52 fuse: -> [ID=0x72] Remove error=ENOENT
2017/01/17 22:45:52 fuse: <- Lookup [ID=0x73 Node=0x1 Uid=0 Gid=0 Pid=3133] "lock.roster"
2017/01/17 22:45:52 lock.roster: Dir.Lookup
2017/01/17 22:45:52 fuse: -> [ID=0x73] Lookup error=ENOENT
```

**Comment by ncw** [comment]
The problem looks like the fact that rclone mount doesn't support fsync

```
2017/01/17 22:45:50 fuse: <- Fsync [ID=0x4e Node=0x3 Uid=0 Gid=0 Pid=3133] Handle 0x1 Flags 0
2017/01/17 22:45:50 fuse: -> [ID=0x4e] Fsync error=EIO
```

which causes

```
  File "/usr/lib/python3/dist-packages/borg/platform.py", line 10, in sync_dir
    os.fsync(fd)
OSError: [Errno 5] Input/output error
```

`rclone mount` can't support fsync - it isn't something that any cloud storage systems support.  But I suppose it could just return without an error.

I can give that a go relatively easily and post a beta.

I don't guarantee that will make borgbackup work though - the file system that rclone presents has quite a lot of limitations (like you can't read and write a file)...

**Comment by tcf909** [comment]
I don't know how others feel, but it might be worth investigating. Borg
does some really awesome things. I believe the way their chunk system and
archives work (write once) is a perfect alignment for rclone.

**Comment by ncw** [comment]
I've implemented fsync here.  Can you give it a go please?  If there are other things borgbackup doesn't like about rclone mount then please open another issue with logs - Thanks - Nick

http://beta.rclone.org/v1.35-47-g29c6e22/ (uploaded in 15-30 mins)

**Comment by tcf909** [comment]
Thanks Nick. I'll give it a try tomorrow or Tuesday.

**Comment by kconat** [comment]
Just tested this version with borgbackup. Issue persists.

mkdir("/mnt/acd/backup/test3/test2232/data/0", 0777) = 0
open("/mnt/acd/backup/test3/test2232/data", O_RDONLY|O_CLOEXEC) = 4
fsync(4)                                = -1 EIO (Input/output error)
close(4)                                = 0

**Comment by ncw** [comment]
Thanks for working that out - I'll have a go for directories too!

**Comment by ncw** [comment]
OK here is a beta for you to try (untested!)

http://beta.rclone.org/v1.35-58-g8a11da4/ (uploaded in 15-30 mins)

**Comment by kconat** [comment]
thanks for the fast response. this is working now. this can be closed.

there is still another issue with borgbackup. since it is writing many files in short time it seems to trigger an amazon error: 429. It seems there is no retry in rclone and the write request just stalls until borgbackup decides to give up and terminates. Settings low-level-retries to a higher level does not seems to have any affect. 

Im going to open another issue if I cannot find an open one. 

```
2017/02/03 11:45:35 backup/test5/data/0/9: Error detected after finished upload - waiting to see if object was uploaded correctly: HTTP code 429: "429 Too Many Requests": response body: "{\"logref\":\"ab273621-e9fd-11e6-ad2f-c147c719a1b1\",\"message\":\"Rate exceeded\",\"code\":\"\"}" ("429 Too Many Requests")
2017/02/03 11:45:35 backup/test5/data/0/9: Object not found - waiting (1/1)
2017/02/03 11:45:40 backup/test5/data/0/9: Giving up waiting for object - returning original error: HTTP code 429: "429 Too Many Requests": response body: "{\"logref\":\"ab273621-e9fd-11e6-ad2f-c147c719a1b1\",\"message\":\"Rate exceeded\",\"code\":\"\"}" ("429 Too Many Requests")
```

**Comment by ncw** [comment]
@kconat glad that is working :-)

Unfortunately rclone can't retry the file without buffering it to disk first (that is the way fuse works).

There are some issues about this #1050 and #711 so you don't need to make a new one.

> write request just stalls until borgbackup decides to give up and terminates

What should happen is borgbackup gets an error when writing (or on the close)

Here is what happens when I try copying files with cp and I get one of those errors

    cp: failed to close '/home/ncw/mnt/tmp/xxxx.jpg': Input/output error
