### ISSUE TITLE
Problems with moveto/copyto commands

### ISSUE THREAD

**Issue by eharris** [ncw/rclone#1079]
Using the latest (updated as of earlier this morning) rclone on Linux, I'm getting unexpected behavior with the `moveto` command on local files.

`rclone -v moveto testfile somepath/`

fails with

```
2017/01/30 16:48:13 rclone: Version "v1.35-DEV" starting with parameters ["rclone" "-v" "moveto" "testfile" "somepath/"]
2017/01/30 16:48:13 Can't find parent directory for "somepath/"
```

Attempting the same command without the trailing slash and an empty `somepath` clobbers the destination directory and just renames the file in the same directory.

Attempting the same command without the trailing slash but a non-empty destination gives:

```
2017/01/30 16:49:26 rclone: Version "v1.35-DEV" starting with parameters ["rclone" "-v" "moveto" "testfile" "somepath"]
2017/01/30 16:49:26 Local file system at /home/eharris/rclone: Modify window is 1ns
2017/01/30 16:49:26 testfile: Sizes differ
2017/01/30 16:49:26 somepath: Couldn't delete: remove /home/eharris/rclone/somepath: directory not empty
2017/01/30 16:49:26 Attempt 1/3 failed with 1 errors and: remove /home/eharris/rclone/somepath: directory not empty
2017/01/30 16:49:26 testfile: Sizes differ
2017/01/30 16:49:26 somepath: Couldn't delete: remove /home/eharris/rclone/somepath: directory not empty
2017/01/30 16:49:26 Attempt 2/3 failed with 1 errors and: remove /home/eharris/rclone/somepath: directory not empty
2017/01/30 16:49:26 testfile: Sizes differ
2017/01/30 16:49:26 somepath: Couldn't delete: remove /home/eharris/rclone/somepath: directory not empty
2017/01/30 16:49:26 Attempt 3/3 failed with 1 errors and: remove /home/eharris/rclone/somepath: directory not empty
2017/01/30 16:49:26 Failed to moveto: remove /home/eharris/rclone/somepath: directory not empty
```

**Comment by eharris** [comment]
Similar results occur when using the `copyto` command.

**Comment by ncw** [comment]
Something weird is going on there certainly!

`Can't find parent directory for "somepath/"` is a parsing the remote error.

As for why the trailing `/` makes a difference - I think that is the same code...

I'll take a look...

**Comment by ncw** [comment]
I've fixed this in this beta

http://beta.rclone.org/v1.35-136-g30e97ad/ (uploaded in 15-30 mins)

Your command will now give this error

```
$ rclone --retries 1 -vv moveto testfile somepath/
2017/02/22 21:13:20 "somepath/" is a directory
```

which should hopefully be a hint that you need to put a leaf name on the end.

**Comment by eharris** [comment]
I just built rclone from master including through checkin `e2f0feef3cf4ff5a15312b5f02e5f7e71ad7ecd8` and I'm still getting the error:

    > rclone --retries 1 -vv moveto testfile somepath/
    2017/02/24 14:38:28 DEBUG : rclone: Version "v1.35-DEV" starting with parameters ["rclone" "--retries" "1" "-vv" "moveto" "testfile" "somepath/"]
    2017/02/24 14:38:28 Can't find parent directory for "somepath/"

**Comment by eharris** [comment]
Normal semantics for filesystems (and rsync) are that moving to a directory destination should work, so it seems to me like the fix you propose of warning that it's a directory and still failing to do what is expected isn't really the desired result.  I think most people would expect moves to a directory to work just fine.

**Comment by ncw** [comment]
I've fixed the overwrite of a directory you mentioned - find that in 79e3c67bbdb0722fd211a67f8a7c5c034a655a15

> I just built rclone from master including through checkin e2f0feef3cf4ff5a15312b5f02e5f7e71ad7ecd8 and I'm still getting the error:

I can't replicate that?

```
$ touch testfile
$ mkdir somepath

$ rclone --retries 1 -v moveto testfile somepath
2017/02/25 11:11:37 INFO  : Local file system at /tmp/b: Modify window is 1ns
2017/02/25 11:11:37 ERROR : Attempt 1/1 failed with 0 errors and: "somepath": is a not a regular file
2017/02/25 11:11:37 Failed to moveto: "somepath": is a not a regular file

$ rclone --retries 1 -v moveto testfile somepath/
2017/02/25 11:11:46 "somepath/" is a directory
```

> Normal semantics for filesystems (and rsync) are that moving to a directory destination should work, so it seems to me like the fix you propose of warning that it's a directory and still failing to do what is expected isn't really the desired result. I think most people would expect moves to a directory to work just fine.

At the moment `moveto` either takes

    rclone moveto file newfile
    rclone moveto dir newdir

If any of the arguments don't exist it will be treated as a directory, and trailing slashes should make no difference.

I think you'd like

    rclone moveto file existingdir
    rclone moveto file existingdir/

to work, which it could - can you make a new issue for that please and I'll have a look at it for 1.37.

Thanks

**Comment by eharris** [comment]
The issue I was having with still seeing the old behavior was because of #1178, my build wasn't picking up the changes from my checkout.

**Comment by ncw** [comment]
@eharris good news - thanks!
