### ISSUE TITLE
Unable to move file: can't move files on overlapping remotes

### ISSUE THREAD

**Issue by memeplex** [ncw/rclone#1319]
When trying to move a file drive:/home/b to a directory drive:/home/docs I get:

```
(ins)carlos@carlos store$ rclone -c move drive:/home/b drive:/home/docs
2017/04/08 22:23:49 INFO  : Google drive root 'home/docs': Modify window is 1ms
2017/04/08 22:23:49 ERROR : Google drive root 'home/docs': can't move files on overlapping remotes
2017/04/08 22:23:49 ERROR : Attempt 1/3 failed with 0 errors and: can't move files on overlapping remotes
2017/04/08 22:23:49 ERROR : Google drive root 'home/docs': can't move files on overlapping remotes
2017/04/08 22:23:49 ERROR : Attempt 2/3 failed with 0 errors and: can't move files on overlapping remotes
2017/04/08 22:23:49 ERROR : Google drive root 'home/docs': can't move files on overlapping remotes
2017/04/08 22:23:49 ERROR : Attempt 3/3 failed with 0 errors and: can't move files on overlapping remotes
2017/04/08 22:23:49 Failed to move: can't move files on overlapping remotes
```

Is this a bug or just lack of server side move operations for google drive?

**Comment by memeplex** [comment]
I would like to add that the same example works fine if I replace move with copy. The output log shows that ` b: Copied (server side copy)`

**Comment by memeplex** [comment]
I've renamed the issue since I realized that is not possible even locally:

```
(ins)carlos@carlos ~$ cd /tmp/
(ins)carlos@carlos tmp$ mkdir test
(ins)carlos@carlos tmp$ cd test/
(ins)carlos@carlos test$ mkdir x
(ins)carlos@carlos test$ touch a
(ins)carlos@carlos test$ rclone mv a x
(ins)carlos@carlos test$ rclone move a x
....
2017/04/09 00:00:31 Failed to move: can't move files on overlapping remotes
```

**Comment by ncw** [comment]
For a remote which support directory moves, your operation is perfectly safe.

For a remote which doesn't it has to move each individual file which might fail and need a retry which is where the trouble starts...

I need to spend some time thinking about the corner cases!

**Comment by ncw** [comment]
This was fixed in c123c702abf531b70bfa1fc93b9dbfcda66a909e :-)

**Comment by o0-o** [comment]
I am still experiencing this error in 1.51 in the following case:

```
rclone mkdir \
    "${CLOUD_DESTINATION}/Hidden System Files"  &&

  rclone                    \
    --include "/.*"         \
    move                    \
    "${CLOUD_DESTINATION}"  \
    "${CLOUD_DESTINATION}/Hidden System Files"
```

The remote is Google Drive as well. Is the include flag possibly causing the issue?

This seems similar enough to reopen this issue, but let me know if I should open a new one.

**Comment by ncw** [comment]
@o0-o the error is because you are attempting to copy "${CLOUD_DESTINATION}" to "${CLOUD_DESTINATION}/Hidden System Files" however "${CLOUD_DESTINATION}" includes "${CLOUD_DESTINATION}/Hidden System Files" already - hence the "overlapping remotes" error.

**Comment by o0-o** [comment]
Is there any way to move pattern-matched files and directories into a non-matching subdirectory?

The filter documentation indicates shell pattern matching and not proper regex, so I would assume that escaping a period would be unnecessary.

> Special characters can be escaped with a \ before them.
> 
> \*.jpg       - matches "*.jpg"
> \\.jpg       - matches "\.jpg"
> \[one\].jpg  - matches "[one].jpg"

**Comment by ncw** [comment]
> Is there any way to move pattern-matched files and directories into a non-matching subdirectory?

Not currently, the filters are applied after the check for overlapping remotes :-(

If I was doing this, I'd do it via a mount...

**Comment by yeya** [comment]
Does `mount` use server side copy when executing `mv`?

**Comment by ncw** [comment]
> Does `mount` use server side copy when executing `mv`?

Yes it does (if available).

**Comment by yeya** [comment]
Thanks. I [see ](https://forum.rclone.org/t/transfers-and-checkers-with-rclone-mount/2097)that `--transfers` can not be used, is there a way to set number of parallels? some `fuse` option maybe?

**Comment by ncw** [comment]
> Thanks. I [see ](https://forum.rclone.org/t/transfers-and-checkers-with-rclone-mount/2097)that `--transfers` can not be used, is there a way to set number of parallels? some `fuse` option maybe?

The mount is pretty much driven by user interaction, so if you want less things happening at once, then you have to do less things at once to the mount.

**Comment by Jwink3101** [comment]
> > Is there any way to move pattern-matched files and directories into a non-matching subdirectory?
> 
> Not currently, the filters are applied after the check for overlapping remotes :-(
> 
> If I was doing this, I'd do it via a mount...

Just for posterity, it appears this has been implemented in https://github.com/rclone/rclone/pull/6312 (released in 1.60.0 I think) as long as the destination is filtered one way or another.

Thanks @Schlossgeist and @ncw  for this awesome fix. It makes some operations in [syncrclone](https://github.com/Jwink3101/syncrclone) *much* easier
