### ISSUE TITLE
Fatal error: Address space conflict

### ISSUE THREAD

**Issue by ccrusius** [ncw/rclone#1520]
> What is your rclone version (eg output from `rclone -V`)

rclone v1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

SunOS, 64 bits.

> Which cloud storage system are you using? (eg Google Drive)

Backblaze

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

/opt/rclone/rclone sync \
  --old-sync-method \
  --log-file "/root/rclone-log/rclone.log" \
  --filter-from rclone-filter.txt \
  --transfers 32 \
  /global \
  backblaze:bucket

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

The log is 18M. I trimmed out what I think are irrelevant parts (skipped files, files successfully copied). I am also attaching the stderr capture with the crash error. Looks like an out of memory situation, but my system logs do not indicate that the VM ever tried to allocate more memory than it has available.

[rclone-2017-07-08T04:47:50+00:00-trimmed.txt](https://github.com/ncw/rclone/files/1132758/rclone-2017-07-08T04.47.50.00.00-trimmed.txt)

[rclone-2017-07-08T04:47:50+00:00-stderr.txt](https://github.com/ncw/rclone/files/1132755/rclone-2017-07-08T04.47.50.00.00-stderr.txt)

**Comment by ncw** [comment]
Hmm, that is almost certainly a bug in the go runtime.

```
runtime: address space conflict: map(0xc511590000) = 0xb
fatal error: runtime: address space conflict

runtime stack:
runtime.throw(0xd27059, 0x1f)
        /opt/go/go1.8/src/runtime/panic.go:596 +0x95
runtime.sysMap(0xc511590000, 0x6000000, 0x11b8a00, 0x11b4d38)
        /opt/go/go1.8/src/runtime/mem_bsd.go:84 +0x1b5
runtime.(*mheap).sysAlloc(0x119bec0, 0x6000000, 0x0)
        /opt/go/go1.8/src/runtime/malloc.go:428 +0x374
runtime.(*mheap).grow(0x119bec0, 0x3000, 0x0)
        /opt/go/go1.8/src/runtime/mheap.go:774 +0x62
runtime.(*mheap).allocSpanLocked(0x119bec0, 0x3000, 0xc420001ba0)
        /opt/go/go1.8/src/runtime/mheap.go:678 +0x420
runtime.(*mheap).alloc_m(0x119bec0, 0x3000, 0xfffffd0100000000, 0x430538)
        /opt/go/go1.8/src/runtime/mheap.go:562 +0xe2
runtime.(*mheap).alloc.func1()
        /opt/go/go1.8/src/runtime/mheap.go:627 +0x4b
runtime.systemstack(0xfffffd7ffdbffec8)
        /opt/go/go1.8/src/runtime/asm_amd64.s:343 +0xc1
runtime.(*mheap).alloc(0x119bec0, 0x3000, 0x10100000000, 0xbb5ec0)
        /opt/go/go1.8/src/runtime/mheap.go:628 +0xa0
runtime.largeAlloc(0x6000000, 0x1, 0x7f2733)
        /opt/go/go1.8/src/runtime/malloc.go:795 +0x93
runtime.mallocgc.func1()
        /opt/go/go1.8/src/runtime/malloc.go:690 +0x3e
runtime.systemstack(0xc420022000)
        /opt/go/go1.8/src/runtime/asm_amd64.s:327 +0x86
runtime.mstart()
        /opt/go/go1.8/src/runtime/proc.go:1132
```

This looks very much like https://github.com/golang/go/issues/14930

This has been fixed for go1.9 [in this commit](https://go-review.googlesource.com/c/43461/6/src/runtime/mem_bsd.go) but really the only difference is that it is going to print "out of memory" instead of "address space conflict".

So it looks like you are correct, that this is an out of memory situation.

If you try the [latest beta](https://beta.rclone.org) with the `--fast-list` flag instead of `--old-sync-method` (which will have the same effect) you should find it uses less memory.

**Comment by ccrusius** [comment]
Thanks. I will try it later, once my API quota resets.

If that doesn't work, I will try with more memory reserved for the VM (currently at 4G).

**Comment by ccrusius** [comment]
Just tried with the latest beta, error is still "address space conflict."

I'll see if I can try again tomorrow with more memory.

**Comment by ccrusius** [comment]
I tried with 8G reserved and it went through. With 4G, the error message is still "address space conflict" when only 4G are available. Feel free to close this bug if you think that having that error message is ok (and you are right, this looks like a Go runtime bug that wasn't fixed yet).

**Comment by ncw** [comment]
Try this attached version which I compiled with go1.9beta2+

[rclone-v1.36-248-gb8fe1759-solaris-amd64.zip](https://github.com/ncw/rclone/files/1134099/rclone-v1.36-248-gb8fe1759-solaris-amd64.zip)

I think it should give a more sensible out of memory error.

**Comment by sean-** [comment]
@ccrusius Any further problems with this issue?

**Comment by ccrusius** [comment]
It is working since July 9th, when I bumped the VM RAM. As far as I'm concerned, this issue can be closed - even if the error message is misleading, whoever has it will find the reason in this issue.

**Comment by sean-** [comment]
@ccrusius Can you confirm that you were actually running the updated binaries, or recompile now that Go 1.9 has been released?  If you're getting `runtime: address space conflict: map(0xc511590000) = 0xb` as your output, that's surprising because `0x9` is `11`, which is `EAGAIN`, and was exactly the return code that was fixed in Go 1.9.  That's not to say it's not possible, but I want to triple check that the binary you're running was indeed compiled with Go 1.9 and had the right fix.  I haven't seen this behavior yet so it's a bit hard for me to test, but before I go down a rabbit hole where I suggest a patch to Go 1.9, I want to make sure this actually happened.  Is there a chance you could get the error output with 4GB of RAM and a version of the program compiled with Go 1.9?  Thanks in advance for helping figure this out.

**Comment by ncw** [comment]
As go1.9 has been released, I'm now compiling rclone with it - see [the latest beta](https://beta.rclone.org).

I'm going to close this issue now, but feel free to re-open it if you think the problem isn't fixed.
