### ISSUE TITLE
Failed to create file system for "laptop:": input too short

### ISSUE THREAD

**Issue by dandv** [ncw/rclone#1743]
New to rclone, I've just tried to copy files from another laptop on the WLAN. The config looks like this:

```
[laptop]
type = sftp
host = 192.168.1.164
user = dandv
port = 22
pass = <my password in plain text>
key_file =
```

`scp dandv@192.168.1.164:.bashrc ./` works fine.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.38
- os/arch: linux/amd64
- go version: go1.9

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 16.04.3 64-bit

> Which cloud storage system are you using? (eg Google Drive)

SFTP

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone lsd laptop:`

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
DEBUG : Using config file from "/home/dandv/.config/rclone/rclone.conf"
DEBUG : rclone: Version "v1.38" starting with parameters ["rclone" "-vv" "lsd" "laptop:"]
Failed to create file system for "laptop:": input too short
```

The error should say what [exactly what input](https://github.com/ncw/rclone/blob/master/fs/config.go#L187) is too short.

**Comment by ncw** [comment]
Yes that error message is a bit cryptic!

Did you figure out that you need to have an obscured password in the config file?

Which you can generate with `rclone obscure mypassword`

**Comment by ncw** [comment]
I've fixed that error message to say: "input too short when revealing password - is it obscured?" which hopefully is enough of a clue.

Find that in a beta here

https://beta.rclone.org/v1.38-032-g11505393/ (uploaded in 15-30 mins)

**Comment by tspicer** [comment]
Just wanted to point out this issue will still occur if you are passing the password in as an ENV VAR vs a local config (at least as far as I can tell)
