### ISSUE TITLE
Copying to a local destination folder that doesn't exist fails on windows

### ISSUE THREAD

**Issue by Neurrone** [ncw/rclone#1754]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.38
- os/arch: windows/amd64
- go version: go1.9

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Win10 x64

> Which cloud storage system are you using? (eg Google Drive)
Dropbox, encrypted remote

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone copy EncryptedDropbox:/music "d:\restored"`

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```sh
D:\downloads\rclone-v1.38-windows-amd64>rclone copy EncryptedDropbox:/music "d:\restored" -vv
2017/10/19 02:32:25 DEBUG : Using config file from "C:\\Users\\Dickson\\.config\\rclone\\rclone.conf"
2017/10/19 02:32:25 DEBUG : rclone: Version "v1.38" starting with parameters ["rclone" "copy" "EncryptedDropbox:/music" "d:\\restored" "-vv"]
2017/10/19 02:32:28 INFO  : Local file system at \\?\d:\restored: Modify window is 1s
2017/10/19 02:32:31 ERROR : 02 Master Of Shadows.mp3: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
2017/10/19 02:32:31 ERROR : 04 Am I Not Human.mp3: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
```

The rest of the files has a similar error.

Works perfectly when I created the directory first before running the command.

**Comment by ncw** [comment]
The error `Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.` means that rclone had trouble making the destination directory.

Why that should be, I'm not sure... It seems to be trying to make the directory `\?` which is a bit strange!

I tested this out on my windows 7 VM and it worked fine, so I wonder if it is windows OS specific.

What happens if you just do `rclone -vv mkdir d:\newdirectory`?

This appears to be https://github.com/golang/go/issues/22230

**Comment by alexbrainman** [comment]
@ncw I wonder how `d:\restored` (from the command line) became `\\?\d:\restored` ? Where is the code that does that? Thank you.

Alex

**Comment by ncw** [comment]
@alexbrainman That code is [the uncPath() function](https://github.com/ncw/rclone/blob/master/local/local.go#L851)

rclone converts all paths to UNC paths to get round the 256 total char length (see #90 for background).

**Comment by alexbrainman** [comment]
> rclone converts all paths to UNC paths to get round the 256 total char length (see #90 for background).

Thanks for explaining. I suppose we just have to fix golang/go#22230

Alex

**Comment by ncw** [comment]
The fix for this missed go1.10 but it has landed in the go dev tree.

Here is rclone compiled with the fix (using the development version of go) - can you see if it fixes the problem?

[rclone-v1.40-032-geca99b33.zip](https://github.com/ncw/rclone/files/1866417/rclone-v1.40-032-geca99b33.zip)

**Comment by XristophD** [comment]
Awesome, I was running into the same error using RCLONE SYNC command where the destination path had to be created. Works with the current v1.40-032 release for me. 

Fix came just in time ... 40 Minutes. What a coincidence.

**Comment by ncw** [comment]
I've been compiling [the latest beta](https://beta.rclone.org) with go1.11rc1 so this issue should be fixed there.

I'm planning to release 1.43 after go1.11 is released so this issue should be fixed in a release then.

**Comment by EvgeniySpinov** [comment]
I'm running:

rclone --version
rclone v1.45
- os/arch: windows/amd64
- go version: go1.11

And the issue is still here. 

> 2018/12/01 17:27:45 ERROR : .dropbox.device: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
> 2018/12/01 17:27:45 ERROR : Broken_cables.mp4: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
> 2018/12/01 17:27:45 ERROR : Budynek_B_rzuty_elektryka.dwl: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
> 2018/12/01 17:27:45 ERROR : Budynek_B_rzuty_elektryka.dwl2: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.

And so on for all of the files, when I'm trying to run "copy". Destination disk is mounted Samba share, if it matters.

**Comment by ncw** [comment]
> I'm running:
> 
> rclone --version
> rclone v1.45
> 
> * os/arch: windows/amd64
> * go version: go1.11
> 
> And the issue is still here.
> 
> > 2018/12/01 17:27:45 ERROR : .dropbox.device: Failed to copy: mkdir \?: The filename, directory name, or volume label syntax is incorrect.
> > 2018/12/01 17:27:45 ERROR : Broken_cables.mp4: Failed to copy: mkdir \?: The filename, directory name, or volume label syntax is incorrect.
> > 2018/12/01 17:27:45 ERROR : Budynek_B_rzuty_elektryka.dwl: Failed to copy: mkdir \?: The filename, directory name, or volume label syntax is incorrect.
> > 2018/12/01 17:27:45 ERROR : Budynek_B_rzuty_elektryka.dwl2: Failed to copy: mkdir \?: The filename, directory name, or volume label syntax is incorrect.
> 
> And so on for all of the files, when I'm trying to run "copy". Destination disk is mounted Samba share, if it matters.

What version of windows are you using?

Can you try copying to a local disk to see if that makes a difference?

Can you share your command line too please?

Thanks

**Comment by ncw** [comment]
Can you try `--local-nounc` to see if that makes a difference?

      --local-nounc string               Disable UNC (long path names) conversion on Windows

Also can you try the `\\Device\mount\path` form of `S:` to see if that makes a difference?

**Comment by EvgeniySpinov** [comment]
Ok, it's to my shame, but I cannot reproduce the issue anymore. 

I've tried without --local-nounc first to make sure that issue exists, but that wasn't the case anymore. Tried with new directory created on remote server, i.e. starting sync from scratch, tried with "sync" and "copy" option - it just works.

None of configurations has changed.

However the issue was definitely there when I've tried the first time. I also tried in different variations and it didn't work.

Let me try to use the tool and come back here if issue will be spotted again with additional details.

Thank you for prompt support, guidance and amazing tool.

**Comment by ncw** [comment]
> Ok, it's to my shame, but I cannot reproduce the issue anymore.

That is a surprise! A [heisenbug](https://en.wikipedia.org/wiki/Heisenbug)?

I note that there is a thread on the forum with a very similar problem: https://forum.rclone.org/t/syncing-network-mounted-filesystem-from-windows-to-google-drive/7781



> Let me try to use the tool and come back here if issue will be spotted again with additional details.
> 
> Thank you for prompt support, guidance and amazing tool.

Great and thank you!

**Comment by xyxxyxxy** [comment]
> What is your rclone version (eg output from rclone -V)

rclone v1.45

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10 (1607) 64bit

> Which cloud storage system are you using? (eg Google Drive)

None, only local filesystem and mounted network drive.

> The command you were trying to run (eg rclone copy /tmp remote:tmp)

`c:\Users\xyxxyxxy\rclone\rclone.exe sync $HOME/1754_test_source "j:\1754_test_destination\"`


I ran into the error `Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.` while trying to schedule my rclone Powershell script with the Windows task scheduler.

The error only occurres if the script is started by the Windows task scheduler. It works if started with the Powershell CLI or CMD CLI directly.

I don't know how the Windows task scheduler differs from a Powershell or CMD CLI.
Following is a minimal test setup to reproduce the issue for further debugging.

#### Spoiler:
Using `\\Device\mount\path` worked for me.

## Setup to reproduce the error

#### Powershell script `1754_test.ps1`:
```
# \\DS416PLAY\Backup\ is mounted to j:/

c:\Users\xyxxyxxy\rclone\rclone.exe sync $HOME/1754_test_source "j:\1754_test_destination\" `
	--log-file "c:/Users/xyxxyxxy/rclone-scripts/1754_test.log" `
	-vv
```

#### Source folder `1754_test_source` with (empty) test file:
```
└───sub_folder
    └───sub_sub_folder
    └───file.txt
```

#### Picture of task configuration in Windows task scheduler:
![image](https://user-images.githubusercontent.com/7705456/50052476-e9888700-0124-11e9-9ad6-174ee9be21ea.png)
#### Picture of task action:
![image](https://user-images.githubusercontent.com/7705456/50052566-4afd2580-0126-11e9-85d5-639bd1c674f9.png)
#### Task action argument:
Add arguments (optional): `-ExecutionPolicy ByPass -File c:\Users\xyxxyxxy\rclone-scripts\1754_test.ps1`

## Results

The destination folder was deleted after each run.

### Running in CMD CLI (no problem)
`C:\Users\xyxxyxxy>Powershell.exe -ExecutionPolicy ByPass -File C:\Users\xyxxyxxy\rclone-scripts\1754_test.ps1`
#### Log:
```
2018/12/16 11:00:12 DEBUG : rclone: Version "v1.45" starting with parameters ["C:\\Users\\xyxxyxxy\\rclone\\rclone.exe" "sync" "C:\\Users\\xyxxyxxy/1754_test_source" "j:\\1754_test_destination\\" "--ignore-case" "--log-file" "c:/Users/xyxxyxxy/rclone-scripts/1754_test.log" "-vv"]
2018/12/16 11:00:12 DEBUG : Using config file from "C:\\Users\\xyxxyxxy\\.config\\rclone\\rclone.conf"
2018/12/16 11:00:12 INFO  : Local file system at \\?\j:\1754_test_destination: Waiting for checks to finish
2018/12/16 11:00:12 INFO  : Local file system at \\?\j:\1754_test_destination: Waiting for transfers to finish
2018/12/16 11:00:12 INFO  : file.txt: Copied (new)
2018/12/16 11:00:12 DEBUG : sub_folder/sub_sub_folder: Making directory
2018/12/16 11:00:12 DEBUG : Local file system at \\?\j:\1754_test_destination: copied 1 directories
2018/12/16 11:00:12 INFO  : Waiting for deletions to finish
2018/12/16 11:00:12 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            1 / 1, 100%
Elapsed time:       100ms

2018/12/16 11:00:12 DEBUG : 2 go routines active
2018/12/16 11:00:12 DEBUG : rclone: Version "v1.45" finishing with parameters ["C:\\Users\\xyxxyxxy\\rclone\\rclone.exe" "sync" "C:\\Users\\xyxxyxxy/1754_test_source" "j:\\1754_test_destination\\" "--ignore-case" "--log-file" "c:/Users/xyxxyxxy/rclone-scripts/1754_test.log" "-vv"]
```
### Running in Powershell CLI (no problem)
`PS C:\Users\xyxxyxxy\rclone-scripts> Powershell.exe -ExecutionPolicy ByPass -File C:\Users\xyxxyxxy\rclone-scripts\1754_test.ps1`

#### Log:
```
2018/12/16 10:59:10 DEBUG : rclone: Version "v1.45" starting with parameters ["C:\\Users\\xyxxyxxy\\rclone\\rclone.exe" "sync" "C:\\Users\\xyxxyxxy/1754_test_source" "j:\\1754_test_destination\\" "--ignore-case" "--log-file" "c:/Users/xyxxyxxy/rclone-scripts/1754_test.log" "-vv"]
2018/12/16 10:59:10 DEBUG : Using config file from "C:\\Users\\xyxxyxxy\\.config\\rclone\\rclone.conf"
2018/12/16 10:59:10 INFO  : Local file system at \\?\j:\1754_test_destination: Waiting for checks to finish
2018/12/16 10:59:10 INFO  : Local file system at \\?\j:\1754_test_destination: Waiting for transfers to finish
2018/12/16 10:59:10 INFO  : file.txt: Copied (new)
2018/12/16 10:59:10 DEBUG : sub_folder/sub_sub_folder: Making directory
2018/12/16 10:59:10 DEBUG : Local file system at \\?\j:\1754_test_destination: copied 1 directories
2018/12/16 10:59:10 INFO  : Waiting for deletions to finish
2018/12/16 10:59:10 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            1 / 1, 100%
Elapsed time:          0s

2018/12/16 10:59:10 DEBUG : 2 go routines active
2018/12/16 10:59:10 DEBUG : rclone: Version "v1.45" finishing with parameters ["C:\\Users\\xyxxyxxy\\rclone\\rclone.exe" "sync" "C:\\Users\\xyxxyxxy/1754_test_source" "j:\\1754_test_destination\\" "--ignore-case" "--log-file" "c:/Users/xyxxyxxy/rclone-scripts/1754_test.log" "-vv"]
```

### Started via Windows task scheduler (error)

#### Log:
```
2018/12/16 10:58:48 DEBUG : rclone: Version "v1.45" starting with parameters ["C:\\Users\\xyxxyxxy\\rclone\\rclone.exe" "sync" "C:\\Users\\xyxxyxxy/1754_test_source" "j:\\1754_test_destination\\" "--ignore-case" "--log-file" "c:/Users/xyxxyxxy/rclone-scripts/1754_test.log" "-vv"]
2018/12/16 10:58:48 DEBUG : Using config file from "C:\\Users\\xyxxyxxy\\.config\\rclone\\rclone.conf"
2018/12/16 10:58:48 INFO  : Local file system at \\?\j:\1754_test_destination: Waiting for checks to finish
2018/12/16 10:58:48 INFO  : Local file system at \\?\j:\1754_test_destination: Waiting for transfers to finish
2018/12/16 10:58:48 ERROR : file.txt: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
2018/12/16 10:58:48 DEBUG : sub_folder/sub_sub_folder: Making directory
2018/12/16 10:58:48 ERROR : sub_folder/sub_sub_folder: Failed to Mkdir: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
2018/12/16 10:58:48 DEBUG : Local file system at \\?\j:\1754_test_destination: failed to copy 2 directories
2018/12/16 10:58:48 ERROR : Local file system at \\?\j:\1754_test_destination: not deleting files as there were IO errors
2018/12/16 10:58:48 ERROR : Local file system at \\?\j:\1754_test_destination: not deleting directories as there were IO errors
2018/12/16 10:58:48 ERROR : Attempt 1/3 failed with 2 errors and: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
2018/12/16 10:58:48 ERROR : file.txt: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
2018/12/16 10:58:48 INFO  : Local file system at \\?\j:\1754_test_destination: Waiting for checks to finish
2018/12/16 10:58:48 INFO  : Local file system at \\?\j:\1754_test_destination: Waiting for transfers to finish
2018/12/16 10:58:48 DEBUG : sub_folder/sub_sub_folder: Making directory
2018/12/16 10:58:48 ERROR : sub_folder/sub_sub_folder: Failed to Mkdir: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
2018/12/16 10:58:48 DEBUG : Local file system at \\?\j:\1754_test_destination: failed to copy 2 directories
2018/12/16 10:58:48 ERROR : Local file system at \\?\j:\1754_test_destination: not deleting files as there were IO errors
2018/12/16 10:58:48 ERROR : Local file system at \\?\j:\1754_test_destination: not deleting directories as there were IO errors
2018/12/16 10:58:48 ERROR : Attempt 2/3 failed with 2 errors and: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
2018/12/16 10:58:48 ERROR : file.txt: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
2018/12/16 10:58:48 INFO  : Local file system at \\?\j:\1754_test_destination: Waiting for checks to finish
2018/12/16 10:58:48 INFO  : Local file system at \\?\j:\1754_test_destination: Waiting for transfers to finish
2018/12/16 10:58:48 DEBUG : sub_folder/sub_sub_folder: Making directory
2018/12/16 10:58:48 ERROR : sub_folder/sub_sub_folder: Failed to Mkdir: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
2018/12/16 10:58:48 DEBUG : Local file system at \\?\j:\1754_test_destination: failed to copy 2 directories
2018/12/16 10:58:48 ERROR : Local file system at \\?\j:\1754_test_destination: not deleting files as there were IO errors
2018/12/16 10:58:48 ERROR : Local file system at \\?\j:\1754_test_destination: not deleting directories as there were IO errors
2018/12/16 10:58:48 ERROR : Attempt 3/3 failed with 2 errors and: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
2018/12/16 10:58:48 Failed to sync: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
```

#### Info
I also tried with `--local-nounc true` set, but the results did not change.

## Workaround
> Also can you try the `\\Device\mount\path` form of `S:` to see if that makes a difference?

This worked for me by replacing `j:\` in `1754_test.ps` with `\\DS416PLAY\Backup\`.

**Comment by EvgeniySpinov** [comment]
I have exactly the same problem and came here to report it, however I see that @xyxxyxxy already did a great job.

I'm scheduling task without powershell, just plain command and getting the same issue. Tried with elevated permissions - no luck. 

And for me workaround with \\Server\Share\path doesn't work.

Otherwise the same tests as described in post above.

Command was:

`C:\TOOLS\rclone.exe --checkers 18 --log-file "D:\rclone.log" -v sync D:\ "S:\AMEE_SECONDARY"`

Result was:

`2018/12/16 21:58:52 NOTICE: Config file "C:\\Users\\Dark Angel\\.config\\rclone\\rclone.conf" not found - using defaults
2018/12/16 21:58:53 ERROR : System Volume Information: error reading source directory: failed to open directory "System Volume Information": open \\?\D:\Sy
stem Volume Information: Access is denied.
2018/12/16 21:58:54 ERROR : Defective_AD8400.mp4: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
2018/12/16 21:58:54 ERROR : .dropbox.device: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
2018/12/16 21:58:55 ERROR : rclone.log: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
2018/12/16 21:58:55 ERROR : SyncToy_14812056-c225-4bd5-8a2f-7e1e41043943.dat: Failed to copy: mkdir \\?: The filename, directory name, or volume label synt
ax is incorrect.
2018/12/16 21:58:55 ERROR : SyncToy_7125c5fb-93b3-4689-aac8-9867e44e4e5c.dat: Failed to copy: mkdir \\?: The filename, directory name, or volume label synt
ax is incorrect.`

**Comment by ncw** [comment]
> I have exactly the same problem and came here to report it, however I see that @xyxxyxxy already did a great job.

Which version of rclone are you using?  Have you tried [the latest release](https://rclone.org/downloads/)?

**Comment by EvgeniySpinov** [comment]
I have exactly the same versions of rclone and Windows. Rclone is latest as I can see.

rclone v1.45
- os/arch: windows/amd64
- go version: go1.11

Windows 10 (1607) 64bit

**Comment by ncw** [comment]
> Seems like the issue is somehow linked to the way how Windows allows to see mapped network drives. For example mapped drive is not visible under Administrator account, however it is visible under the user I'm trying to use.

If someone would like to propose some more docs explaining this, I'd be grateful.

Here is the source of the docs

https://github.com/ncw/rclone/blob/9d16822c63e288767211aca27c880eb3dbffad1b/cmd/mountlib/mount.go#L96

**Comment by EvgeniySpinov** [comment]
Well, the issue that I've seen exactly the same piece of documentation somewhere in MSDN. My disks are mapped by Windows (map on startup) and are visible under the user I'm working with (Single user in the system) and not visible under Administrator.

However probably in Task Scheduler it's also somehow affected.

Rclone is executed under the user where disks are visible. User account in Task Scheduler is set to the same user. You can refer to @xyxxyxxy screenshot - I have the same settings userwise, just the names are different.

**Comment by krsentai** [comment]
I seem to be getting the same "Couldn't move: mkdir \\?\G:\newfolder: A device which does not exist was specified." error that @ncw mentioned earlier in the thread, using local drives. I'm using 1.66.0 on Win11 23H2.

**Comment by ncw** [comment]
@krsentai can you open a [new issue](https://github.com/rclone/rclone/issues/new/choose) please. Can you fill in the details of the issue with a method of reproducing and we will investigate - thanks.
