### ISSUE TITLE
#ZgotmplZ as link in serve http

### ISSUE THREAD

**Issue by uwe-schwarz** [ncw/rclone#1939]
> What is your rclone version (eg output from `rclone -V`)

```
rclone v1.39
- os/arch: linux/amd64
- go version: go1.9.2
```

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 16.04

> Which cloud storage system are you using? (eg Google Drive)

Google Drive encrypted

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone serve http remote:

In one of my directories must be some bad character and I get this as links:
`<a href="#ZgotmplZ">example/</a>`

I have quite a few folder names in there with non-ascii characters, but I'm unsure which causes the issue. Seems to be related to https://stackoverflow.com/questions/14765395/why-am-i-seeing-zgotmplz-in-my-go-html-template-output

Looks like it happens if the folder contains a ":".

**Comment by ncw** [comment]
This is easy to replicate by trying to serve a file with a `:` in it as you suggested.

I'll fix shortly then post a beta for you to try.

**Comment by ncw** [comment]
I've fixed this now - please find a beta here

https://beta.rclone.org/v1.39-004-g65618afd/ (uploaded in 15-30 mins)

**Comment by uwe-schwarz** [comment]
I built it from github/master (used on Linux, not Windows), but it's still showing the wrong link.

This was my starting line:
2018/01/06 10:05:29 DEBUG : rclone: Version "v1.39-DEV" starting with parameters ["go/bin/rclone" "serve" "-vv" "http" "foo:"]
Last commit in my src: commit 65618afd8cfa5c63a2baa9605723e32f118a9312

**Comment by ncw** [comment]
Can you make a standalone example which replicates the problem please? So some shell commands to reproduce a directory tree which shows the problem?

Thanks

**Comment by uwe-schwarz** [comment]
Nevermind, I tried with your version (rclone-v1.39-004-g65618afdβ-linux-amd64.zip) and it worked. I probably got something wrong with compiling my own version.

Thanks for fixing this so fast :)

**Comment by ncw** [comment]
Glad it is working now :-)
