### ISSUE TITLE
inode usage 100%

### ISSUE THREAD

**Issue by mechanimal82** [ncw/rclone#2089]
As mentioned in the forum I’m using netdata to help monitor my system (a Hetzner dedicated) and have noticed that it’s giving me warnings about inode usage from my Plex mount… is this normal because of the way fuse/rclone works, or is something wrong and needs fixing?

Output of df -i:
```
$ df -i /mnt/plex
Filesystem         Inodes      IUsed IFree IUse% Mounted on
cachedecrypt:  1000000000 1000000000     0  100% /mnt/plex
```
Link to forum post: https://forum.rclone.org/t/inode-usage-maxed-out/4872

> What is your rclone version (eg output from `rclone -V`)
rclone v1.39-149-g442334ba

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 17.10 (4.13.0-32 generic) x86_64

> Which cloud storage system are you using? (eg Google Drive)
Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
df -i

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
N/A

**Comment by ncw** [comment]
It looks like this is a bug in the fuse library rclone is using.  I've reported an issue: https://github.com/bazil/fuse/issues/194

I couldn't see an easy fix though!

**Comment by ncw** [comment]
This is now fixed here

https://beta.rclone.org/v1.40-113-gd36b80f5/ (uploaded in 15-30 mins)

which will be in [the latest beta](https://beta.rclone.org) from now on and 1.41.

**Comment by chauffer** [comment]
Still encountering this with 1.41 and 1.42b

```
root@air:/mnt/gdrive# rclone -V; df -i /mnt/gdrive
rclone v1.42-001-g71103495β
- os/arch: linux/amd64
- go version: go1.10.1
Filesystem         Inodes IUsed      IFree IUse% Mounted on
gdrive:        1000000000     0 1000000000    0% /mnt/gdrive
root@air:/mnt/gdrive#
```

I have mounted it with the new binary, but I haven't changed anything else. Is there any way I could be using the old version? I had 1.35 installed via .sh script before, and I had to manually `rm /usr/sbin/rclone` before the script would install the latest version.

**Comment by ncw** [comment]
@chauffer which provider are you using? Not all support this feature.

**Comment by chauffer** [comment]
@ncw Google Drive, apologies for not including it, I thought it was obvious from the name 😇

**Comment by ncw** [comment]
@chauffer probably should have been obvious :-)  Is it a team drive?  If so then team drives don't support reading the size used and the size free alas.

What does `rclone about gdrive:` say?

**Comment by chauffer** [comment]
```
root@air:~# rclone about gdrive
2018/06/17 18:35:36 Failed to about: About call failed: failed to read disk usage: no such file or directory
```
Both before & after having it mounted with this cmd

```
root@air:~# rclone mount --allow-non-empty --allow-other --max-read-ahead 200M gdrive:/ /mnt/gdrive
```
It is not a team drive, but it is a G Suite individual drive

**Comment by B4dM4n** [comment]
> df -i /mnt/gdrive
Filesystem         Inodes IUsed      IFree IUse% Mounted on
gdrive:        1000000000     0 1000000000    0% /mnt/gdrive

This output looks correct to me. It shows 0 inodes in use and `0%` usage.

The original issue was the display of `100%` usage.

**Comment by ncw** [comment]
Thanks @B4dM4n for setting me and @chauffer straight - I was looking at the 0 readings having failed to notice that this was about inodes :blush:
