### ISSUE TITLE
rclone mount has zero blocks available

### ISSUE THREAD

**Issue by as-com** [ncw/rclone#2356]
#### What is the problem you are having with rclone?
```
>>> import os
>>> os.statvfs("/Users/andrew/rclone-mnt/google/")
posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=0, f_bfree=4275873052, f_bavail=0, f_files=1000000000, f_ffree=1000000000, f_favail=1000000000, f_flag=2, f_namemax=255)
```
f_bavail being 0 confuses software like https://github.com/borgbackup/borg/blob/3bdfa869d62c6f9d5bd87db493e8d96433810117/src/borg/repository.py#L646

I cannot figure out which layer the problem comes from. 😕 

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.41
- os/arch: darwin/amd64
- go version: go1.10.1

(cannot reproduce with latest beta because of #2355)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
macOS Mojave Developer Preview 2 10.14 Beta (18A314h)

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount --vfs-cache-mode writes --no-modtime google: -vv ./rclone-mnt/google

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2018/06/20 20:01:54 DEBUG : rclone: Version "v1.41" starting with parameters ["rclone" "mount" "--vfs-cache-mode" "writes" "--no-modtime" "google:" "-vv" "./rclone-mnt/google"]
2018/06/20 20:01:54 DEBUG : Using config file from "/Users/andrew/.config/rclone/rclone.conf"
2018/06/20 20:01:54 INFO  : Google drive root '': Modify window is 1ms
2018/06/20 20:01:54 DEBUG : Google drive root '': Mounting on "./rclone-mnt/google"
2018/06/20 20:01:54 DEBUG : vfs cache root is "/Users/andrew/Library/Caches/rclone/vfs/google"
2018/06/20 20:01:54 DEBUG : Adding path "vfs/forget" to remote control registry
2018/06/20 20:01:54 DEBUG : : Root:
2018/06/20 20:01:54 DEBUG : : >Root: node=/, err=<nil>
2018/06/20 20:01:54 DEBUG : : Statfs:
2018/06/20 20:01:54 DEBUG : /: Attr:
2018/06/20 20:01:54 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/06/20 20:01:54 DEBUG : : Statfs:
2018/06/20 20:01:54 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : Google drive root '': Checking for changes on remote
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : Google drive root '': All changes were processed. Waiting for more.
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : : Statfs:
2018/06/20 20:01:55 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:55 DEBUG : /: Lookup: name=".localized"
2018/06/20 20:01:55 DEBUG : pacer: Rate limited, sleeping for 1.444026182s (1 consecutive low level retries)
2018/06/20 20:01:55 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/06/20 20:01:55 DEBUG : pacer: Rate limited, sleeping for 2.066625023s (2 consecutive low level retries)
2018/06/20 20:01:55 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/06/20 20:01:57 DEBUG : pacer: Resetting sleep to minimum 10ms on success
2018/06/20 20:01:57 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/06/20 20:01:57 DEBUG : /: Attr:
2018/06/20 20:01:57 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/06/20 20:01:57 DEBUG : /: Lookup: name=".localized"
2018/06/20 20:01:57 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/06/20 20:01:57 DEBUG : : Statfs:
2018/06/20 20:01:57 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:57 DEBUG : : Statfs:
2018/06/20 20:01:57 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:57 DEBUG : : Statfs:
2018/06/20 20:01:57 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:57 DEBUG : : Statfs:
2018/06/20 20:01:57 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:57 DEBUG : : Statfs:
2018/06/20 20:01:57 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:01:57 DEBUG : /: Lookup: name=".localized"
2018/06/20 20:01:57 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/06/20 20:02:13 DEBUG : /: Attr:
2018/06/20 20:02:13 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/06/20 20:02:13 DEBUG : : Statfs:
2018/06/20 20:02:13 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:02:25 DEBUG : /: Lookup: name="backup"
2018/06/20 20:02:25 DEBUG : /: >Lookup: node=backup/, err=<nil>
2018/06/20 20:02:25 DEBUG : backup/: Attr:
2018/06/20 20:02:25 DEBUG : backup/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/06/20 20:02:25 DEBUG : : Statfs:
2018/06/20 20:02:25 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:02:25 DEBUG : : Statfs:
2018/06/20 20:02:25 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/20 20:02:28 DEBUG : : Statfs:
2018/06/20 20:02:28 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
^C2018/06/20 20:02:38 DEBUG : cache cleaner exiting
2018/06/20 20:02:38 DEBUG : rclone: Version "v1.41" finishing with parameters ["rclone" "mount" "--vfs-cache-mode" "writes" "--no-modtime" "google:" "-vv" "./rclone-mnt/google"]

**Comment by ncw** [comment]
This is fixed in v1.42 I believe!

https://github.com/ncw/rclone/issues/2089

**Comment by as-com** [comment]
I compiled rclone from source, and...
```
>>> import os
>>> os.statvfs("/Users/andrew/rclone-mnt/google")
posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=0, f_bfree=4275873052, f_bavail=0, f_files=1000000000, f_ffree=1000000000, f_favail=1000000000, f_flag=2, f_namemax=255)
```

```
~
❯ ~/go/bin/rclone mount --vfs-cache-mode writes --no-modtime google: -vv ~/rclone-mnt/google
2018/06/21 11:25:19 DEBUG : rclone: Version "v1.42-DEV" starting with parameters ["/Users/andrew/go/bin/rclone" "mount" "--vfs-cache-mode" "writes" "--no-modtime" "google:" "-vv" "/Users/andrew/rclone-mnt/google"]
2018/06/21 11:25:19 DEBUG : Using config file from "/Users/andrew/.config/rclone/rclone.conf"
2018/06/21 11:25:19 DEBUG : Google drive root '': Mounting on "/Users/andrew/rclone-mnt/google"
2018/06/21 11:25:19 DEBUG : vfs cache root is "/Users/andrew/Library/Caches/rclone/vfs/google"
2018/06/21 11:25:19 DEBUG : Adding path "vfs/forget" to remote control registry
2018/06/21 11:25:19 DEBUG : : Root:
2018/06/21 11:25:19 DEBUG : : >Root: node=/, err=<nil>
2018/06/21 11:25:19 DEBUG : : Statfs:
2018/06/21 11:25:19 DEBUG : /: Attr:
2018/06/21 11:25:19 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/06/21 11:25:19 DEBUG : : Statfs:
2018/06/21 11:25:19 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : Google drive root '': Checking for changes on remote
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : /: Attr:
2018/06/21 11:25:24 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : Google drive root '': All changes were processed. Waiting for more.
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : /: Lookup: name=".localized"
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/06/21 11:25:24 DEBUG : /: Lookup: name=".localized"
2018/06/21 11:25:24 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:24 DEBUG : : Statfs:
2018/06/21 11:25:24 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:25 DEBUG : /: Lookup: name=".localized"
2018/06/21 11:25:25 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/06/21 11:25:25 DEBUG : : Statfs:
2018/06/21 11:25:25 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:28 DEBUG : /: Attr:
2018/06/21 11:25:28 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/06/21 11:25:28 DEBUG : /: Lookup: name=".hidden"
2018/06/21 11:25:28 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/06/21 11:25:28 DEBUG : /: ReadDirAll:
2018/06/21 11:25:28 DEBUG : /: >ReadDirAll: item=2, err=<nil>
2018/06/21 11:25:28 DEBUG : /: Lookup: name="Getting started.pdf"
2018/06/21 11:25:28 DEBUG : /: >Lookup: node=Getting started.pdf, err=<nil>
2018/06/21 11:25:28 DEBUG : Getting started.pdf: Attr:
2018/06/21 11:25:28 DEBUG : Getting started.pdf: >Attr: a=valid=1s ino=0 size=696774 mode=-rw-r--r--, err=<nil>
2018/06/21 11:25:28 DEBUG : /: Lookup: name="backup"
2018/06/21 11:25:28 DEBUG : /: >Lookup: node=backup/, err=<nil>
2018/06/21 11:25:28 DEBUG : backup/: Attr:
2018/06/21 11:25:28 DEBUG : backup/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/06/21 11:25:28 DEBUG : backup/: Lookup: name=".localized"
2018/06/21 11:25:28 DEBUG : /: Lookup: name=".localized"
2018/06/21 11:25:28 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/06/21 11:25:28 DEBUG : /: Attr:
2018/06/21 11:25:28 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/06/21 11:25:28 DEBUG : : Statfs:
2018/06/21 11:25:28 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:28 DEBUG : /: Lookup: name=".localized"
2018/06/21 11:25:28 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/06/21 11:25:28 DEBUG : : Statfs:
2018/06/21 11:25:28 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:28 DEBUG : : Statfs:
2018/06/21 11:25:28 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:28 DEBUG : : Statfs:
2018/06/21 11:25:28 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:28 DEBUG : backup/: >Lookup: node=<nil>, err=no such file or directory
2018/06/21 11:25:28 DEBUG : : Statfs:
2018/06/21 11:25:28 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:28 DEBUG : /: Lookup: name=".localized"
2018/06/21 11:25:28 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/06/21 11:25:29 DEBUG : /: Attr:
2018/06/21 11:25:29 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/06/21 11:25:32 DEBUG : /: Attr:
2018/06/21 11:25:32 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/06/21 11:25:32 DEBUG : /: ReadDirAll:
2018/06/21 11:25:32 DEBUG : /: >ReadDirAll: item=2, err=<nil>
2018/06/21 11:25:32 DEBUG : Getting started.pdf: Attr:
2018/06/21 11:25:32 DEBUG : Getting started.pdf: >Attr: a=valid=1s ino=0 size=696774 mode=-rw-r--r--, err=<nil>
2018/06/21 11:25:32 DEBUG : backup/: Attr:
2018/06/21 11:25:32 DEBUG : backup/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/06/21 11:25:32 DEBUG : /: Attr:
2018/06/21 11:25:32 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/06/21 11:25:32 DEBUG : : Statfs:
2018/06/21 11:25:32 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:35 DEBUG : /: Attr:
2018/06/21 11:25:35 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/06/21 11:25:37 DEBUG : /: Attr:
2018/06/21 11:25:37 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/06/21 11:25:44 DEBUG : /: Attr:
2018/06/21 11:25:44 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/06/21 11:25:44 DEBUG : : Statfs:
2018/06/21 11:25:44 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:44 DEBUG : : Statfs:
2018/06/21 11:25:44 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/06/21 11:25:46 DEBUG : : Statfs:
2018/06/21 11:25:46 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
^C2018/06/21 11:25:52 DEBUG : cache cleaner exiting
2018/06/21 11:25:52 DEBUG : rclone: Version "v1.42-DEV" finishing with parameters ["/Users/andrew/go/bin/rclone" "mount" "--vfs-cache-mode" "writes" "--no-modtime" "google:" "-vv" "/Users/andrew/rclone-mnt/google"]
```

```
~
❯ ~/go/bin/rclone -V
rclone v1.42-DEV
- os/arch: darwin/amd64
- go version: go1.10.3
```

So this is still not fixed...

**Comment by ncw** [comment]
I've just realised that I misread your title - it is blocks not inodes that is the problem.  

This appears to work OK for linux

```
$ df -i /mnt/tmp/
Filesystem          Inodes IUsed      IFree IUse% Mounted on
local:/tmp/test 1000000000     0 1000000000    0% /mnt/tmp
```

```
$  df /mnt/tmp/
Filesystem      1K-blocks      Used Available Use% Mounted on
local:/tmp/test 475425880 465914292   9495204  99% /mnt/tmp
```

and

```
>>> import os
>>> os.statvfs("/mnt/tmp")
posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=118856470, f_bfree=2378046, f_bavail=2373950, f_files=1000000000, f_ffree=1000000000, f_favail=1000000000, f_flag=4102, f_namemax=255)
>>> 
```

It might be worth studying https://github.com/bazil/fuse/issues/194 and the fix to see if there is a macOS fix which got missed.

Also if you can compile rclone from source then can you compile with `go install -tags cmount` (or go build if you prefer) and then try `rclone cmount` to see if that has the same problem?  That uses the FUSE library directly via a cgo shim rather than the bazil FUSE layer linked above.

Also see if `rclone about` gives the results you expect...

**Comment by as-com** [comment]
I can't compile with `-tags cmount` because of https://github.com/golang/go/issues/25908. I guess I'll have to wait for it to be released.

```
~/go/src/github.com/ncw/rclone master
❯ ~/go/bin/rclone about google:
Used:    72.839G
Trashed: 628.072M
Other:   0
```
Seems fine to me

**Comment by ncw** [comment]
Can you try this build: https://1037-17803236-gh.circle-artifacts.com/0/tmp/rclone.dist/rclone-darwin-10.6-amd64

That is a macOS native build.  Can youtry both mount and cmount on that?

We can see rclone internally is returning this:

    Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096},

Wheras your python call returns this

    f_bsize=4096, f_frsize=4096, f_blocks=0, f_bfree=4275873052, f_bavail=0, f_files=1000000000, f_ffree=1000000000, f_favail=1000000000, f_flag=2, f_namemax=255

Comparing the two...

```
Blocks:274877906944 f_blocks=0
Bfree:274858812700  f_bfree=4275873025
Bavail:274877906944 f_bavail=0
Files:1000000000    f_files=1000000000
Ffree:1000000000    f_ffree=1000000000
Bsize:4096          f_bsize=4096
Namelen:255         f_namemax=255
Frsize:4096         f_frsize=4096
                    f_favail=1000000000
                    f_flag=2
```

Because `rclone about` doesn't show a max size then rclone will be using 1PB as the free figure which you can see above: 274877906944*4096 = 1PB

What I don't understand is why the bfree don't match...  Under linux they match perfectly:

    Blocks:118856470 Bfree:2370866 Bavail:2366770 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096
    f_bsize=4096, f_frsize=4096, f_blocks=118856470, f_bfree=2370866, f_bavail=2366770, f_files=1000000000, f_ffree=1000000000, f_favail=1000000000, f_flag=4102, f_namemax=255

Looking at the two numbers in hex

```
>>> "%x"%274858812700
'3ffedca51c'
>>> "%x"%4275873025
'fedca501'
```

It looks like the Bavail has been truncated to 32 bits.

I wonder whether that number is too big for macOS.

Can you also try rclone mounting a local directory and see how that works:

    rclone mount /path/to/directory /path/to/mountpoint

**Comment by as-com** [comment]
With the above build:
rclone mount:
```
>>> import os
>>> os.statvfs("/Users/andrew/rclone-mnt/google")
posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=0, f_bfree=4275873052, f_bavail=0, f_files=1000000000, f_ffree=1000000000, f_favail=1000000000, f_flag=2, f_namemax=255)
```
```
2018/06/25 13:59:49 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274858812700 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
```

rclone cmount does not show up in Finder (socketfilterfw eats CPU), but I'm still able to grab a statvfs:
``
>>> os.statvfs("/Users/andrew/rclone-mnt/google")
posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=0, f_bfree=4275873052, f_bavail=0, f_files=1000000000, f_ffree=1000000000, f_favail=1000000000, f_flag=2, f_namemax=255)
```
```
~/Downloads 37s
❯ ./rclone-darwin-10.6-amd64 cmount --vfs-cache-mode writes --no-modtime google: -vv ~/rclone-mnt/google
2018/06/25 14:01:20 DEBUG : rclone: Version "v1.42-DEV" starting with parameters ["./rclone-darwin-10.6-amd64" "cmount" "--vfs-cache-mode" "writes" "--no-modtime" "google:" "-vv" "/Users/andrew/rclone-mnt/google"]
2018/06/25 14:01:20 DEBUG : Using config file from "/Users/andrew/.config/rclone/rclone.conf"
2018/06/25 14:01:20 DEBUG : Google drive root '': Mounting on "/Users/andrew/rclone-mnt/google"
2018/06/25 14:01:20 DEBUG : vfs cache root is "/Users/andrew/Library/Caches/rclone/vfs/google"
2018/06/25 14:01:20 DEBUG : Adding path "vfs/forget" to remote control registry
2018/06/25 14:01:20 DEBUG : Google drive root '': Mounting with options: ["-o" "fsname=google:" "-o" "subtype=rclone" "-o" "max_readahead=131072" "-o" "attr_timeout=1" "-o" "atomic_o_trunc" "-o" "volname=google" "-o" "noappledouble"]
2018/06/25 14:01:21 DEBUG : Google drive root '': Init:
2018/06/25 14:01:21 DEBUG : Google drive root '': >Init:
2018/06/25 14:01:21 DEBUG : /: Statfs:
2018/06/25 14:01:21 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/06/25 14:01:21 DEBUG : /: >Getattr: errc=0
2018/06/25 14:01:21 DEBUG : /: Statfs:
2018/06/25 14:01:21 DEBUG : /: Statfs:
2018/06/25 14:01:21 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:1125899906842624 Bfree:1125899887748380 Bavail:1125899906842624 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
2018/06/25 14:01:21 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:1125899906842624 Bfree:1125899887748380 Bavail:1125899906842624 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
2018/06/25 14:01:21 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:1125899906842624 Bfree:1125899887748380 Bavail:1125899906842624 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
2018/06/25 14:01:21 DEBUG : /: Statfs:
2018/06/25 14:01:21 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:1125899906842624 Bfree:1125899887748380 Bavail:1125899906842624 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
2018/06/25 14:01:21 DEBUG : Google drive root '': Checking for changes on remote
2018/06/25 14:01:21 DEBUG : /: Access: mask=00
2018/06/25 14:01:21 DEBUG : /: >Access: errc=0
2018/06/25 14:01:21 DEBUG : /: Statfs:
2018/06/25 14:01:21 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:1125899906842624 Bfree:1125899887748380 Bavail:1125899906842624 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
2018/06/25 14:01:21 DEBUG : /: Statfs:
2018/06/25 14:01:21 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:1125899906842624 Bfree:1125899887748380 Bavail:1125899906842624 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
2018/06/25 14:01:21 DEBUG : /: Access: mask=00
2018/06/25 14:01:21 DEBUG : /: >Access: errc=0
2018/06/25 14:01:21 DEBUG : /: Access: mask=04
2018/06/25 14:01:21 DEBUG : /: >Access: errc=0
2018/06/25 14:01:21 DEBUG : /: Opendir:
2018/06/25 14:01:21 DEBUG : /: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2018/06/25 14:01:21 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2018/06/25 14:01:21 DEBUG : /: >Opendir: errc=0, fh=0x0
2018/06/25 14:01:21 DEBUG : /: Releasedir: fh=0x0
2018/06/25 14:01:21 DEBUG : /: >Releasedir: errc=0
2018/06/25 14:01:21 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/06/25 14:01:21 DEBUG : /: >Getattr: errc=0
2018/06/25 14:01:21 DEBUG : /: Access: mask=00
2018/06/25 14:01:21 DEBUG : /: >Access: errc=0
2018/06/25 14:01:21 DEBUG : /: Statfs:
2018/06/25 14:01:21 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:1125899906842624 Bfree:1125899887748380 Bavail:1125899906842624 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
2018/06/25 14:01:21 DEBUG : /: Statfs:
2018/06/25 14:01:21 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:1125899906842624 Bfree:1125899887748380 Bavail:1125899906842624 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
2018/06/25 14:01:21 DEBUG : /: Access: mask=04
2018/06/25 14:01:21 DEBUG : /: >Access: errc=0
2018/06/25 14:01:21 DEBUG : /: Opendir:
2018/06/25 14:01:21 DEBUG : /: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2018/06/25 14:01:21 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2018/06/25 14:01:21 DEBUG : /: >Opendir: errc=0, fh=0x0
2018/06/25 14:01:21 DEBUG : /: Statfs:
2018/06/25 14:01:21 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:1125899906842624 Bfree:1125899887748380 Bavail:1125899906842624 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
2018/06/25 14:01:21 DEBUG : /DCIM: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/06/25 14:01:22 DEBUG : Google drive root '': All changes were processed. Waiting for more.
2018/06/25 14:01:22 DEBUG : /DCIM: >Getattr: errc=-2
2018/06/25 14:01:22 DEBUG : /: Access: mask=00
2018/06/25 14:01:22 DEBUG : /: >Access: errc=0
2018/06/25 14:01:22 DEBUG : /: Access: mask=00
2018/06/25 14:01:22 DEBUG : /: >Access: errc=0
2018/06/25 14:01:22 DEBUG : /: Access: mask=00
2018/06/25 14:01:22 DEBUG : /: >Access: errc=0
2018/06/25 14:01:22 DEBUG : /.Spotlight-V100: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/06/25 14:01:22 DEBUG : /.Spotlight-V100: >Getattr: errc=-2
2018/06/25 14:01:22 DEBUG : /.metadata_never_index: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/06/25 14:01:22 DEBUG : /.metadata_never_index: >Getattr: errc=-2
2018/06/25 14:01:22 DEBUG : /.metadata_never_index_unless_rootfs: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/06/25 14:01:22 DEBUG : /.metadata_never_index_unless_rootfs: >Getattr: errc=-2
2018/06/25 14:01:22 DEBUG : /: Access: mask=00
2018/06/25 14:01:22 DEBUG : /: >Access: errc=0
2018/06/25 14:01:22 DEBUG : /.metadata_never_index: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/06/25 14:01:22 DEBUG : /.metadata_never_index: >Getattr: errc=-2
2018/06/25 14:01:22 DEBUG : /.metadata_never_index_unless_rootfs: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/06/25 14:01:22 DEBUG : /.metadata_never_index_unless_rootfs: >Getattr: errc=-2
2018/06/25 14:01:22 DEBUG : /: Access: mask=00
2018/06/25 14:01:22 DEBUG : /: >Access: errc=0
2018/06/25 14:01:22 DEBUG : /: Access: mask=00
2018/06/25 14:01:22 DEBUG : /: >Access: errc=0
2018/06/25 14:01:22 DEBUG : /: Access: mask=00
2018/06/25 14:01:22 DEBUG : /: >Access: errc=0
2018/06/25 14:01:22 DEBUG : /: Access: mask=00
2018/06/25 14:01:22 DEBUG : /: >Access: errc=0
2018/06/25 14:01:22 DEBUG : /: Access: mask=00
2018/06/25 14:01:22 DEBUG : /: >Access: errc=0
2018/06/25 14:01:22 DEBUG : /: Access: mask=00
2018/06/25 14:01:22 DEBUG : /: >Access: errc=0
2018/06/25 14:01:22 DEBUG : /: Access: mask=00
2018/06/25 14:01:22 DEBUG : /: >Access: errc=0
2018/06/25 14:01:22 DEBUG : /: Statfs:
2018/06/25 14:01:22 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:1125899906842624 Bfree:1125899887748380 Bavail:1125899906842624 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
2018/06/25 14:01:22 DEBUG : /: Statfs:
2018/06/25 14:01:22 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:1125899906842624 Bfree:1125899887748380 Bavail:1125899906842624 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
2018/06/25 14:01:22 DEBUG : /: Statfs:
2018/06/25 14:01:22 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:1125899906842624 Bfree:1125899887748380 Bavail:1125899906842624 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
2018/06/25 14:01:22 DEBUG : /: Access: mask=00
2018/06/25 14:01:22 DEBUG : /: >Access: errc=0
2018/06/25 14:01:22 DEBUG : /: Access: mask=00
2018/06/25 14:01:22 DEBUG : /: >Access: errc=0
2018/06/25 14:01:22 DEBUG : /: Access: mask=00
2018/06/25 14:01:22 DEBUG : /: >Access: errc=0
2018/06/25 14:01:22 DEBUG : /: Statfs:
2018/06/25 14:01:22 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:1125899906842624 Bfree:1125899887748380 Bavail:1125899906842624 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
2018/06/25 14:01:22 DEBUG : /: Statfs:
2018/06/25 14:01:22 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:1125899906842624 Bfree:1125899887748380 Bavail:1125899906842624 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
2018/06/25 14:01:37 DEBUG : /.metadata_never_index: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/06/25 14:01:37 DEBUG : /.metadata_never_index: >Getattr: errc=-2
2018/06/25 14:01:37 DEBUG : /.metadata_never_index_unless_rootfs: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/06/25 14:01:37 DEBUG : /.metadata_never_index_unless_rootfs: >Getattr: errc=-2
2018/06/25 14:01:37 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/06/25 14:01:37 DEBUG : /: >Getattr: errc=0
2018/06/25 14:01:37 DEBUG : /: Access: mask=00
2018/06/25 14:01:37 DEBUG : /: >Access: errc=0
2018/06/25 14:01:41 DEBUG : /: Statfs:
2018/06/25 14:01:41 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:1125899906842624 Bfree:1125899887748380 Bavail:1125899906842624 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
^C2018/06/25 14:01:49 DEBUG : /: Fsyncdir: datasync=true, fh=0x0
2018/06/25 14:01:49 DEBUG : /: >Fsyncdir: errc=0
2018/06/25 14:01:49 DEBUG : /: Releasedir: fh=0x0
2018/06/25 14:01:49 DEBUG : /: >Releasedir: errc=0
2018/06/25 14:01:49 DEBUG : Google drive root '': Destroy:
2018/06/25 14:01:49 DEBUG : Google drive root '': >Destroy:
2018/06/25 14:01:49 DEBUG : rclone: Version "v1.42-DEV" finishing with parameters ["./rclone-darwin-10.6-amd64" "cmount" "--vfs-cache-mode" "writes" "--no-modtime" "google:" "-vv" "/Users/andrew/rclone-mnt/google"]
```

**Comment by ncw** [comment]
Thanks for testing.  It seems likely that the problem is in the OSXFUSE layer since it is in both mount and cmount.

This issue https://github.com/osxfuse/osxfuse/issues/396 seems to agree with me that the values are 32 bit and hence are wrapping.  There appears to be an extended interface which neither of the upstream libraries I'm using implement.

Here is an rclone with a work-around which clips the number of blocks to the maximum the OS can support.  This will let disks get to be 16 TB and above that the free/avail etc will show as 16 TB.

Can you give this a go and report back what `df -h` says and see if `f_bavail` looks sensible?

Thanks

https://beta.rclone.org/branch/v1.42-013-gc9749454-fix-2356-macOS-mount/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
I've merged this here

https://beta.rclone.org/v1.42-133-g174ca229/ (uploaded in 15-30 mins)

This will be in [the latest beta](https://beta.rclone.org) and 1.43!
