### ISSUE TITLE
Excessive memory usage 

### ISSUE THREAD

**Issue by danzig666** [ncw/rclone#236]
I'm trying to copy OneDrive to Amazon Cloud Drive on a low memory vps  (256MB), but the rclone process gets killed constantly after using up all available memory. 
Does rclone really needs to keep the entire directory tree in memory? Seems really unnecessary. 
Why not compare each directory, copy what needs to be copied, then discard the now unneeded file list.
Is there any way around this?

**Comment by ncw** [comment]
I haven't spend much time optimizing memory usage in rclone recently. For example the amazon cloud drive `Object`s are fatter than they need to be - making them smaller would reduce memory usage a lot.

> Does rclone really needs to keep the entire directory tree in memory?

The way the internal interfaces are implemented at the moment it does.  Not all the cloud storage systems have the concept of directory and can they can return files in any order.

You'll see if you look at the code for sync (`fs/operations.go` `syncCopyMove`)  a `FIXME` which could help if implemented.

Probably what rclone needs is a bit of time with go's memory profiler!  I should add a `--memprofile` flag so anyone can do this.

You could work around this by using `lsd` to see the top level directories, then syncing each one of these individually - that would help probably.

**Comment by ncw** [comment]
Memory usage in rclone could do with a round of optimization and checking each of the remotes doesn't use an excess of memory.

**Comment by danzig666** [comment]
I'm learning Go right now just to be able to contribute

**Comment by lcarstensen** [comment]
FWIW, I could take advantage of a --memprofile flag also right now.  I'm getting OOM kills on a 2G Linux instance trying to sync swift to swift.  ~11500 objects, ~50G of data, it gets killed after moving between two and three thousand files each time.  This sounds more like a leak to me than holding the directory tree, but having the --memprofile option would help identify that sort of thing more quickly.

**Comment by klauspost** [comment]
@lcarstensen - that does indeed sound like a leak, or excessive buffering. If I copy 154k files local->ACD, memory never gets above 300MB.

**Comment by ncw** [comment]
@lcarstensen I've added a `--memprofile` flag for you - you can find a binary with it here

http://pub.rclone.org/v1.26-15-g2646519%CE%B2/

To use it, first add `--memprofile mem.prof` to the command line of your command.

You'll need go installed to analyse it, which you do with

    go tool pprof /path/to/rclone mem.prof

The two most useful commands are `top20` and `web` - they should give you a good idea what is going on.

If you'd like me to analyse it then you'll need to send me the `mem.prof` file and tell me exactly which rclone binary you used.

**Comment by SullyTheUnusual** [comment]
I'm trying to run RClone on a RPi with 1GB RAM, and it only runs about 15 minutes before using up all the memory and crashing.  I've tried setting the `--memprofile` flag, but it's not generating a file.  Here's my command:  `rclone sync -v --ignore-existing --retries 30 --memprofile mem.prof /home/sullytheunusual/3tbHDD remote:Backups`

**Comment by ncw** [comment]
How many files are you syncing? At the moment rclone loads each file name into memory first so more files means more memory. 

Which remote are you using? They use differing amounts of memory.

**Comment by SullyTheUnusual** [comment]
Well, that explains it.  I'm trying to backup a drive with thousands of files.  Guess I'll stick with acd_cli.

**Comment by ncw** [comment]
You can sync sub directories as a workaround.

I'll l fix the memory usage eventually though!

**Comment by nodughere** [comment]
I can verify that copying 2.5 million files from Swift cluster to local is eating up 16GB of memory at the end.  That's about 6kB per object.  Will I can finish the moves with this server, it certainly would break on my laptop.

**Comment by ncw** [comment]
@nodughere 6k per object sounds way too big!

Below you'll find an rclone with a new command `memtest`

http://pub.rclone.org/v1.30-4-g12342eb%CE%B2/

This is what I get running it against a swift container with 60k files in.

```
rclone memtest swift:container
2016/06/21 16:35:05 60182 objects took 26790336 bytes, 445.2 bytes/object
2016/06/21 16:35:05 System memory changes from 7969016 to 45504760 bytes a change of 37535744 bytes
```

This loads all the info about the remote objects into memory in the same way as it does doing a sync.

Can you try that on your 2.5 million files container and report back what it says please?

If you could also try it on a local copy of all files (if available) that would be interesting too.  So

```
rclone memtest swift:container
rclone memtest /path/to/copy/of/files
```

Thanks

**Comment by kmanley** [comment]
Also an issue for me trying to run latest rclone on a WD My Cloud which has limited memory

**Comment by fredericofs** [comment]
Any news?  
rclone CPU and memory usage during 30gb sync, makes raspberry oom-killer kill some other apps (not rclone).

**Comment by ncw** [comment]
I'm currently implementing #517 which will likely fix this issue too.

**Comment by ncw** [comment]
Here is a beta for a low memory sync which I think should fix this problem.

tThere is a temporary flag `--old-sync-method` to select the old sync method.

It should work identically to current rclone, except using a lot less memory.

http://pub.rclone.org/v1.35-50-g9d88ce3-low-mem-sync%CE%B2/

It is a major re-work of the syncing internals.  All the unit tests pass, and the code is well covered.  My own smoke tests pass too.

Test with care - use --dry-run first!

I'm particularly interested in 
  * any bugs
  * memory usage differences before vs after - especially on big syncs
  * speed differences before vs after

You can run this little ditty in another window to see rclone memory usage

    while [ true ]; do ps -eo rss,args --sort rss | grep [r]clone ; sleep 0.5 ; done

**Comment by fredericofs** [comment]
In my case, it is only 1 folder (no sub-dirs) with 30gb of ~3mb files.
Should I expect some improvement too?

**Comment by ncw** [comment]
@fredericofs 
> In my case, it is only 1 folder (no sub-dirs) with 30gb of ~3mb files.
> Should I expect some improvement too?

A bit maybe!  I wouldn't have thought only 10,000 files would use much memory though...

**Comment by kmanley** [comment]
I tried running the low memory sync Beta on my WD My Cloud but now I'm back to getting "runtime: kernel page size (65536) is larger than runtime page size (4096), which was previously addressed in #426. Please can you build this low memory version the same way you built the binaries in #426?

**Comment by ncw** [comment]
@kmanley 
Here http://pub.rclone.org/v1.35-68-g5eb5e5f-low-mem-sync%CE%B2/ is a beta compiled with go 1.8 rc3 which should work on the WD cloud.

**Comment by ncw** [comment]
I have merged this to master now - see here for a beta:

http://beta.rclone.org/v1.35-74-g48cdedc/

Any feedback much appreciated

**Comment by kmanley** [comment]
Hi @ncw, thanks for your reply. Unfortunately I still get the same error

```WDMyCloud:/home/rclone/rclone-v1.35-74-g48cdedc#U03b2-linux-arm# ./rclone 
runtime: kernel page size (65536) is larger than runtime page size (4096)
```

**Comment by ncw** [comment]
@kmanley the fix for the page size isn't in the stable go compiler yet - I'm hoping it will be in time for the rclone 1.36 release.

In the mean time try this which I compiled with  `go1.8rc3`

http://pub.rclone.org/v1.35-75-g381b845%CE%B2/

**Comment by ncw** [comment]
@umaxfun please use [the latest beta](https://beta.rclone.org) - there was a memory leak in the onedrive multipart upload code, now fixed.
