### ISSUE TITLE
Stop dedupe failing with "Failed to dedupe [...] can't merge directories" on crypted drives

### ISSUE THREAD

**Issue by DurvalMenezes** [ncw/rclone#2689]
#### Output of `rclone version`

rclone v1.44
- os/arch: linux/amd64
- go version: go1.11.1

#### Describe the issue
As per https://github.com/ncw/rclone/issues/1243#issuecomment-432257111, `rclone dedupe` fails with message "Failed to dedupe [...] can't merge directories":
```
rclone -vv dedupe AAA:BBBBBBBBBBBBBBB/CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC/DDDDDDDDDDDD
2018/10/22 09:17:01 DEBUG : rclone: Version "v1.44" starting with parameters ["rclone" "-vv" "dedupe" "AAA:BBBBBBBBBBBBBBB/CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC/DDDDDDDDDDDD"]
2018/10/22 09:17:01 DEBUG : Using config file from "/EEEE/FFFFFF/.rclone.conf"
2018/10/22 09:17:04 INFO  : Encrypted drive 'AAA:BBBBBBBBBBBBBBB/CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC/DDDDDDDDDDDD': Looking for duplicates using interactive mode.
2018/10/22 09:19:06 Failed to dedupe: Encrypted drive 'AAA:BBBBBBBBBBBBBBB/CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC/DDDDDDDDDDDD': can't merge directories
```
(NB: each of the sequences of repeated uppercase letters AAA,  BBBBBBBBBBBBBBB, etc stands for a redacted remote name, or a component of the path in that remote, with the same length in characters). 

@ncw: wasn't it supposed to be a whole lot of logging between the last and the next-to-last lines above? If you need anything else please let me know.

**Comment by ncw** [comment]
This isn't working because we need crypt to support `MergeDirs`.  This should be reasonably straight forward to implement.

That also means that you can run `dedupe` on the underlying google drive and it should work, albeit with encrypted file names which might make it rather difficult to work out what is going on.

**Comment by jkuehl2** [comment]
No solution yet? How to handle this issue? Do i have to delete a 3TB+ directory and resync to fix it? I cannot sync the dir because of dupes and i cannot dedupe because of duped dirs. btw, this happened when i manually moved dirs from one folder in drive to another that already contained some of those dirs.

**Comment by ncw** [comment]
> No solution yet? How to handle this issue?

You should be able to dedupe the underlying drive.

**Comment by jkuehl2** [comment]
> 
> 
> > No solution yet? How to handle this issue?
> 
> You should be able to dedupe the underlying drive.

That seemed to to the trick, thanks.

**Comment by ncw** [comment]
Here is a beta with this implemented - please give it a go!

https://beta.rclone.org/branch/v1.46.0-112-g716bb755-fix-2895-optional-methods-beta/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.48

**Comment by tcf909** [comment]
Not to dredge up an old issue, but I still receive this error when using dedupe against Drive > Cache > Crypt config.

**Comment by ncw** [comment]
> Not to dredge up an old issue, but I still receive this error when using dedupe against Drive > Cache > Crypt config.
> 
> rclone v1.52.0
> 
> * os/arch: linux/amd64
> * go version: go1.14.3

That will be a different issue! Can you please make a [new issue on github](https://github.com/rclone/rclone/issues/new/choose) for that please!

**Comment by tcf909** [comment]
> > Not to dredge up an old issue, but I still receive this error when using dedupe against Drive > Cache > Crypt config.
> > rclone v1.52.0
> > 
> > * os/arch: linux/amd64
> > * go version: go1.14.3
> 
> That will be a different issue! Can you please make a [new issue on github](https://github.com/rclone/rclone/issues/new/choose) for that please!

Thanks Nick. As always, I appreciate the quick response. Project looks like it is doing great.

Reference New Issue: #4320
