### ISSUE TITLE
Azure Blob Store: rclone confused by folder blobs

### ISSUE THREAD

**Issue by bmc** [ncw/rclone#2806]
#### What is the problem you are having with rclone?

`rclone` sees two folders for `adventure-works` in the following Azure blob store (see image). The Azure blob stores I use are littered with these "Hot" blobs. `rclone` invariably copies the file-looking one (even though Azure says it's a "folder"), and not the folder and its contents.

<img src="https://s3.amazonaws.com/clapper-stuff/blob-store.png"/>

#### What is your rclone version (output from `rclone version`)

Tested with the following versions:

```
rclone v1.44
- os/arch: darwin/amd64
- go version: go1.11.1
```

```
rclone v1.45-011-gba8aa73a-fix-2654-azureblob-client-beta
- os/arch: darwin/amd64
- go version: go1.11.2
```

```
rclone v1.44
- os/arch: linux/amd64
- go version: go1.11.1
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Mac OS 64-bit
Ubuntu 14.04 (trusty) 64-bit

####  Which cloud storage system are you using? (eg Google Drive)

S3, Azure

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone sync azureremote:blob s3:bucket`

`rclone sync azureremote:blob .`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Note the "Duplicate directory" notices in the log.

```
2018/11/30 12:46:03 DEBUG : rclone: Version "v1.45-011-gba8aa73a-fix-2654-azureblob-client-beta" starting with parameters ["../rclone" "sync" "-vv" "airlift453:class-453" "."]
2018/11/30 12:46:03 DEBUG : Using config file from "/Users/bmc/.config/rclone/rclone.conf"
2018/11/30 12:46:03 DEBUG : pacer: Reducing sleep to 0s
2018/11/30 12:46:03 NOTICE: adventure-works: Duplicate directory found in source - ignoring
2018/11/30 12:46:03 NOTICE: airbnb/listings: Duplicate directory found in source - ignoring
2018/11/30 12:46:04 INFO  : adventure-works: Copied (new)
2018/11/30 12:46:04 INFO  : Local file system at /Users/bmc/tmp/rclone-v1.45-011-gba8aa73a-fix-2654-azureblob-client-beta-osx-amd64/tmp: Waiting for checks to finish
2018/11/30 12:46:04 INFO  : Local file system at /Users/bmc/tmp/rclone-v1.45-011-gba8aa73a-fix-2654-azureblob-client-beta-osx-amd64/tmp: Waiting for transfers to finish
2018/11/30 12:46:04 INFO  : airbnb/listings: Copied (new)
2018/11/30 12:46:04 INFO  : PartnerOrderClean.json: Copied (new)
2018/11/30 12:47:03 INFO  :
Transferred:   	  200.189M / 273.261 MBytes, 73%, 3.335 MBytes/s, ETA 21s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            3 / 4, 75%
Elapsed time:        1m0s
Transferring:
 *     _$azuretmpfolder$/cd…-oct-06-detailed.csv: 73% /273.068M, 3.406M/s, 21s

2018/11/30 12:47:25 INFO  : _$azuretmpfolder$/cd8e991f-21fd-489c-8205-b3c8fe717e64london-2018-oct-06-detailed.csv: Copied (new)
2018/11/30 12:47:25 INFO  : Waiting for deletions to finish
2018/11/30 12:47:25 INFO  :
Transferred:   	  273.261M / 273.261 MBytes, 100%, 3.349 MBytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            4 / 4, 100%
Elapsed time:     1m21.5s

2018/11/30 12:47:25 DEBUG : 5 go routines active
2018/11/30 12:47:25 DEBUG : rclone: Version "v1.45-011-gba8aa73a-fix-2654-azureblob-client-beta" finishing with parameters ["../rclone" "sync" "-vv" "airlift453:class-453" "."]
```

**Comment by bmc** [comment]
Note that there's no difference if I use a SAS URL vs. an access key.

**Comment by bmc** [comment]
We've done some digging. It turns out these file things are created by a Hadoop library, as a means to make an empty "directory" actually look like it's there (because, like S3, empty directories in Azure Blob Store don't really exist—and don't even *appear* to exist until you put something in them).

These things have a piece of metadata in them that says `hdi_isfolder` = `true`.

However, there might even be an easier solution for you: Since Azure Blob Store _allows_ there to be a file that has the same name as a directory, just handle that on a copy _to_ Azure.

Here's the output of the `rdump`. Feel free to me here or privately, if you wish (bmc@databricks.com or bmc@clapper.org). We're using `rclone` at Databricks, for data replication. We'd be willing to remunerate you for helping us get past this issue. :-)

```
$ rclone -vv --dump bodies lsf "airlift453:class-453"
2018/12/05 14:11:17 DEBUG : rclone: Version "v1.44" starting with parameters ["rclone" "-vv" "--dump" "bodies" "lsf" "airlift453:class-453"]
2018/12/05 14:11:17 DEBUG : Using config file from "/Users/bmc/.config/rclone/rclone.conf"
PartnerOrderClean.json
_$azuretmpfolder$/
adventure-works
adventure-works/
airbnb/
2018/12/05 14:11:17 DEBUG : 5 go routines active
2018/12/05 14:11:17 DEBUG : rclone: Version "v1.44" finishing with parameters ["rclone" "-vv" "--dump" "bodies" "lsf" "airlift453:class-453"]
```

**Comment by ncw** [comment]
> Here's the output of the `rdump`

Thank you..

I added the same fix as I did for s3 when it had a similar problem which is to ignore objects ending in / of zero length - can you have a go with it?

https://beta.rclone.org/branch/v1.45-023-g1e602790-fix-2806-azureblob-directory-beta/ (uploaded in 15-30 mins)

If that doesn't work can you do the `lsf` command above with that beta - it will print a lot more stuff. If you are worried about it containing confidential stuff then feel free to edit it or you could email it to me at nick@craig-wood.com (put a link to this issue in too - I get a lot of email!).

**Comment by bmc** [comment]
There's nothing confidential in the blob store. (We use it for Apache Spark training; it's just test data.)

The attempt to do a `sync` from the Azure blob store to the local disk still gagged on the duplication. Here's the current state of the blob store, at the top level. There's one case (at that level) where a folder and a (placeholder) file have the same name.

<img src="https://s3.amazonaws.com/clapper-stuff/blob-store-2.png"/>

Here's what Azure thinks the `adventure-works` file looks like:

<img src="https://s3.amazonaws.com/clapper-stuff/blob-store-3.png"/>

Here's the `rclone ls` and `lsd` output for that blob store:

```
$ ../rclone ls --max-depth 1 airlift:class-453
   201870 PartnerOrderClean.json
        0 adventure-works
$ ../rclone lsd --max-depth 1 airlift:class-453
          -1 2018-12-05 17:45:36        -1 _$azuretmpfolder$
          -1 2018-12-05 17:45:36        -1 adventure-works
          -1 2018-12-05 17:45:36        -1 airbnb
```

Here's what `sync` does, to an empty local directory. (It skips the `adventure-works` folder, favoring only the `adventure-works` placeholder file.

```
$ ../rclone sync -vv --exclude '*azuretmpfolder*' airlift:class-453 .
2018/12/05 17:48:27 DEBUG : rclone: Version "v1.45-023-g1e602790-fix-2806-azureblob-directory-beta" starting with parameters ["../rclone" "sync" "-vv" "--exclude" "*azuretmpfolder*" "airlift:class-453" "."]
2018/12/05 17:48:27 DEBUG : Using config file from "/Users/bmc/.config/rclone/rclone.conf"
2018/12/05 17:48:27 DEBUG : pacer: Reducing sleep to 0s
2018/12/05 17:48:27 NOTICE: adventure-works: Duplicate directory found in source - ignoring
2018/12/05 17:48:27 NOTICE: airbnb/listings: Duplicate directory found in source - ignoring
2018/12/05 17:48:27 INFO  : adventure-works: Copied (new)
2018/12/05 17:48:27 INFO  : airbnb/listings: Copied (new)
2018/12/05 17:48:27 INFO  : PartnerOrderClean.json: Copied (new)
2018/12/05 17:48:28 INFO  : Local file system at /Users/bmc/Downloads/rclone-v1.45-023-g1e602790-fix-2806-azureblob-directory-beta-osx-amd64/tmp: Waiting for checks to finish
2018/12/05 17:48:28 INFO  : Local file system at /Users/bmc/Downloads/rclone-v1.45-023-g1e602790-fix-2806-azureblob-directory-beta-osx-amd64/tmp: Waiting for transfers to finish
2018/12/05 17:49:27 INFO  :
Transferred:   	  179.189M / 273.261 MBytes, 66%, 2.986 MBytes/s, ETA 31s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            3 / 4, 75%
Elapsed time:        1m0s
Transferring:
 *     _$azuretmpfolder$/cd…-oct-06-detailed.csv: 65% /273.068M, 3.075M/s, 30s

2018/12/05 17:49:58 INFO  : _$azuretmpfolder$/cd8e991f-21fd-489c-8205-b3c8fe717e64london-2018-oct-06-detailed.csv: Copied (new)
2018/12/05 17:49:58 INFO  : Waiting for deletions to finish
2018/12/05 17:49:58 INFO  :
Transferred:   	  273.261M / 273.261 MBytes, 100%, 2.997 MBytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            4 / 4, 100%
Elapsed time:     1m31.1s

2018/12/05 17:49:58 DEBUG : 5 go routines active
2018/12/05 17:49:58 DEBUG : rclone: Version "v1.45-023-g1e602790-fix-2806-azureblob-directory-beta" finishing with parameters ["../rclone" "sync" "-vv" "--exclude" "*azuretmpfolder*" "airlift:class-453" "."]
```

(Clearly, I don't have the `--exclude` pattern quite right, but that's not relevant to this issue.)

The two **NOTICE** lines correspond to cases where the folder has a corresponding placeholder file.

Here's the same log info as before, with the new beta version of `rclone`:
```
$ ../rclone -vv --dump bodies lsf airlift:class-453
2018/12/05 17:47:26 DEBUG : rclone: Version "v1.45-023-g1e602790-fix-2806-azureblob-directory-beta" starting with parameters ["../rclone" "-vv" "--dump" "bodies" "lsf" "airlift:class-453"]
2018/12/05 17:47:26 DEBUG : Using config file from "/Users/bmc/.config/rclone/rclone.conf"
2018/12/05 17:47:26 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/12/05 17:47:26 DEBUG : HTTP REQUEST (req 0xc000439600)
2018/12/05 17:47:26 DEBUG : GET /class-453?comp=list&delimiter=%2F&include=metadata&maxresults=5000&restype=container&se=2019-12-01T01%3A50%3A25Z&sig=wHEU3uOYLkHjb1pjok8TpfrkcfPxZbgcKAmlidXxTAc%3D&sp=rl&spr=https&srt=sco&ss=bfqt&st=2018-11-30T17%3A50%3A25Z&sv=2017-11-09&timeout=31536001 HTTP/1.1
Host: airlift453.blob.core.windows.net
User-Agent: rclone/v1.45-023-g1e602790-fix-2806-azureblob-directory-beta
X-Ms-Client-Request-Id: 0f513545-9714-40e9-4e7c-0d760f46237e
X-Ms-Version: 2018-03-28
Accept-Encoding: gzip

2018/12/05 17:47:26 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/12/05 17:47:26 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/12/05 17:47:26 DEBUG : HTTP RESPONSE (req 0xc000439600)
2018/12/05 17:47:26 DEBUG : HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Wed, 05 Dec 2018 22:47:26 GMT
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
X-Ms-Request-Id: 0ea1c08f-001e-0021-2bec-8c51fb000000
X-Ms-Version: 2018-03-28

76e
﻿<?xml version="1.0" encoding="utf-8"?><EnumerationResults ServiceEndpoint="https://airlift453.blob.core.windows.net/" ContainerName="class-453"><MaxResults>5000</MaxResults><Delimiter>/</Delimiter><Blobs><Blob><Name>PartnerOrderClean.json</Name><Properties><Creation-Time>Thu, 25 Oct 2018 04:10:54 GMT</Creation-Time><Last-Modified>Thu, 25 Oct 2018 09:54:25 GMT</Last-Modified><Etag>0x8D63A5FD8F4C980</Etag><Content-Length>201870</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5 /><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Hot</AccessTier><AccessTierInferred>true</AccessTierInferred><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>true</ServerEncrypted></Properties><Metadata><hdi_permission>{"owner":"root","group":"supergroup","permissions":"rw-r--r--"}</hdi_permission></Metadata></Blob><BlobPrefix><Name>_$azuretmpfolder$/</Name></BlobPrefix><Blob><Name>adventure-works</Name><Properties><Creation-Time>Thu, 25 Oct 2018 04:16:12 GMT</Creation-Time><Last-Modified>Thu, 25 Oct 2018 04:16:12 GMT</Last-Modified><Etag>0x8D63A30991AC26F</Etag><Content-Length>0</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5 /><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Hot</AccessTier><AccessTierInferred>true</AccessTierInferred><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>true</ServerEncrypted></Properties><Metadata><hdi_isfolder>true</hdi_isfolder><hdi_permission>{"owner":"root","group":"supergroup","permissions":"rwxr-xr-x"}</hdi_permission></Metadata></Blob><BlobPrefix><Name>adventure-works/</Name></BlobPrefix><BlobPrefix><Name>airbnb/</Name></BlobPrefix></Blobs><NextMarker /></EnumerationResults>
0

2018/12/05 17:47:26 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/12/05 17:47:26 DEBUG : pacer: Reducing sleep to 0s
PartnerOrderClean.json
_$azuretmpfolder$/
adventure-works
adventure-works/
airbnb/
2018/12/05 17:47:26 DEBUG : 5 go routines active
2018/12/05 17:47:26 DEBUG : rclone: Version "v1.45-023-g1e602790-fix-2806-azureblob-directory-beta" finishing with parameters ["../rclone" "-vv" "--dump" "bodies" "lsf" "airlift:class-453"]
```

**Comment by bmc** [comment]
I've set up an Azure blob store that has this exact kind of situation. I've created a full-access SAS URL for it. I'm emailing the info to nick@craig-wood.com, in case it helps you debug. Feel free to use that blob store. I can easily create this scenario (in our Spark-based product) in seconds, if you need additional test samples.

**Comment by ncw** [comment]
> I've set up an Azure blob store that has this exact kind of situation. I've created a full-access SAS URL for it. I'm emailing the info to [nick@craig-wood.com](mailto:nick@craig-wood.com), in case it helps you debug. Feel free to use that blob store. I can easily create this scenario (in our Spark-based product) in seconds, if you need additional test samples.

Thank you that was really helpful.

I can see the problem quite clearly now.   On s3 the convention is directory markers have  `/` on the end so you have a 0 length blob called `path/to/dir/`.  These directory markers don't have the trailing slash (hence the fix above didn't work) but they do have that extra `hdi_isfolder` metadata which a bit of reading confirms is a defacto standard in azure.

I've adjusted rclone to take account of that - can you have a go with this please?

https://beta.rclone.org/branch/v1.45-023-gb86ebbe0-fix-2806-azureblob-directory-beta/ (uploaded in 15-30 mins)

Hopefully that will work - it does on the test bucket anyway!

PS nice use of SAS URL.  Did you know that with a SAS URL you can use rclone without a config file...

rclone lsf -R --azureblob-sas-url "https://..." :azureblob:bmc

**Comment by bmc** [comment]
Works perfectly! Thanks!

I'll use this downloaded beta for now, until the fix is released officially.

**Comment by ncw** [comment]
Thanks for testing :-)

I've merged this to master and it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins.  It will be released in v1.46

**Comment by robertoayusob** [comment]
Hi @ncw I have the same problem, downloaded the patched version but still the same problem:

root@ubuntu0:~# rclone -vv sync azure:common/tmp ./probando/
2018/12/27 11:43:06 DEBUG : rclone: Version "v1.45-023-gb86ebbe0-fix-2806-azureblob-directory-beta" starting with parameters ["rclone" "-vv" "sync" "azure:common/tmp" "./probando/"]
2018/12/27 11:43:06 NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults
2018/12/27 11:43:07 DEBUG : pacer: Reducing sleep to 0s
2018/12/27 11:43:07 INFO  : Local file system at /root/probando: Waiting for checks to finish
2018/12/27 11:43:07 INFO  : Local file system at /root/probando: Waiting for transfers to finish
2018/12/27 11:43:07 INFO  : tmp: Copied (new)
2018/12/27 11:43:07 INFO  : Waiting for deletions to finish
2018/12/27 11:43:07 INFO  : 
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            1 / 1, 100%
Elapsed time:       600ms


While /tmp is a folder on azure with several subfolders and files, I am not using a SAS URL

**Comment by robertoayusob** [comment]
Yes, the problem comes when the blob folder is at the first point, it detects as a file and do not go into it, I am not a developer but, after adding some debug traces, it looks that rclone does not go into the part of code you patched when this blob folder is wrongly detected as a file at the first point. A workarround has been using always the root source and some include filters.

Anyway this is the dump you request, may be you can solve the problem (little things removed):
```
root@ubuntu0:~/rclone# ./rclone -vv --dump bodies lsf azure:common
2019/01/03 07:15:05 DEBUG : rclone: Version "v1.45-DEV" starting with parameters ["./rclone" "-vv" "--dump" "bodies" "lsf" "azure:common"]
2019/01/03 07:15:05 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2019/01/03 07:15:05 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/01/03 07:15:05 DEBUG : HTTP REQUEST (req 0xc0002fd700)
2019/01/03 07:15:05 DEBUG : GET /common?comp=list&delimiter=%2F&include=metadata&maxresults=5000&restype=container&timeout=31536001 HTTP/1.1
Host: vecibigdatastorage.blob.core.windows.net
User-Agent: rclone/v1.45-DEV
Authorization: XXXX
X-Ms-Client-Request-Id: 101f54d8-7f1c-4126-7db9-f3cc48209dd3
X-Ms-Version: 2018-03-28
x-ms-date: Thu, 03 Jan 2019 06:15:05 GMT
Accept-Encoding: gzip

2019/01/03 07:15:05 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/01/03 07:15:05 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/01/03 07:15:05 DEBUG : HTTP RESPONSE (req 0xc0002fd700)
2019/01/03 07:15:05 DEBUG : HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Thu, 03 Jan 2019 06:15:05 GMT
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
X-Ms-Request-Id: 58759ab9-b01e-0087-3d2b-a34c12000000
X-Ms-Version: 2018-03-28

3a9c
<?xml version="1.0" encoding="utf-8"?><EnumerationResults........></EnumerationResults>
0

2019/01/03 07:15:05 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/01/03 07:15:05 DEBUG : pacer: Reducing sleep to 0s
HdiSamples/
_$azuretmpfolder$/
ams/
amshbase/
app-logs/
apps/
atshistory/
custom-scriptaction-logs/
data/
data_azure_orig/
dataimport/
example/
hbase/
hdp/
hive/
mapred/
mapreducestaging/
mr-history/
testrclone1/
tmp/
user/
2019/01/03 07:15:05 DEBUG : 4 go routines active
2019/01/03 07:15:05 DEBUG : rclone: Version "v1.45-DEV" finishing with parameters ["./rclone" "-vv" "--dump" "bodies" "lsf" "azure:common"]
```
and
```
root@ubuntu0:~/rclone# ./rclone -vv --dump bodies lsf azure:common/tmp
2019/01/03 07:18:32 DEBUG : rclone: Version "v1.45-DEV" starting with parameters ["./rclone" "-vv" "--dump" "bodies" "lsf" "azure:common/tmp"]
2019/01/03 07:18:32 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2019/01/03 07:18:32 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/01/03 07:18:32 DEBUG : HTTP REQUEST (req 0xc0002ef700)
2019/01/03 07:18:32 DEBUG : HEAD /common/tmp?timeout=31536001 HTTP/1.1
Host: vecibigdatastorage.blob.core.windows.net
User-Agent: rclone/v1.45-DEV
Authorization: XXXX
X-Ms-Client-Request-Id: 35593f26-7c73-4d8c-4947-67892c0b6d82
X-Ms-Version: 2018-03-28
x-ms-date: Thu, 03 Jan 2019 06:18:32 GMT

2019/01/03 07:18:32 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/01/03 07:18:33 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/01/03 07:18:33 DEBUG : HTTP RESPONSE (req 0xc0002ef700)
2019/01/03 07:18:33 DEBUG : HTTP/1.1 200 OK
Accept-Ranges: bytes
Date: Thu, 03 Jan 2019 06:18:32 GMT
Etag: "0x8D65B887F16C166"
Last-Modified: Thu, 06 Dec 2018 14:38:32 GMT
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
X-Ms-Blob-Type: BlockBlob
X-Ms-Creation-Time: Fri, 23 Nov 2018 06:49:03 GMT
X-Ms-Lease-State: available
X-Ms-Lease-Status: unlocked
X-Ms-Meta-Hdi_isfolder: true
X-Ms-Meta-Hdi_permission: {"owner":"hdfs","group":"supergroup","permissions":"rwxrwxrwx"}
X-Ms-Request-Id: 056adef3-401e-0135-6c2c-a34d6e000000
X-Ms-Server-Encrypted: true
X-Ms-Version: 2018-03-28
Content-Length: 0

2019/01/03 07:18:33 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/01/03 07:18:33 DEBUG : pacer: Reducing sleep to 0s
2019/01/03 07:18:33 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/01/03 07:18:33 DEBUG : HTTP REQUEST (req 0xc000112800)
2019/01/03 07:18:33 DEBUG : HEAD /common/tmp?timeout=31536001 HTTP/1.1
Host: vecibigdatastorage.blob.core.windows.net
User-Agent: rclone/v1.45-DEV
Authorization: XXXX
X-Ms-Client-Request-Id: 809c3522-bc1d-420d-5104-1a7a64769763
X-Ms-Version: 2018-03-28
x-ms-date: Thu, 03 Jan 2019 06:18:33 GMT

2019/01/03 07:18:33 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/01/03 07:18:33 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/01/03 07:18:33 DEBUG : HTTP RESPONSE (req 0xc000112800)
2019/01/03 07:18:33 DEBUG : HTTP/1.1 200 OK
Accept-Ranges: bytes
Date: Thu, 03 Jan 2019 06:18:32 GMT
Etag: "0x8D65B887F16C166"
Last-Modified: Thu, 06 Dec 2018 14:38:32 GMT
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
X-Ms-Blob-Type: BlockBlob
X-Ms-Creation-Time: Fri, 23 Nov 2018 06:49:03 GMT
X-Ms-Lease-State: available
X-Ms-Lease-Status: unlocked
X-Ms-Meta-Hdi_isfolder: true
X-Ms-Meta-Hdi_permission: {"owner":"hdfs","group":"supergroup","permissions":"rwxrwxrwx"}
X-Ms-Request-Id: 056adf12-401e-0135-032c-a34d6e000000
X-Ms-Server-Encrypted: true
X-Ms-Version: 2018-03-28
Content-Length: 0

2019/01/03 07:18:33 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
tmp
2019/01/03 07:18:33 DEBUG : 4 go routines active
2019/01/03 07:18:33 DEBUG : rclone: Version "v1.45-DEV" finishing with parameters ["./rclone" "-vv" "--dump" "bodies" "lsf" "azure:common/tmp"]
```

**Comment by ncw** [comment]
@robertoayusob thanks for the dumps.  I can see from those that a similar fix should work for this case too.

https://beta.rclone.org/branch/v1.45-057-g75613e96-fix-2806-azureblob-dir-marker-beta/ (uploaded in 15-30 mins)

Can you give it a go?

**Comment by robertoayusob** [comment]
Of Course but the link returns a 404- Can you give me the github src version link? I can checkout and compile miself.

Thkns

**Comment by robertoayusob** [comment]
got the same problem:

```
root@ubuntu0:~/rclone# ./rclone -vv --dump bodies lsf azure:common/tmp
2019/01/04 14:01:26 DEBUG : rclone: Version "v1.45-DEV" starting with parameters ["./rclone" "-vv" "--dump" "bodies" "lsf" "azure:common/tmp"]
2019/01/04 14:01:26 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2019/01/04 14:01:26 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/01/04 14:01:26 DEBUG : HTTP REQUEST (req 0xc0002f1700)
2019/01/04 14:01:26 DEBUG : HEAD /common/tmp?timeout=31536001 HTTP/1.1
Host: vecibigdatastorage.blob.core.windows.net
User-Agent: rclone/v1.45-DEV
Authorization: XXXX
X-Ms-Client-Request-Id: d0aebfcd-ee5c-4d5c-6b5e-81de7734afd9
X-Ms-Version: 2018-03-28
x-ms-date: Fri, 04 Jan 2019 13:01:26 GMT

2019/01/04 14:01:26 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/01/04 14:01:27 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/01/04 14:01:27 DEBUG : HTTP RESPONSE (req 0xc0002f1700)
2019/01/04 14:01:27 DEBUG : HTTP/1.1 200 OK
Accept-Ranges: bytes
Date: Fri, 04 Jan 2019 13:01:26 GMT
Etag: "0x8D65B887F16C166"
Last-Modified: Thu, 06 Dec 2018 14:38:32 GMT
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
X-Ms-Blob-Type: BlockBlob
X-Ms-Creation-Time: Fri, 23 Nov 2018 06:49:03 GMT
X-Ms-Lease-State: available
X-Ms-Lease-Status: unlocked
X-Ms-Meta-Hdi_isfolder: true
X-Ms-Meta-Hdi_permission: {"owner":"hdfs","group":"supergroup","permissions":"rwxrwxrwx"}
X-Ms-Request-Id: bd1237c0-d01e-0075-432d-a4b45b000000
X-Ms-Server-Encrypted: true
X-Ms-Version: 2018-03-28
Content-Length: 0

2019/01/04 14:01:27 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/01/04 14:01:27 DEBUG : pacer: Reducing sleep to 0s
2019/01/04 14:01:27 Failed to create file system for "azure:common/tmp": is a not a regular file
```

**Comment by ncw** [comment]
Doh, that was a silly mistake!  Try this

https://beta.rclone.org/branch/v1.45-057-g92e0ba81-fix-2806-azureblob-dir-marker-beta/ (uploaded in 15-30 mins)

**Comment by robertoayusob** [comment]
Great job, I built it from source and it works perfect I got the same result as using the filter workarround:
Before:
`./rclone sync -vv --include '/tmp/**' azure:common ./probando_confiltro/`
Now:
`./rclone sync -vv azure:common/tmp/ ./probando_sinfiltro/tmp/`

Great job @ncw

**Comment by ncw** [comment]
> Great job, I built it from source and it works perfect I got the same result as using the filter workarround:
> Before:
> `./rclone sync -vv --include '/tmp/**' azure:common ./probando_confiltro/`
> Now:
> `./rclone sync -vv azure:common/tmp/ ./probando_sinfiltro/tmp/`
> 
> Great job @ncw

Thank you for testing :-)

I've merged that to [the latest beta](https://beta.rclone.org) now (it will be there in 15-30 mins) and this will be released in v1.46 on 7th Feb.
