### ISSUE TITLE
Doing my backup I see repeating Error 409 Conflict. What does this error mean and how could I fix it?

### ISSUE THREAD

**Issue by bunset** [ncw/rclone#289]
2016/01/09 03:00:13 15 boda laura y oscar/foto/1/DCIM/100EOS5D/IMG_2158.CR2: Received error: HTTP code 409: "409 Conflict", reponse body: {"logref":"b8a1c898-b674-11e5-94a1-25dbf54c992b","message":"Node with the name img_2158.cr2 already exists under parentId ErQpIn7aQJyboAPthMpXow conflicting NodeId: PipzSt9OQECDw6-CmJ-c-Q","code":"NAME_ALREADY_EXISTS","info":{"nodeId":"PipzSt9OQECDw6-CmJ-c-Q"}}
 - retrying 4/10

Thanks!
David

**Comment by ncw** [comment]
Have you got a file called `MG_2158.CR2` and another called `img_2158.cr2` would be the first thing to check?  Amazon cloud drive can't have files which differ only in case.

If it does that every time you sync then that is probably the explanation.  If not then retrying the sync will probably clear it up.

**Comment by bunset** [comment]
Hello Nick, thank you for responding my question.

I retry this same backup today to see if I pass errors but I have no good news to tell you. These are the errors.
Have you any idea for me?
Best regards,
David.

2016/01/12 00:17:23 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"78455be4-b8b9-11e5-a9e1-7b3d3af0708c","message":"Next token is expired"}
2016/01/12 00:17:54 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 1
Checks:                 0
Transferred:            0
Elapsed time:     13m1.8s

2016/01/12 00:18:05 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"9174f55f-b8b9-11e5-89f9-9fa63cc188bd","message":"Next token is expired"}
2016/01/12 00:18:39 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"a5baeeea-b8b9-11e5-8a5c-1dc936022f78","message":"Next token is expired"}
2016/01/12 00:18:54 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 3
Checks:                 0
Transferred:            0
Elapsed time:     14m1.8s

2016/01/12 00:19:13 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"b9c60162-b8b9-11e5-a4b6-1dab780678ad","message":"Next token is expired"}
2016/01/12 00:19:40 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"ca0abd2f-b8b9-11e5-af9a-a35439bbe5ef","message":"Next token is expired"}
2016/01/12 00:19:54 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 5
Checks:                 0
Transferred:            0
Elapsed time:     15m1.8s

2016/01/12 00:20:24 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"e472fdf6-b8b9-11e5-b206-c5271ed18146","message":"Next token is expired"}
2016/01/12 00:20:54 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 6
Checks:                 0
Transferred:            0
Elapsed time:     16m1.8s

2016/01/12 00:20:58 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"f86e32c7-b8b9-11e5-9e59-aff0ed81ea31","message":"Next token is expired"}

**Comment by bunset** [comment]
And this continues with this:

2016/01/12 00:24:15 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"6e1a192f-b8ba-11e5-b690-2fe169be019f","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"722d30ca-b8ba-11e5-b71b-c9f7a2b1755b","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Error reading fotos y videos personales/20150828/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"722d30ca-b8ba-11e5-b71b-c9f7a2b1755b","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"72391714-b8ba-11e5-9baa-bf30e079a361","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Error reading fotos y videos personales/20150803/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"72391714-b8ba-11e5-9baa-bf30e079a361","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"7243ec7e-b8ba-11e5-8445-1b2f4ae2e53e","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Error reading fotos y videos personales/android note 2/DCIM/Camera/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"7243ec7e-b8ba-11e5-8445-1b2f4ae2e53e","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Error reading fotos y videos personales/android note 2/DCIM/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"7243ec7e-b8ba-11e5-8445-1b2f4ae2e53e","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Error reading fotos y videos personales/android note 2/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"7243ec7e-b8ba-11e5-8445-1b2f4ae2e53e","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"724af121-b8ba-11e5-995b-c189821f5878","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Error reading fotos y videos personales/20151127/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"724af121-b8ba-11e5-995b-c189821f5878","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"725467e6-b8ba-11e5-8166-a18906a156dc","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Error reading fotos y videos personales/20151222/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"725467e6-b8ba-11e5-8166-a18906a156dc","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"72611157-b8ba-11e5-a8c9-e948bfd4d12f","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Error reading fotos y videos personales/20151210/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"72611157-b8ba-11e5-a8c9-e948bfd4d12f","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"7261ae03-b8ba-11e5-8d80-8f63cdfc2fc5","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Error reading fotos y videos personales/20151122/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"7261ae03-b8ba-11e5-8d80-8f63cdfc2fc5","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"7263a9bc-b8ba-11e5-af9a-a35439bbe5ef","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Error reading fotos y videos personales/20151026/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"7263a9bc-b8ba-11e5-af9a-a35439bbe5ef","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"72668f89-b8ba-11e5-8c22-03e2f37f8936","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Error reading fotos y videos personales/20151202/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"72668f89-b8ba-11e5-8c22-03e2f37f8936","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"725d199f-b8ba-11e5-8fc9-336f8529d06d","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Error reading fotos y videos personales/20151206/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"725d199f-b8ba-11e5-8fc9-336f8529d06d","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"726fde54-b8ba-11e5-8b33-614e3613c0e9","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Error reading fotos y videos personales/20151224/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"726fde54-b8ba-11e5-8b33-614e3613c0e9","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"7271dad7-b8ba-11e5-a065-13a227994cb3","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Error reading fotos y videos personales/20151225/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"7271dad7-b8ba-11e5-a065-13a227994cb3","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"7275ab5a-b8ba-11e5-9794-07a8a8d1b2ba","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Error reading fotos y videos personales/20151113/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"7275ab5a-b8ba-11e5-9794-07a8a8d1b2ba","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"72784336-b8ba-11e5-bad5-ad2bf291595d","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Error reading fotos y videos personales/copia note2 julio 2014/DCIM/Camera/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"72784336-b8ba-11e5-bad5-ad2bf291595d","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"727de82e-b8ba-11e5-89f9-9fa63cc188bd","message":"Next token is expired"}
2016/01/12 00:24:22 Amazon cloud drive root '9-1': Error reading fotos y videos personales/20160109/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"727de82e-b8ba-11e5-89f9-9fa63cc188bd","message":"Next token is expired"}
2016/01/12 00:24:23 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"72875e3d-b8ba-11e5-8e26-8333432c69ae","message":"Next token is expired"}
2016/01/12 00:24:23 Amazon cloud drive root '9-1': Error reading fotos y videos personales/note2 wassap 12nov2015/WhatsApp Images/Sent/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"72875e3d-b8ba-11e5-8e26-8333432c69ae","message":"Next token is expired"}
2016/01/12 00:24:23 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"728fe9be-b8ba-11e5-92f4-55012bead4b9","message":"Next token is expired"}
2016/01/12 00:24:23 Amazon cloud drive root '9-1': Error reading fotos y videos personales/copia note2 julio 2014/ACRCallsBackup/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"728fe9be-b8ba-11e5-92f4-55012bead4b9","message":"Next token is expired"}
2016/01/12 00:24:23 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"729085a2-b8ba-11e5-95ad-476432104ce0","message":"Next token is expired"}
2016/01/12 00:24:23 Amazon cloud drive root '9-1': Error reading fotos y videos personales/20151102/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"729085a2-b8ba-11e5-95ad-476432104ce0","message":"Next token is expired"}
2016/01/12 00:24:23 Amazon cloud drive root '9-1': Couldn't list files: HTTP code 400: "400 Bad Request", reponse body: {"logref":"729715da-b8ba-11e5-b7ed-73cd3a14c1ba","message":"Next token is expired"}
2016/01/12 00:24:23 Amazon cloud drive root '9-1': Error reading fotos y videos personales/note2 wassap 12nov2015/WhatsApp Images/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"729715da-b8ba-11e5-b7ed-73cd3a14c1ba","message":"Next token is expired"}
2016/01/12 00:24:23 Amazon cloud drive root '9-1': Error reading fotos y videos personales/note2 wassap 12nov2015/:HTTP code 400: "400 Bad Request", reponse body: {"logref":"729715da-b8ba-11e5-b7ed-73cd3a14c1ba","message":"Next token is expired"}

**Comment by ncw** [comment]
I haven't see `Next token is expired

**Comment by klauspost** [comment]
>Does the listing take a really long time?

Well, it is less than 13 minutes. I guess it is because of some server restarts/reconfiguration going on at Amazon.

The failure is in `func (s *NodesService) listNodes`, but it doesn't do anything else than reading nodes. Concurrent reads are limited by the pacer, so we don't do limit the client in any fashion.

Are you by any chance running multiple simultaneous uploads?

I don't know if writes from another client will invalidate the tokens. Depends on Amazon.

**Comment by bunset** [comment]
Fortunately, the error "next token is expired" was only that day and today is not present. Less bad.

Responding to your question Nick. Yes, I have many jpg images with same file name, but in different folders. I haven't two images with same file name in same folder.

Let me give you some more extra information. I uploaded the first backup of this usb drive (1.5TB), using the official amazon desktop application, and now I am trying to use rclone to uploading just the new files. At the moment there I haven't added new files to the usb drive, so rclone should check all and tell me, there isn't nothing to copy.

Could you fix rclone to admit having same filename in different folders on ACD or do you think Amazon doesn't admit it?. If you think last option, it extrange for me that I was able to upload the entire usb using official acd desktop app.

Let's see... Kind regards and thank you for your interest in this issue
David

**Comment by ncw** [comment]
>  same filename in different folders on ACD

This shouldn't be a problem.

I think the problem might just have been temporary - does the sync work properly now?

**Comment by Wowfunhappy** [comment]
Sounds to me like https://github.com/ncw/rclone/issues/263 I'm guessing the directory you're uploading contains a lot of files?

Amazon Cloud Drive has been finicky for the past month or so, and it seems to be mostly Amazon's fault. The sync should eventually work; it depends on the day.

**Comment by bunset** [comment]
No, it continues giving error in same point. I have tried rclone copy for the full hard disk drive another 4 days more and always gives me the same errors with it reaches this folder:
- boda laura y oscar/foto/1/DCIM/100EOS5D/

To discard problems over this folder, I have tried rclone copy for this folder only and it worked well without errors.

**Comment by bunset** [comment]
Tested again just now and continues giving same error.

lines of error here:
http://pastebin.com/b8bbDccd

It could be any database used by rclone or any configuration file used for rclone to annotate what things to do in this backup, corrupted or broken?. If yes, is there any way to clean or recreate this cache, db or config file in rclone?.

**Comment by ncw** [comment]
@bunset thank you that log is very useful.

I can see the "Next token is expired" messages.  It is clear to me that these are the cause of the "409 Conflict" messages - rclone didn't read part of the directory listing, so missed out some files.

It would be fairly easy to change the recursion strategy for listing from depth first into width first - that should fix the token expired messages hopefully.

Also I'm concerned that the error in the listing didn't seem to get passed up to the master sync command - it really should have done.

Also rclone spends ages retrying those 409 Conflicts for no gain.

**Comment by avgex** [comment]
I'm also getting this 409 Conflict (NAME_ALREADY_EXISTS) error. Trying to copy 250GB folder with photos. My camera rolled over its file name counter several times so there a duplicities but never in the same folder. Below is a link to verbose logs and a list of all photos I back up. Each time I run rclone the error appears on different directory and file. I still need to upload most of the photos but the copy get so slow with the 409 error and retries that it would be impossible to finish in reasonable time. I run rclone v1.26 on Synology NAS. First time I ran rclone I managed to copy 100GB of photos without any error. Then we had power outage and since then I encounter this error.

logs and file list of local photo directory
https://www.dropbox.com/sh/8rk42habdvtaf8h/AAC6xdXArxZAtQNrWBhYJ6JCa?dl=0

**Comment by ncw** [comment]
@avgex Thanks for that - very helpful.

I can see the same "Next token is expired" followed later by the "409 Conflict" errors, so this looks like the same problem.

I note also that your file system appears to be in latin1 instead of UTF-8.  This may mean that some of the names with accents look a bit odd in Amazon's web interface ([see the local docs](http://rclone.org/local/)).  You might want to run `convmv` on the filesystem to make it utf-8 which would be the modern thing to do. (I made myself a ticket to write this up #300)

**Comment by bunset** [comment]
Hi Nick. Thank you for reviewing the errors. 
Let me know if there is anything else I can help you until you can fix it, for example if you need remote connection to my desktop computer to see these errors or debugging them while they are happening. Just tell me.

Thanks and Kind regards!
David

**Comment by bunset** [comment]
Another log of another try just now. Same error after doing the backup very well along hours. It comes into a loop over same error. 
https://www.dropbox.com/s/thn9wiykfcoyqmd/logrclone.txt?dl=0

**Comment by ncw** [comment]
I'm working on a fix - I'll put a link to a beta release in a day or two.

**Comment by bunset** [comment]
Thank you Nick!

**Comment by ncw** [comment]
I've made a beta for you to try: http://pub.rclone.org/v1.26-34-gde3cf5e%CE%B2/

Any feedback much appreciated.

**Comment by avgex** [comment]
tried twice the beta, it got stuck each time
https://www.dropbox.com/sh/8rk42habdvtaf8h/AAC36oI8RTeZtB7pG6CFGM79a/v1.26-34-gde3cf5e%C3%9F?dl=0

**Comment by bunset** [comment]
Thank you Nick, I am testing it, running my backup, I tell you soon, how is it going!

**Comment by bunset** [comment]
Hi Nick, after 53 min. tried I had to kill the process because there was not progression on backup. It is not working well.
Kind regards!
David

Log:
MacBook-Pro-13:bin David$ cat prueba.sh 
#!/bin/sh
# si se conecta el 9-1 usb
#if [ -d  /Volumes/9-1\ 3TB ]
#then
	#si otro proceso rclone no está ejecutandose
	#if pgrep rclone; 
		#then
	    	#/usr/bin/osascript -e 'display notification "Prueba.sh" with title "Otro proceso rclone está todavía ejecutandose"';
			#else
		    #/usr/bin/osascript -e 'display notification "Prueba.sh" with title "9-1 conectado - Haciendo backup del 9-1 en acd"'			
			#echo "Comenzando rclone del 9-1 en acd" >> /Users/David/bin/cronlog.log;
			#echo "/Users/David/bin/rclone --log-file=/Users/David/bin/cronlog.log copy /Volumes/9-1\ 3TB/9-1/ remote:9-1" >> /Users/David/bin/cronlog.log;
			#/Users/David/bin/rclone --log-file=/Users/David/bin/cronlog.log copy /Volumes/9-1\ 3TB/9-1/ remote:9-1
	#fi
	#fi


	# rclone -v copy /Volumes/9-1\ 3TB/9-1/trabajo\ fotos\ boda\ laura\ y\ oscar/ remote:9-1/"trabajo fotos boda laura y oscar"
	
	

MacBook-Pro-13:bin David$ 
MacBook-Pro-13:bin David$ 
MacBook-Pro-13:bin David$ 
MacBook-Pro-13:bin David$ 
MacBook-Pro-13:bin David$ 

MacBook-Pro-13:bin David$ 
MacBook-Pro-13:bin David$ 

MacBook-Pro-13:bin David$ 
MacBook-Pro-13:bin David$ 

MacBook-Pro-13:bin David$ 
MacBook-Pro-13:bin David$ 
MacBook-Pro-13:bin David$ /Users/David/bin/rclone -v copy /Volumes/9-1\ 3TB/9-1/ remote:9-1
2016/01/21 00:13:45 Amazon cloud drive root '9-1': Modify window not supported
2016/01/21 00:13:45 Amazon cloud drive root '9-1': Building file list
2016/01/21 00:13:45 Amazon cloud drive root '9-1': Reading ""
2016/01/21 00:13:45 Amazon cloud drive root '9-1': Finished reading ""
2016/01/21 00:13:45 Amazon cloud drive root '9-1': Reading "16 boda elena&alex 13-jun-2015/"
2016/01/21 00:13:45 Amazon cloud drive root '9-1': Reading "trabajo fotos boda virginia sergio/"
2016/01/21 00:13:45 Amazon cloud drive root '9-1': Reading "trabajo fotos de boda elena y alex/"
2016/01/21 00:13:45 Amazon cloud drive root '9-1': Reading "laura fotos embarazada aranjuez 17-jun-2015/"
2016/01/21 00:13:45 Amazon cloud drive root '9-1': Reading "lr5-prebodas-veronica-pilar-laura/"
2016/01/21 00:13:45 Amazon cloud drive root '9-1': Reading "trabajo album boda esther cesar/"
2016/01/21 00:13:45 Amazon cloud drive root '9-1': Reading "slideshow virginia sergio/"
2016/01/21 00:13:46 Amazon cloud drive root '9-1': Finished reading "16 boda elena&alex 13-jun-2015/"
2016/01/21 00:13:46 Amazon cloud drive root '9-1': Finished reading "laura fotos embarazada aranjuez 17-jun-2015/"
2016/01/21 00:13:46 Amazon cloud drive root '9-1': Finished reading "trabajo fotos de boda elena y alex/"
2016/01/21 00:13:46 Amazon cloud drive root '9-1': Finished reading "trabajo fotos boda virginia sergio/"
2016/01/21 00:13:46 Amazon cloud drive root '9-1': Finished reading "lr5-prebodas-veronica-pilar-laura/"
2016/01/21 00:13:46 Amazon cloud drive root '9-1': Finished reading "trabajo album boda esther cesar/"
2016/01/21 00:13:46 Amazon cloud drive root '9-1': Finished reading "slideshow virginia sergio/"
2016/01/21 00:14:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m2.1s

2016/01/21 00:15:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      2m2.1s

2016/01/21 00:16:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      3m2.1s

2016/01/21 00:17:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      4m2.1s

2016/01/21 00:18:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      5m2.1s

2016/01/21 00:19:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      6m2.1s

2016/01/21 00:20:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      7m2.1s

2016/01/21 00:21:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      8m2.1s

2016/01/21 00:22:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      9m2.1s

2016/01/21 00:23:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     10m2.1s

2016/01/21 00:24:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     11m2.1s

2016/01/21 00:25:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     12m2.1s

2016/01/21 00:26:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     13m2.1s

2016/01/21 00:27:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     14m2.1s

2016/01/21 00:28:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     15m2.1s

2016/01/21 00:29:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     16m2.1s

2016/01/21 00:30:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     17m2.1s

2016/01/21 00:31:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     18m2.1s

2016/01/21 00:32:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     19m2.1s

2016/01/21 00:33:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     20m2.1s

2016/01/21 00:34:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     21m2.1s

2016/01/21 00:35:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     22m2.1s

2016/01/21 00:36:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     23m2.1s

2016/01/21 00:37:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     24m2.1s

2016/01/21 00:38:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     25m2.1s

2016/01/21 00:39:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     26m2.1s

2016/01/21 00:40:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     27m2.1s

2016/01/21 00:41:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     28m2.1s

2016/01/21 00:42:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     29m2.1s

2016/01/21 00:43:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     30m2.1s

2016/01/21 00:44:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     31m2.1s

2016/01/21 00:45:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     32m2.1s

2016/01/21 00:46:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     33m2.1s

2016/01/21 00:47:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     34m2.1s

2016/01/21 00:48:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     35m2.1s

2016/01/21 00:49:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     36m2.1s

2016/01/21 00:50:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     37m2.1s

2016/01/21 00:51:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     38m2.1s

2016/01/21 00:52:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     39m2.1s

2016/01/21 00:53:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     40m2.1s

2016/01/21 00:54:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     41m2.1s

2016/01/21 00:55:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     42m2.1s

2016/01/21 00:56:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     43m2.1s

2016/01/21 00:57:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     44m2.1s

2016/01/21 00:58:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     45m2.1s

2016/01/21 00:59:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     46m2.1s

2016/01/21 01:00:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     47m2.1s

2016/01/21 01:01:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     48m2.1s

2016/01/21 01:02:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     49m2.1s

MacBook-Pro-13:bin David$ cat prueba.sh 
#!/bin/sh
# si se conecta el 9-1 usb
#if 2016/01/21 01:03:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     50m2.1s

2016/01/21 01:04:45 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     51m2.1s

**Comment by bunset** [comment]
Hello Nick.
I think you did close this issue by mistake. It is without resolving, may you change it to open?
Kind regards and happy saturday!

**Comment by avgex** [comment]
the fix will be released in v1.27
@ncw can we test it out in some beta ?

**Comment by ncw** [comment]
Thanks for your reports.  It looks like there is still a problem :-(  I'll see if I can replicate it.

If you could send me a log with `rclone -v --dump-headers` of it pausing that would be really helpful. It will be very big and contain sensitive info, so If you could email it to me privately that would be really helpful.

Here is a new beta.  I don't think it will fix the problem, but just so we are testing the same thing!

http://pub.rclone.org/v1.26-39-gc3a0c0c%CE%B2/

**Comment by ncw** [comment]
Actually don't bother sending me a log - I've reproduced the problem!

Will make a new Beta when I've figured out what is going on...

**Comment by bunset** [comment]
Thank you Nick, I keep waiting for your fix. Will you tell us your progress here on this thread?

**Comment by ncw** [comment]
This should be fixed in version 1.27 which I've just uploaded :-)

**Comment by avgex** [comment]
thank you Nick for the fix, I finally managed to upload some new files. However I noticed in log file that the "409 Conflict" error is still there, but it does not get stuck as before. Also the files in error seem to be all backed up already on amazon cloud, so it is not a big deal
here is the log file if you want  to check: 
https://dl.dropboxusercontent.com/u/432618/rcopy_/log3.zip

**Comment by ncw** [comment]
@avgex I see what happened there - that log was really helpful thank you.

The 409 errors are caused by the listing of the files going wrong.  Looks like I have a few more things to retry...

I made an issue here #340 - if you subscribe to that then you'll get updates on it.

**Comment by bunset** [comment]
Hello Nick!
I have tested it now and it is working well. Awesome.

One thing, please. When I do a copy I can see a resume at the end of copy process, showing me how many errors I had doing my copy, but every error I had was displayed while rclone was doing the copy in the middle of thousand of lines, so it is very difficult for me to get a clean list of just files with error. Is there any way or do you know any trick, so I can get a simple list of files giving error in my copy? 


Thank you very much, kind regards,
David

**Comment by ncw** [comment]
@bunset if you run rclone without the `-v` flag, it should only tell you about the errors rather than about everything it is copying.

**Comment by fcarreiro** [comment]
Hi, I'm also getting many 409 errors while syncing a folder, for example:

`
2016/07/08 13:26:34 avoidthecrowd/www/tmp/cache/sprockets/v3.0/ouIVwmb-ntMxhEoLCci-Im11GMCyKg0vRXAHhhRPaDU.cache: Failed to copy: HTTP code 409: "409 Conflict", reponse body: {"logref":"d37d396e-44fe-11e6-9e80-7576dc88fd3e","message":"Node with the name ouivwmb-ntmxheolcci-im11gmcykg0vrxahhhrpadu.cache already exists under parentId lXvdUqFIQKSGE_-XBRGCow conflicting NodeId: 8IsDNjWQTGmWDvxA4DVi6g","code":"NAME_ALREADY_EXISTS","info":{"nodeId":"8IsDNjWQTGmWDvxA4DVi6g"}}
2016/07/08 13:27:16 avoidthecrowd/www/tmp/cache/sprockets/v3.0/n1esMikxkVncQWoTefSzE79C8RfTVdUWWEo7C2UIQi4.cache: Failed to copy: HTTP code 409: "409 Conflict", reponse body: {"logref":"ec5e656e-44fe-11e6-a6dd-573b84944f90","message":"Node with the name n1esmikxkvncqwotefsze79c8rftvduwweo7c2uiqi4.cache already exists under parentId lXvdUqFIQKSGE_-XBRGCow conflicting NodeId: umkCEev_RT-n8eC6IOrNnQ","code":"NAME_ALREADY_EXISTS","info":{"nodeId":"umkCEev_RT-n8eC6IOrNnQ"}}
`

The names are not repeated locally (nor with a different case). Isn't rclone supposed to overwrite the remote files?

**Comment by ncw** [comment]
@fcarreiro are you using the latest version of rclone - 1.30 ?  If not can you try that.  If you get the problems with 1.30 then can you open a new issue with a log of all the errors - 409 errors are caused by the directory listing going wrong earlier which I believe is fixed in 1.30.

**Comment by fcarreiro** [comment]
I was using version 1.29; I'm now checking with 1.30 and will let you know if it still fails. Thanks.
