### ISSUE TITLE
Errors syncing to backblaze b2

### ISSUE THREAD

**Issue by wkf** [ncw/rclone#298]
Hello, I've been (mostly successfully) attempting to use rclone to sync some files to backblaze b2. Most files worked just fine, but for large files, I received this error:

```
Failed to copy: Failed to upload: file size too big: 8046431535 (400 bad_request)
```

My understanding was that backblaze had no file size limits.

And on some others, the error is:

```
Failed to copy: Failed to upload: Bad hex digit:   (400 bad_request)
```

Also, I get a message about an expired security token. Am I doing something wrong, or is this a bug?

- rclone v1.26
- debian wheezy x64

Thanks!

**Comment by klauspost** [comment]
>My understanding was that backblaze had no file size limits.
Unfortunately it does: [" Files can range in size from 0 bytes to 5 billion bytes."](https://www.backblaze.com/b2/docs/files.html).

> `Failed to copy: Failed to upload: Bad hex digit:   (400 bad_request)`

Does it keep giving the same error, if you retry the upload, or does it happen at random?

**Comment by klauspost** [comment]
Regarding the `bad hex digit`, it could be because it uses [`fmt.Sprintf("%x", hash.Sum(nil))`](`https://github.com/ncw/rclone/blob/master/b2/b2.go#L851`). It could be that it skips printing if the first byte is a zero value. That would make it fail on 1 in 256 files.

**Comment by ncw** [comment]
That is an interesting idea Klaus. I was thinking along the line of encoding of an unusual file name which I had problems with in development. 

@wkf Is it always the same files which fail with the percent message? If so could you post the names?

**Comment by klauspost** [comment]
Nah, it prints all values: http://play.golang.org/p/KnMHMW71Zd

**Comment by ncw** [comment]
@wkf can you share a failing file name?

**Comment by wkf** [comment]
@ncw Interestingly, all the bad hex digit files seem to be named `._Icon` or `Icon`.

**Comment by ncw** [comment]
@wkf are you still seeing these problems?  Things have been moving fast at backblaze so I'm hoping the issue is now fixed :-)

**Comment by ncw** [comment]
I'm going to assume this is fixed now - please re-open if not.

Thanks

Nick

**Comment by wkf** [comment]
Sorry about that, missed your update from a few days ago. Giving it another shot now. I'll reopen if it doesn't work. Thanks! :)

**Comment by hajes** [comment]
Unfortunately, it is not fixed.

I've asked Backblaze guys and there is their reply
==========================================

Rclone does not currently support our Large File API calls. So either support for large files will need to be added, or the file will need to be broken up into smaller chunks prior to upload. 

Cheers, 
 Christopher


https://www.backblaze.com/blog/technical-support-engineer-christopher/
The Backblaze Team

**Comment by ncw** [comment]
@hajes back blaze I'd a fast moving target - the large file support has only just been invented. Can you make a new issue please? 

Thanks 

Nick

**Comment by hajes** [comment]
ok, I thought it has been resolved or it is related
