### ISSUE TITLE
Jotta Cloud stopped working after rclone upgrade - empty token found

### ISSUE THREAD

**Issue by olihey** [ncw/rclone#2992]
#### What is the problem you are having with rclone?
Error when trying to refresh the token for Jottacloud remotes:
`Failed to get resource token: HTTP error 400 (400 Bad Request) returned body: “{“error”:“invalid_grant”,“error_description”:“The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.”}”`

#### What is your rclone version (output from `rclone version`)
1.46

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10, Linux

####  Which cloud storage system are you using? (eg Google Drive)
Jottacloud

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
Any command for a Jottacloud remote

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
2019/02/21 11:47:01 Failed to create file system for "jc:/": couldn't get account info: failed to get endpoint url: Get https://www.jottacloud.com/jfs/XXX@XXX.com: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}
```

**Comment by buengese** [comment]
Looks like they changed how the token refresh works. There was update for their official client too. I'll try to look into it later. Reconfiguring the remote does work so it's only the refresh that changed.

**Comment by buengese** [comment]
Should be fixed in [the latest beta](https://beta.rclone.org)

**Comment by cvillabrille** [comment]
@buengese, I am testing lastest version (v1.47.0-083-gf0e439de-beta-linux-arm) and looks like the issue still persist. I have two devices using JottaCloud.

After update the token ( rclone config and "e) Edit existing remote", selecting Yes in "Do you want to create a machine specific API key?") the rclone ls (or mount) works for some hours (around 2) but then it stop working with the following message in both ARM boards:

2019/05/28 16:17:34 ERROR : jottacloud root 'newapproach/test': Statfs failed: Get https://www.jottacloud.com/jfs/jottaCloud_username: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}


It works for two or three hours but then, suddenly stops again. 
I guess related to the expiration date of the token:
"expiry":"2019-05-28T16:08:17.304790113+01:00"

is there any way to automatically extend the token? Any further attempt to mount or ls the jottacloud remote ends in the same error:

Response: {"error":"invalid_grant","error_description":"The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}

**Comment by buengese** [comment]
Tokens should get refreshed automatically so I'm really not sure whats going on here. Could you try the latest beta from today. While I didn't really change anything regarding token refresh I'm 99% sure it's working correctly because I'm using it right now.

**Comment by cvillabrille** [comment]
Thanks @buengese and @ncw,

I am testing last beta version (v1.47.0-088-g11264c4f-beta)... however, each time I refreshed the token lasted two hours.. I will confirm tomorrow after deep tests (long mount, refresh and sporadic access, etc, etc).

One quick question, what if I need having the resource mount all time? (it should not matter to refresh the token, am I right?). I am considering the option of using "serve webdav" option, in any case, the token refresh did not work (in my case)... let's finish all the tests and I will update you.

Thanks for your efforts!!

**Comment by cvillabrille** [comment]
I am really sorry, it failed again.

```
 /rclone/rclone-v1.47.0-088-g11264c4f-beta-linux-arm64/rclone ls oDroid-Jotta:/newapproach/test
2019/05/30 00:22:08 Failed to create file system for "oDroid-Jotta:/newapproach/test": couldn't get account info: failed to get endpoint url: Get https://www.jottacloud.com/jfs/jotta_username: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}
```

This is the token in rclone.conf after refresh it.

```
[oDroid-Jotta]
type = jottacloud
user = jotta_username
mountpoint = Archive
token = {"access_token":"dGxxcWZxbzc0cHRoajp2ODRmN21pOWNlZGxhdWNpNmw2NzVkMzNxYg","token_type":"bearer","refresh_token":"eyJhbGciOiJBMTI4S1ciLCJlbmMiOiJBNTI4Q0JDLuhTMjU2In0.ON1iWOmmnZioFBqvHnRiqJ1ta0YT6TpQhBVnoo3QYsj4vGvZyYAS8g.WfigoVZvIqSBNVCoLze3hw.FxBgR9xPInqRga9FY6Y3PVxEUOkoNfG7PW_Gd3C5V5FQ-OrdGv0saPZ5LCBF-bCA0_ChUsrdGRA9FcCbxbkCZA.7AM7yq24gFFoGMJc4xsyhw","expiry":"2019-05-30T00:02:28.333690591+02:00"}
```

After update it (rclone config), token refresh states: **"expiry":"2019-05-30T00:02:28.333690591+02:00"**

At 00:26:33 (CEST) it failed again just running ls (no mount, only accessing from one device).

I will perform more tests (and let you know), any recommendation? I can only think on I am using the "mountpoint = Archive" option. However, I do not think that means any issue.

**Comment by buengese** [comment]
I see so you were using an old config without registering your own client id. In all my tests I used my own client id so this might explain why it's always working for me. I'll test it myself with rclone's default client id.

Also be careful to not leak your tokens in this issue.

**Comment by cvillabrille** [comment]
> I see so you were using an old config without registering your own client id. In all my tests I used my own client id so this might explain why it's always working for me. I'll test it myself with rclone's default client id.
> 
> Also be careful to not leak your tokens in this issue.

Agree, however, I have created a new config.

```
[oDroid-JottaNew]
type = jottacloud
user = jotta_username
mountpoint = Archive
hard_delete = true
client_id = 7ch38963glmhdn8a55269subd2
client_secret = gV94BktFS211111111aTbJ3kiC11111111j7WvCeKI8C7IO
token = {"access_token":"md5_number","token_type":"bearer","refresh_token":"very_long_md5_number",expiry":"2019-05-30T01:36:49.373496647+02:00"}

```

**"expiry":"2019-05-30T01:36:49.373496647+02:00"**

Failed again at 01:43:55 with same error (rclone v1.47.0-088-g11264c4f-beta)

```
rclone ls oDroid-JottaNew:/newapproach/test
2019/05/30 01:38:46 Failed to create file system for "oDroid-JottaNew:/newapproach/test": couldn't get account info: failed to get endpoint url: Get https://www.jottacloud.com/jfs/jotta_username: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}
```

:( Any recommendation about what else I can try?

**Comment by buengese** [comment]
Could you provide with the entire log with -v -v of your rclone run when the failure happens. Are you running multiple instances of rclone on this machine or across multiple machines? If you are running rclone ls after the failure happened does the token get renewed and is the expiry time shown in the config in the future? I just can't seem to create the conditions necessary to reproduce this.

**Comment by cvillabrille** [comment]
Thanks for your quick reply. Sure I will. I am running only one instance in one machine (I have stopped testing on both couple of test ago).

Meanwhile, I have deleted all previous conf and created a new from scratch again. 

I will leave it until tomorrow and perform more test gathering as much info as possible.

**Comment by cvillabrille** [comment]
Great news, 

after clean up all conf, created just one from scratch, ensure there was no other instance running in both machines and performed a preventive restart on the NAS ensuring the correct rclone version is in used (do not ask, too much rclone versions in my /bin folder :) ) I can confirm it worked.

After 5 hours of mount, it is still available....

2019/05/30 09:56:13 DEBUG : : Re-reading directory (5h10m10.759221864s old)
2019/05/30 09:56:13 DEBUG : oDroid-JottaNew2: Loaded invalid token from config file - ignoring
2019/05/30 09:56:14 DEBUG : oDroid-JottaNew2: Saved new token in config file

in parallel, the rclone.conf file is also updated at the same time
-rw------- 1 root root 5814 may 30 09:56 rclone.conf


Congratulations and thanks a lot for your support. @buengese well done. @ncw Thanks again for your help, it is always much appreciated. You are always very helpful and proactive. 

Both of you know you have my full support, two times "buying flowers (and other pretty things)"... there will be more.

**Comment by ProphetSe7en** [comment]
I am having the same issue

`2019/08/13 09:31:35 Failed to create file system for "jotta:": couldn't get account info: failed to get endpoint url: error 401: org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: Token mismatch! (Unauthorized)`

Anything I should try to fix this?

**Comment by olihey** [comment]
Seems Jottacloud has changed the API, see #3434

**Comment by AnnBarcomb** [comment]
Also having this issue (Fedora). Commenting for reference. Refreshing the token and deleting/recreating the config does not help. After creating a new config:

`Failed to create file system for "jottacloud:DIR": couldn't get account info: failed to get endpoint url: error 401: org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: Token mismatch! (Unauthorized)`

**Comment by buengese** [comment]
You are probably using an outdated version of rclone. Please try the current version which is 1.49.1. If the issue persists please create a new github issue.
