### ISSUE TITLE
drive: large server side copies failing with 500 error

### ISSUE THREAD

**Issue by MLZC** [ncw/rclone#3070]
Thank you for reading my question.

I an using "rclone copy" to transfer shared folders to my  google drive. But something went wrong.

code here

```shell
rclone copy -v mydrive:A mydrive:A
rclone sync mydrive:A mydrive:A
```

sync error code here

```
2019/03/22 19:39:16 ERROR : S H E-2gether 4ever Encore live concert in Taipei 2014 1080i BluRay REMUX AVC DTS -HD MA 5.1 -HDS/BDMV/STREAM/00000.m2ts: Failed to copy: googleapi: Error 500: Internal Error, internalError
2019/03/22 19:39:16 ERROR : Google drive root 'Media/Music': not deleting files as there were IO errors
2019/03/22 19:39:16 ERROR : Google drive root 'Media/Music': not deleting directories as there were IO errors
2019/03/22 19:39:16 ERROR : Attempt 1/3 failed with 1 errors and: googleapi: Error 500: Internal Error, internalError
2019/03/22 21:51:25 ERROR : S H E-2gether 4ever Encore live concert in Taipei 2014 1080i BluRay REMUX AVC DTS -HD MA 5.1 -HDS/BDMV/STREAM/00000.m2ts: Failed to copy: googleapi: Error 500: Internal Error, internalError
2019/03/22 21:51:25 ERROR : Google drive root 'Media/Music': not deleting files as there were IO errors
2019/03/22 21:51:25 ERROR : Google drive root 'Media/Music': not deleting directories as there were IO errors
2019/03/22 21:51:25 ERROR : Attempt 2/3 failed with 1 errors and: googleapi: Error 500: Internal Error, internalError
2019/03/23 00:09:55 ERROR : S H E-2gether 4ever Encore live concert in Taipei 2014 1080i BluRay REMUX AVC DTS -HD MA 5.1 -HDS/BDMV/STREAM/00000.m2ts: Failed to copy: googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded
2019/03/23 00:09:55 ERROR : Google drive root 'Media/Music': not deleting files as there were IO errors
2019/03/23 00:09:55 ERROR : Google drive root 'Media/Music': not deleting directories as there were IO errors
2019/03/23 00:09:55 ERROR : Attempt 3/3 failed with 1 errors and: googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded
2019/03/23 00:09:55 Failed to sync: googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded
```
copy error code here

```shell
2019/03/23 16:44:06 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:              9219 / 9219, 100%
Transferred:            0 / 1, 0%
Elapsed time:    6h6m1.4s
Transferring:
 * 极客时间-已经完结的课程/11 大咖说/In…16期 续彬/InfoQ大咖说-续彬.m4v: transferring

2019/03/23 16:45:06 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:              9219 / 9219, 100%
Transferred:            0 / 1, 0%
Elapsed time:    6h7m1.4s
Transferring:
 * 极客时间-已经完结的课程/11 大咖说/In…16期 续彬/InfoQ大咖说-续彬.m4v: transferring

```

This code block has been repeated all the time, but the file cannot be copied over.

Firstly, I am using a deep os with a memory size of 0.6g, rclone v1.46. And I added 2g of swap space. 

Second, I have replaced default api by my own. And the upper limit of 750G is far from reaching. 

Finally, I try to replace "rclone copy" with "rclone sync",but the problem still exists.

I would like to know the reason for this problem and how to fix this problem.

**Comment by MLZC** [comment]
```
2019/03/23 18:06:53 ERROR : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第16期 续彬/InfoQ大咖说-续彬.m4v: Failed to copy: googleapi: Error 503: Backend Error, backendError
2019/03/23 18:06:53 ERROR : Attempt 3/3 failed with 1 errors and: googleapi: Error 503: Backend Error, backendError
2019/03/23 18:06:53 Failed to copy: googleapi: Error 503: Backend Error, backendError
```

**Comment by ncw** [comment]
> Error 503: Backend Error, backendError

That is a google internal error.  I don't know what causes that.

Does a retry fix it, or does it always give that error?

**Comment by MLZC** [comment]
> > Error 503: Backend Error, backendError
> 
> That is a google internal error. I don't know what causes that.
> 
> Does a retry fix it, or does it always give that error?

Thanks for your replay,  retry it but always gives an error. 

I forgot to mention that I am copying data between the same Google cloud disk. This file is 3G size, I find  this error occurs if the copied file is larger. But It is normal when I was operating on the web side of Google drive.

I try to run the follow code and the file size to be copied is 45G.

>rclone copy -vv --dump bodies --retries 1 gdswccd:SHE gdswccd:test

```
2019/03/25 21:38:15 DEBUG : HTTP/1.1 500 Internal Server Error
Transfer-Encoding: chunked
Cache-Control: private, max-age=0
Content-Type: application/json; charset=UTF-8
Date: Mon, 25 Mar 2019 13:37:08 GMT
Expires: Mon, 25 Mar 2019 13:37:08 GMT
Server: GSE
Vary: Origin
Vary: X-Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

84
{"error":{"errors":[{"domain":"global","reason":"internalError","message":"Internal Error"}],"code":500,"message":"Internal Error"}}
0

2019/03/25 21:38:15 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/03/25 21:38:15 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 500: Internal Error, internalError)
2019/03/25 21:38:15 DEBUG : pacer: Rate limited, increasing sleep to 2.15455162s
2019/03/25 21:38:15 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/03/25 21:38:15 DEBUG : HTTP REQUEST (req 0xc000418900)
2019/03/25 21:38:15 DEBUG : POST /drive/v3/files/1vxrEePt0zBcs7uDtdUxfKtutRntI_ciF/copy?alt=json&fields=id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink&keepRevisionForever=false&prettyPrint=false&supportsTeamDrives=false HTTP/1.1
Host: www.googleapis.com
User-Agent: rclone/v1.46.0-103-gc3aab713-fix-3033-copy-transfer-beta
Content-Length: 182
Authorization: XXXX
Content-Type: application/json
Accept-Encoding: gzip

{"description":"00000.m2ts","mimeType":"video/vnd.dlna.mpeg-tts","modifiedTime":"2019-03-19T20:01:58.016000000Z","name":"00000.m2ts","parents":["1Inwx_aUADagkPXqVRxvaRei_8WIhabhU"]}
2019/03/25 21:38:15 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/03/25 21:38:15 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/03/25 21:38:15 DEBUG : HTTP RESPONSE (req 0xc000418900)
2019/03/25 21:38:15 DEBUG : HTTP/1.1 403 Forbidden
Transfer-Encoding: chunked
Cache-Control: private, max-age=0
Content-Type: application/json; charset=UTF-8
Date: Mon, 25 Mar 2019 13:38:15 GMT
Expires: Mon, 25 Mar 2019 13:38:15 GMT
Server: GSE
Vary: Origin
Vary: X-Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

97
{"error":{"errors":[{"domain":"usageLimits","reason":"rateLimitExceeded","message":"Rate Limit Exceeded"}],"code":403,"message":"Rate Limit Exceeded"}}
0

2019/03/25 21:38:15 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/03/25 21:38:15 DEBUG : pacer: low level retry 3/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2019/03/25 21:38:15 DEBUG : pacer: Rate limited, increasing sleep to 4.463359852s
2019/03/25 21:38:17 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/03/25 21:38:17 DEBUG : HTTP REQUEST (req 0xc0001b0100)
2019/03/25 21:38:17 DEBUG : POST /drive/v3/files/1vxrEePt0zBcs7uDtdUxfKtutRntI_ciF/copy?alt=json&fields=id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink&keepRevisionForever=false&prettyPrint=false&supportsTeamDrives=false HTTP/1.1
Host: www.googleapis.com
User-Agent: rclone/v1.46.0-103-gc3aab713-fix-3033-copy-transfer-beta
Content-Length: 182
Authorization: XXXX
Content-Type: application/json
Accept-Encoding: gzip
Reply
```

**Comment by ncw** [comment]
There are other people reporting difficulties copying very big files in [this thread on the google forums](https://productforums.google.com/forum/#!topic/drive/OgnC30vb8bM;context-place=mydiscussions).

This must be some kind of google limit but I don't know what.

If you don't mind downloading and re-uploading the data you can use `--disable Copy`.

**Comment by MLZC** [comment]
I read this discussion but it is  strange that I using another chrom app "copy, url to google drive'.  This app also needs to get my verification id but there are no errors. I think the reason for the error should be 'rclone' regards the copy between remote as a local upload to the remote. So the error rateLimitExceeded will appear.

**Comment by KCBAI** [comment]
I'm seeing the same issues copying between two Team Drives, it's not any kind of rate limit. Just an unhelpful 'Backend Error' for bigger files.

`$ rclone ls instbackup:
3956080640 bigtestfile
        5 test
`
<details> 
  <summary>rclone copy -vv --dump bodies --retries 1 drive1 drive2</summary>
`$ rclone copy -vv --dump bodies --retries 1 drive1: drive2:
2019/04/30 12:48:31 DEBUG : rclone: Version "v1.47.0" starting with parameters ["rclone" "copy" "-vv" "--dump" "bodies" "--retries" "1" "drive1:" "drive2:"]
2019/04/30 12:48:31 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2019/04/30 12:48:31 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/04/30 12:48:31 DEBUG : HTTP REQUEST (req 0xc0004d6100)
2019/04/30 12:48:31 DEBUG : GET /drive/v3/files?alt=json&corpora=teamDrive&fields=files%28id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%29%2CnextPageToken&includeTeamDriveItems=true&pageSize=1000&prettyPrint=false&q=trashed%3Dfalse+and+%28%270AOIBmRy3bcFqUk9PVA%27+in+parents%29&supportsTeamDrives=true&teamDriveId=0AOIBmRy3bcFqUk9PVA HTTP/1.1
Host: www.googleapis.com
User-Agent: rclone/v1.47.0
Authorization: XXXX
Accept-Encoding: gzip

2019/04/30 12:48:31 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/04/30 12:48:31 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/04/30 12:48:31 DEBUG : HTTP REQUEST (req 0xc0004fa100)
2019/04/30 12:48:31 DEBUG : POST /token HTTP/1.1
Host: oauth2.googleapis.com
User-Agent: rclone/v1.47.0
Content-Length: 783
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

assertion=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImEyNTRjNzE2ZmE2YTNjYzQwNmZhY2QxODM3YzcwNjg1NzBhNmE1ZmMifQ.eyJpc3MiOiJjYmctcmNsb25lLWJhY2t1cEBpdC1zZXJ2aWNlcy0yMDA5MTEuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJzY29wZSI6Imh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL2F1dGgvZHJpdmUiLCJhdWQiOiJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsImV4cCI6MTU1NjYyODUwMSwiaWF0IjoxNTU2NjI0OTAxfQ.q72JyR9mBsHLTE1CJ2dZRusohBvmGXAWrNHHKhd3STRHSuQAe6Y1nKM0enHMCM91s0mHjky2JzZqMLaXNuUVoFMXMIfcc4SFPJ8-BZUv59djrqEWPGLgDj_ff-O9A3e3yP3rtstp1Y_tP64KZSYLkJXjGB-rMKZXjdlzyS_TOJLLgCik2_qvnFykWLRyKfiJ-qyaq86-HPCPjeNT2fY9x4nQxT2pgYQ-SOg9BsOE2Oq6aaHZJUYawa75ZY4iQUanQMYTuRDHpsdM-xQvrotpZegtcvj1SNnCjxHnYNrfS3PM8t_qiNTAgrkSIdQGoiSAoImiQwsGwxFfBgGOphiYyA&grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer
2019/04/30 12:48:31 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/04/30 12:48:32 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/04/30 12:48:32 DEBUG : HTTP RESPONSE (req 0xc0004fa100)
2019/04/30 12:48:32 DEBUG : HTTP/1.1 200 OK
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; ma=2592000; v="46,44,43,39"
Cache-Control: private
Content-Type: application/json; charset=utf-8
Date: Tue, 30 Apr 2019 11:48:32 GMT
Server: scaffolding on HTTPServer2
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

c9
{
  "access_token": "ya29.c.Eln7BuCMwzz5AE9icHEnot3-tzelFER8STCD7u_fASmxwd8RML9QxPcEb1sEQx6rI9RltapXixJA84DB47nJ7Jz5pSGvFpQq-Uify9MXYhkMCGREUnR_V99VxQ",
  "expires_in": 3600,
  "token_type": "Bearer"
}
0

2019/04/30 12:48:32 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/04/30 12:48:32 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/04/30 12:48:32 DEBUG : HTTP REQUEST (req 0xc00038b400)
2019/04/30 12:48:32 DEBUG : GET /drive/v3/files?alt=json&corpora=teamDrive&fields=files%28id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%29%2CnextPageToken&includeTeamDriveItems=true&pageSize=1000&prettyPrint=false&q=trashed%3Dfalse+and+%28%271BEzPvLg8S1hXUk9PVA%27+in+parents%29&supportsTeamDrives=true&teamDriveId=1BEzPvLg8S1hXUk9PVA HTTP/1.1
Host: www.googleapis.com
User-Agent: rclone/v1.47.0
Authorization: XXXX
Accept-Encoding: gzip

2019/04/30 12:48:32 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/04/30 12:48:32 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/04/30 12:48:32 DEBUG : HTTP RESPONSE (req 0xc0004d6100)
2019/04/30 12:48:32 DEBUG : HTTP/1.1 200 OK
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; ma=2592000; v="46,44,43,39"
Cache-Control: private, max-age=0, must-revalidate, no-transform
Content-Type: application/json; charset=UTF-8
Date: Tue, 30 Apr 2019 11:48:32 GMT
Expires: Tue, 30 Apr 2019 11:48:32 GMT
Server: GSE
Vary: Origin
Vary: X-Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

c
{"files":[]}
0

2019/04/30 12:48:32 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/04/30 12:48:32 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/04/30 12:48:32 DEBUG : HTTP RESPONSE (req 0xc00038b400)
2019/04/30 12:48:32 DEBUG : HTTP/1.1 200 OK
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; ma=2592000; v="46,44,43,39"
Cache-Control: private, max-age=0, must-revalidate, no-transform
Content-Type: application/json; charset=UTF-8
Date: Tue, 30 Apr 2019 11:48:32 GMT
Expires: Tue, 30 Apr 2019 11:48:32 GMT
Server: GSE
Vary: Origin
Vary: X-Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

326
{"files":[{"id":"1K33axEX6K7c_75ZIj0Rff3_9_Z-AmU7T","name":"bigtestfile","mimeType":"application/x-iso9660-image","trashed":false,"parents":["1BEzPvLg8S1hXUk9PVA"],"webViewLink":"https://drive.google.com/file/d/1K33axEX6K7c_75ZIj0Rff3_9_Z-AmU7T/view?usp=drivesdk","createdTime":"2019-04-30T10:49:30.589Z","modifiedTime":"2019-04-30T11:46:09.599Z","md5Checksum":"6ced2c7c1db5694d99d892c1dbcb6501","size":"3956080640"},{"id":"1fMjkipKCAM21y0C2ABCs4rZDCdNWQ8jK","name":"test","mimeType":"application/octet-stream","trashed":false,"parents":["1BEzPvLg8S1hXUk9PVA"],"webViewLink":"https://drive.google.com/file/d/1fMjkipKCAM21y0C2ABCs4rZDCdNWQ8jK/view?usp=drivesdk","createdTime":"2019-04-30T11:45:08.681Z","modifiedTime":"2019-04-30T11:44:55.251Z","md5Checksum":"53cd6a6c916d782939bdf24b230fc8e9","size":"5"}]}
0

2019/04/30 12:48:32 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/04/30 12:48:32 INFO  : Google drive root '': Waiting for checks to finish
2019/04/30 12:48:32 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/04/30 12:48:32 DEBUG : HTTP REQUEST (req 0xc0004fa400)
2019/04/30 12:48:32 DEBUG : GET /drive/v3/files?alt=json&corpora=teamDrive&fields=files%28id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%29%2CnextPageToken&includeTeamDriveItems=true&pageSize=1000&prettyPrint=false&q=trashed%3Dfalse+and+%28%270AOIBmRy3bcFqUk9PVA%27+in+parents%29+and+%28name%3D%27bigtestfile%27%29+and+mimeType%21%3D%27application%2Fvnd.google-apps.folder%27&supportsTeamDrives=true&teamDriveId=0AOIBmRy3bcFqUk9PVA HTTP/1.1
Host: www.googleapis.com
User-Agent: rclone/v1.47.0
Authorization: XXXX
Accept-Encoding: gzip

2019/04/30 12:48:32 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/04/30 12:48:32 INFO  : Google drive root '': Waiting for transfers to finish
2019/04/30 12:48:32 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/04/30 12:48:32 DEBUG : HTTP REQUEST (req 0xc0004fa700)
2019/04/30 12:48:32 DEBUG : GET /drive/v3/files?alt=json&corpora=teamDrive&fields=files%28id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%29%2CnextPageToken&includeTeamDriveItems=true&pageSize=1000&prettyPrint=false&q=trashed%3Dfalse+and+%28%270AOIBmRy3bcFqUk9PVA%27+in+parents%29+and+%28name%3D%27test%27%29+and+mimeType%21%3D%27application%2Fvnd.google-apps.folder%27&supportsTeamDrives=true&teamDriveId=0AOIBmRy3bcFqUk9PVA HTTP/1.1
Host: www.googleapis.com
User-Agent: rclone/v1.47.0
Authorization: XXXX
Accept-Encoding: gzip

2019/04/30 12:48:32 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/04/30 12:48:32 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/04/30 12:48:32 DEBUG : HTTP RESPONSE (req 0xc0004fa700)
2019/04/30 12:48:32 DEBUG : HTTP/1.1 200 OK
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; ma=2592000; v="46,44,43,39"
Cache-Control: private, max-age=0, must-revalidate, no-transform
Content-Type: application/json; charset=UTF-8
Date: Tue, 30 Apr 2019 11:48:32 GMT
Expires: Tue, 30 Apr 2019 11:48:32 GMT
Server: GSE
Vary: Origin
Vary: X-Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

c
{"files":[]}
0

2019/04/30 12:48:32 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/04/30 12:48:32 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/04/30 12:48:32 DEBUG : HTTP REQUEST (req 0xc00038b700)
2019/04/30 12:48:32 DEBUG : POST /drive/v3/files/1fMjkipKCAM21y0C2ABCs4rZDCdNWQ8jK/copy?alt=json&fields=id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink&keepRevisionForever=false&prettyPrint=false&supportsTeamDrives=true HTTP/1.1
Host: www.googleapis.com
User-Agent: rclone/v1.47.0
Content-Length: 157
Authorization: XXXX
Content-Type: application/json
Accept-Encoding: gzip

{"description":"test","mimeType":"application/octet-stream","modifiedTime":"2019-04-30T11:44:55.251000000Z","name":"test","parents":["0AOIBmRy3bcFqUk9PVA"]}
2019/04/30 12:48:32 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/04/30 12:48:32 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/04/30 12:48:32 DEBUG : HTTP RESPONSE (req 0xc0004fa400)
2019/04/30 12:48:32 DEBUG : HTTP/1.1 200 OK
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; ma=2592000; v="46,44,43,39"
Cache-Control: private, max-age=0, must-revalidate, no-transform
Content-Type: application/json; charset=UTF-8
Date: Tue, 30 Apr 2019 11:48:32 GMT
Expires: Tue, 30 Apr 2019 11:48:32 GMT
Server: GSE
Vary: Origin
Vary: X-Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

c
{"files":[]}
0

2019/04/30 12:48:32 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/04/30 12:48:32 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/04/30 12:48:32 DEBUG : HTTP REQUEST (req 0xc0004fa200)
2019/04/30 12:48:32 DEBUG : POST /drive/v3/files/1K33axEX6K7c_75ZIj0Rff3_9_Z-AmU7T/copy?alt=json&fields=id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink&keepRevisionForever=false&prettyPrint=false&supportsTeamDrives=true HTTP/1.1
Host: www.googleapis.com
User-Agent: rclone/v1.47.0
Content-Length: 171
Authorization: XXXX
Content-Type: application/json
Accept-Encoding: gzip

{"description":"bigtestfile","mimeType":"application/octet-stream","modifiedTime":"2019-04-30T11:46:09.599000000Z","name":"bigtestfile","parents":["0AOIBmRy3bcFqUk9PVA"]}
2019/04/30 12:48:32 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/04/30 12:48:34 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/04/30 12:48:34 DEBUG : HTTP RESPONSE (req 0xc00038b700)
2019/04/30 12:48:34 DEBUG : HTTP/1.1 200 OK
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; ma=2592000; v="46,44,43,39"
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/json; charset=UTF-8
Date: Tue, 30 Apr 2019 11:48:34 GMT
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Server: GSE
Vary: Origin
Vary: X-Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

193
{"id":"1l0rDHZWZ2VFNai50fjiVJmki3n_ChaB5","name":"test","mimeType":"application/octet-stream","trashed":false,"parents":["0AOIBmRy3bcFqUk9PVA"],"webViewLink":"https://drive.google.com/a/org.ai/file/d/1l0rDHZWZ2VFNai50fjiVJmki3n_ChaB5/view?usp=drivesdk","createdTime":"2019-04-30T11:48:32.723Z","modifiedTime":"2019-04-30T11:44:55.251Z","md5Checksum":"53cd6a6c916d782939bdf24b230fc8e9","size":"5"}
0

2019/04/30 12:48:34 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/04/30 12:48:34 INFO  : test: Copied (server side copy)
2019/04/30 12:49:31 INFO  : 
Transferred:   	         5 / 5 Bytes, 100%, 0 Bytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            1 / 2, 50%
Elapsed time:        1m0s
Transferring:
 *                                   bigtestfile: transferring

2019/04/30 12:50:02 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/04/30 12:50:02 DEBUG : HTTP RESPONSE (req 0xc0004fa200)
2019/04/30 12:50:02 DEBUG : HTTP/1.1 503 Service Unavailable
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; ma=2592000; v="46,44,43,39"
Cache-Control: private, max-age=0
Content-Type: application/json; charset=UTF-8
Date: Tue, 30 Apr 2019 11:50:02 GMT
Expires: Tue, 30 Apr 2019 11:50:02 GMT
Server: GSE
Vary: Origin
Vary: X-Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

81
{"error":{"errors":[{"domain":"global","reason":"backendError","message":"Backend Error"}],"code":503,"message":"Backend Error"}}
0

2019/04/30 12:50:02 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/04/30 12:50:02 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 503: Backend Error, backendError)
2019/04/30 12:50:02 DEBUG : pacer: Rate limited, increasing sleep to 1.835974361s
2019/04/30 12:50:02 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/04/30 12:50:02 DEBUG : HTTP REQUEST (req 0xc000646100)
2019/04/30 12:50:02 DEBUG : POST /drive/v3/files/1K33axEX6K7c_75ZIj0Rff3_9_Z-AmU7T/copy?alt=json&fields=id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink&keepRevisionForever=false&prettyPrint=false&supportsTeamDrives=true HTTP/1.1
Host: www.googleapis.com
User-Agent: rclone/v1.47.0
Content-Length: 171
Authorization: XXXX
Content-Type: application/json
Accept-Encoding: gzip

{"description":"bigtestfile","mimeType":"application/octet-stream","modifiedTime":"2019-04-30T11:46:09.599000000Z","name":"bigtestfile","parents":["0AOIBmRy3bcFqUk9PVA"]}
2019/04/30 12:50:02 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/04/30 12:50:31 INFO  : 
Transferred:   	         5 / 5 Bytes, 100%, 0 Bytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            1 / 2, 50%
Elapsed time:        2m0s
Transferring:
 *                                   bigtestfile: transferring

^C
`
</details>

**Comment by ncw** [comment]
I'm not sure what to do about this.  It seems to be a problem at the google drive end.  Rclone uses the [v3 copy API](https://developers.google.com/drive/api/v3/reference/files/copy) and nowhere in that is mention of file size limits.

I suspect it is an internal timeout when copying the very large file.

**Comment by isoisoiso** [comment]
Having the same problem, rclone gets stuck when trying to copy 10 specific files and -vv shows backend error.
Sizes range is between 1GB and 15GB.

**Comment by IIeTp** [comment]
> AirExplorer can copy them just fine.
without download?

same issue with .m2ts files (any size). 
copied mkv files to almost 50 tb, there were no problems. copied instantly

**Comment by IIeTp** [comment]
As a temporary solution for rclone, I suggest the following script. If the file is not copied for some time, make a duplicate of the desired file (in google drive, right click with the mouse -> make a copy), move to the right place and rename (remove the "copy of" in the file name).

It will work fine, I tried. Only copying does not work.

**Comment by ncw** [comment]
> As a temporary solution for rclone, I suggest the following script. If the file is not copied for some time, make a duplicate of the desired file (in google drive, right click with the mouse -> make a copy), move to the right place and rename (remove the "copy of" in the file name).
> 
> It will work fine, I tried. Only copying does not work.

Interesting.  That kind of implies that the file has got rate limited at google somehow.

**Comment by isoisoiso** [comment]
> As a temporary solution for rclone, I suggest the following script. If the file is not copied for some time, make a duplicate of the desired file (in google drive, right click with the mouse -> make a copy), move to the right place and rename (remove the "copy of" in the file name).
> 
> It will work fine, I tried. Only copying does not work.

That's what I do. But something worth mentioning is that if you then run rclone copy on that copy you just manually made, it will get stuck regardless. There is something about these files that rclone does not like. I could provide public gdrive folder with 10 files that get stuck if anyone wants to do some tests on them. Folder ID is 1zu61e6QhvZmFNVbTWoee1h4WndQ6AnbD .

**Comment by ncw** [comment]
@isoisoiso thanks for that test directory, very useful

I can see the same problem.  Here are the times between starting the server side copy request and the error message coming back

    2019/07/03 13:16:45 DEBUG : HTTP REQUEST (req 0xc0004bd600)
    2019/07/03 13:18:15 DEBUG : HTTP RESPONSE (req 0xc0004bd600)

    2019/07/03 13:18:15 DEBUG : HTTP REQUEST (req 0xc00011c400)
    2019/07/03 13:19:44 DEBUG : HTTP RESPONSE (req 0xc00011c400)

    2019/07/03 13:19:44 DEBUG : HTTP REQUEST (req 0xc00060f300)
    2019/07/03 13:21:14 DEBUG : HTTP RESPONSE (req 0xc00060f300)

    2019/07/03 13:21:14 DEBUG : HTTP REQUEST (req 0xc00011c400)
    2019/07/03 13:22:43 DEBUG : HTTP RESPONSE (req 0xc00011c400)

All of these are exactly 89 or 90 seconds for the transaction

```
>>> 60*18+15-(60*16+45)
90
>>> 60*19+44-(60*18+15)
89
>>> 60*21+14-(60*19+44)
90
>>> 60*22+43-(60*21+14)
89
```

Which makes me think this must be a timeout issue at google.  I searched for bug on the [google issue tracker](https://issuetracker.google.com/issues?q=componentid:191650) bug I couldn't find a relevant one.

> AirExplorer can copy them just fine.

Any chance you could find out exactly what AirExplorer is sending in the HTTP request? You might need to use something like [burp suite](https://www.google.com/search?q=burp+suite+intercept+https) to intercept the https traffic.

For comparison this is what rclone sends

```
2019/07/03 13:22:43 DEBUG : POST /drive/v3/files/1Uz-iyOeP_zqyzJBAm12jWuFmf5DZCQbq/copy?alt=json&fields=id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink&keepRevisionForever=false&prettyPrint=false&supportsTeamDrives=false HTTP/1.1
Host: www.googleapis.com
User-Agent: rclone/v1.48.0-DEV
Content-Length: 206
Authorization: XXXX
Content-Type: application/json
Accept-Encoding: gzip

{
  "description": "file name",
  "mimeType": "application/octet-stream",
  "modifiedTime": "2019-07-02T17:29:17.600000000Z",
  "name": "file name",
  "parents": [
    "root"
  ]
}
```

**Comment by darthShadow** [comment]
I tried out a couple of variants of the above request using different parameters via curl and the API explorer available at https://developers.google.com/drive/api/v3/reference/files/copy.

Looks like the issue is with the `mimeType`. As soon as I don't specify a mimeType in the request it starts working.

I have been able to replicate similar behaviour on my own files which failed to copy server-side. Their original mimeType was `video/x-matroska` which timed out after ~90s with the same error but if I tried copying the same files with the mimeType set to `application/octet-stream` or even no mimeType, it works.

**Comment by ncw** [comment]
Super debugging @darthShadow well done :-)

I tried the example above and it worked perfectly.

I made a beta of rclone with this change in for everyone to try

https://beta.rclone.org/branch/v1.48.0-062-gde20031e-fix-3070-drive-copy-beta/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
Just looking at [the docs for server side copy](https://developers.google.com/drive/api/v3/reference/files/copy) some more.

> Creates a copy of a file and applies any requested updates with patch semantics.

So setting the mime type is perfectly allowed.  It not working must be classed a s a bug.

What I conjecture is happening is that if you attempt to set the mime type (maybe to something different) then google is doing an actual copy of the file which is taking a very long time (since it is large) and failing after a 90s timeout.  When I tried the above on a large file without mime type it copied instantly indicating drive wasn't copying the actual data (kind of like a hard link on unix).

I'm not really sure why rclone was setting the mime type - it isn't necessary on a copy at all.

**Comment by darthShadow** [comment]
I am not really sure whether skipping the mime type is the correct solution, to be honest. If the mime type is not set, then the new file has the mime type by default as `application/octet-stream` which is binary and may break things which expect the copied file to have the correct mime type or the same mime type as the original.

Perhaps, this could be a flag instead and we could add a note regarding the 500 error without this flag enabled?

**Comment by darthShadow** [comment]
Btw, did the builds fail to compile? I don't see the linux builds present

**Comment by IIeTp** [comment]
I tried. All my files began to be copied with the active flag "--disable Copy", but I did not include it.
My command line:  remote1:dest remote2:dest --progress

**Comment by darthShadow** [comment]
@IIeTp Server Side Copies are disabled by default in 1.48. Are you using the `--drive-server-side-across-configs` flag to enable it?

**Comment by IIeTp** [comment]
> @IIeTp Server Side Copies are disabled by default in 1.48. Are you using the `--drive-server-side-across-configs` flag to enable it?


No, I did not use it. with the new flag all copied. thank!

**Comment by ncw** [comment]
> I am not really sure whether skipping the mime type is the correct solution, to be honest. If the mime type is not set, then the new file has the mime type by default as `application/octet-stream` which is binary and may break things which expect the copied file to have the correct mime type or the same mime type as the original.

My reading of the docs indicates that if you don't supply the mime type you should get the mime type of the original file.  Is that not what you see?

> Perhaps, this could be a flag instead and we could add a note regarding the 500 error without this flag enabled?

It could if we need it.

> Btw, did the builds fail to compile? I don't see the linux builds present

Yes the builder failed, I gave it a kick

**Comment by darthShadow** [comment]
Sorry, my mistake. Checked the wrong file which already had the type as binary. Looks fine then.

Another thought, do you think this could be the cause for the [bug](https://github.com/ncw/rclone/issues/3033) with the 4-letter extensions like mk3d too?

**Comment by ncw** [comment]
> Sorry, my mistake. Checked the wrong file which already had the type as binary. Looks fine then.

:-)
 
> Another thought, do you think this could be the cause for the [bug](https://github.com/ncw/rclone/issues/3033) with the 4-letter extensions like mk3d too?

Yes that is almost certainly the same problem.  The mime type rclone chooses will be different to the one on the file.

**Comment by darthShadow** [comment]
Nice, so that is another bug solved then once a couple of folks try it out.

Possible to change the default value of `--drive-server-side-across-configs` to true then?

**Comment by darthShadow** [comment]
Disregard the above comment. Forgot about the need for appropriate permissions.

**Comment by 88lex** [comment]
@darthshadow Thanks for giving a heads up re this.

@ncw Tested the 062 beta linked above on Windows and Linux machines with m2ts, mk3d, vob and m4v files (all of which did not copy/sync server side previously.  Happy to report all four file types copied server side successfully with --drive-server-side-across-configs enabled.

Brilliant, and thank you all.

**Comment by ncw** [comment]
I realised that this could be affecting server side moves also so for safety I've removed that too.

Here is a new beta to test:

https://beta.rclone.org/branch/v1.48.0-062-g3fcd4c69-fix-3070-drive-copy-beta/ (uploaded in 15-30 mins)

**Comment by 88lex** [comment]
> I realised that this could be affecting server side moves also so for safety I've removed that too.
> 
> Here is a new beta to test:
> 
> https://beta.rclone.org/branch/v1.48.0-062-g3fcd4c69-fix-3070-drive-copy-beta/ (uploaded in 15-30 mins)

Happy to test.  I just tested the earlier version with move (as well as copy and sync) for m2ts and mk3d files up to 25GB. Server side moves worked fine.

Is there a specific case that this version fixes that may have previously failed?  Or just safety / consistency?

**Comment by ncw** [comment]
> Is there a specific case that this version fixes that may have previously failed? Or just safety / consistency?

I think it should work exactly as the previous beta and it did in my tests, I'd just like a double check :-)

**Comment by ncw** [comment]
@darthShadow wrote:
> Possible to change the default value of `--drive-server-side-across-configs` to true then?

What we need here is a 100% reliable test so that we can know in advance whether we can do a server side copy or not.

It might be as simple as checking the `canCopy` field in the [files resources](https://developers.google.com/drive/api/v3/reference/files#resource) - I haven't had time to experiment, so any help much appreciated :-)

**Comment by darthShadow** [comment]
This probably needs to be raised as a bug in the google issue tracker too, given that its some internal timeout that seems to be happening.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.49

**Comment by vaccarieli** [comment]
The issue is still present, i just tried the 3 latest beta, either in ubuntu  (rclonebeta_amd64.deb) and the windows version the 32bits and the 64bits, still gets stuck with those files.

**Comment by darthShadow** [comment]
@vaccarieli What do the debug logs show?

**Comment by ncw** [comment]
@vaccarieli can you still reproduce this with [the latest beta](https://beta.rclone.org)?

> The issue is still present, i just tried the 3 latest beta, either in ubuntu (rclonebeta_amd64.deb) and the windows version the 32bits and the 64bits, still gets stuck with those files.

**Comment by vaccarieli** [comment]
Here is attached the Output LOG, hope this can help.

[RCLONE OUTPUT STUCK FILES.txt](https://github.com/ncw/rclone/files/3419437/RCLONE.OUTPUT.STUCK.FILES.txt)

**Comment by darthShadow** [comment]
@vaccarieli This is the expected behaviour. Since the 750 GB upload quota has been consumed, `rclone` will simply continue retrying with greater and greater sleep intervals as visible in the last few lines.

**Comment by vaccarieli** [comment]
Am not saying the 750gb is the issue, just mentioned it because even though the logs shows 40 files are stuck, the rclone seems to be copying the rest of them, but those.

**Comment by darthShadow** [comment]
No other files seem to be copying according to the log. Its simply checking the existing files to determine what should be copied.
