### ISSUE TITLE
Does not fetch new B2 authorization token when token expires

### ISSUE THREAD

**Issue by ZacharyDuBois** [ncw/rclone#310]
Version `v1.26`
OS: Ubuntu 14.04 LTS 64bit
Command: `rclone copy ./folder b2:bucket/folder`

Issue: I was uploading ~3M files and the upload from my estimate would take 3 days. B2 auth tokens expire after 24 hours. I noticed today (started upload last night around this time) that rclone began throwing unauthorized errors because B2 expired the token and rclone ignored it.

**Comment by ncw** [comment]
Thanks for reporting that. I missed that the token expired in the docs.

**Comment by ncw** [comment]
Do you happen to know which error code backblaze returned? 401?  Or was it something else?

There isn't much of a clue in the docs

https://www.backblaze.com/b2/docs/b2_authorize_account.html

I might just fetch a new one every hour - that would probably do it.

**Comment by ZacharyDuBois** [comment]
You could do if error code != 200, get new auth token. Same with the uploads. If the upload returns anything but 200, get a new URL.

**Comment by ncw** [comment]
The actual error is

    x: Failed to copy: Failed to upload: Authorization token has expired (401 expired_auth_token)

**Comment by ncw** [comment]
I've fixed this.  It took a little while with a 24 hour test cycle! I've also fixed a number of other important B2 bugs!

Here is a beta for you to try.

http://pub.rclone.org/v1.27-41-g6b6b434%CE%B2/

Thanks for reporting the bug.

Nick

**Comment by ZacharyDuBois** [comment]
I don't have any massive uploads at the moment .-. I managed to break apart my massive upload to upload in sections. Also, I got to talk with the Backblaze CEO (Because I was hammering the B2 API with 750 concurrent uploads) and they suggest using multiple upload URLs when doing concurrent uploads.

**Comment by ncw** [comment]
See #373 for the multiple upload URLs - I've fixed that and there is a beta with that in on that issue!

**Comment by ZacharyDuBois** [comment]
Awesome! :+1:  :)

**Comment by jdeluyck** [comment]
Hello, 

Rclone 1.34, running on a raspberry pi 3 (with raspbian)

I'm currently in the progress of uploading a ton of data to B2, and unfortunately, this issue is still present.
I started rclone at [2016-11-21 19:48] (ah, don't we love logfiles)

After a bit over 24 hours, it started spouting these errors:

2016/11/22 19:59:52 data/5/50045: Failed to copy: Authorization token has expired (401 expired_auth_token)
2016/11/22 19:59:53
