### ISSUE TITLE
S3 to S3 copy ends up with TotalPartsExceeded

### ISSUE THREAD

**Issue by dkorunic** [ncw/rclone#415]
Hi,

We're doing a S3 to S3 copy with rclone and we have 2.6 GB files ending up with TotalPartsExceeded error:

2016/04/01 15:48:02 D156748_1.mp4: Failed to copy: MultipartUpload: upload multipart failed
        upload id: 2~dxDK4rkYSz7eIt40U_wqcoz6xh4oCZL
caused by: TotalPartsExceeded: exceeded total allowed configured MaxUploadParts (10000). Adjust PartSize to fit in this limit

Both S3 storage backends are Ceph/RadosGW, if that helps. Rclone being used is v1.28 (tried -v1.28-8-ga1323ebβ and v1.28-9-g9dccf91β, neither seem capable of finishing larger uploads).

Command being used is simple rclone copy s3_old:bucket s3_new:bucket. Let me know if you need full rclone -v output.

**Comment by ncw** [comment]
The max parts issue I've fixed in  a1323eb20441946bbd575012f39b6ff8b43a5c8b which is in the latest beta.

So I'm interested in working out what has gone wrong there - in what way doesn't the upload finish? 

Can you post a log with -v with the latest beta from http://pub.rclone.org ? I didn't test the beta with ceph so it is possible that something is awry there. 

Thanks

Nick

**Comment by ncw** [comment]
Here is a link to the latest beta: http://pub.rclone.org/v1.28-23-g6cc9c09%CE%B2/

I tried uploading a 2.6GB file to dreamhost (which use Ceph) and that worked fine so I think this issue is already fixed - can you confirm?

Thanks

Nick

**Comment by dkorunic** [comment]
Hi Nick, same issue still persists even with latest beta:

2016/04/04 21:59:10 D216449.mxf: Failed to copy: MultipartUpload: upload multipart failed
        upload id: 2~BWIg9rIFszTUO4mhoekjxN-wCrCOea5
caused by: TotalPartsExceeded: exceeded total allowed configured MaxUploadParts (10000). Adjust PartSize to fit in this limit

Size in question is:

2016-03-09 05:20 4176059964   s3://Video/D249101.mxf

Anything else to try?

**Comment by ncw** [comment]
Did you try the beta from the link I sent above `v1.28-23-g6cc9c09`, or a different one?

Does the same thing happen if you try copying from a local copy of the file (so local -> s3, not s3 -> s3)?

Which OS/bits are you using (eg linux 64 bit)?  I can send you a binary with some more debugging in which should help get to the bottom of this.

Thanks

Nick

**Comment by dkorunic** [comment]
Hi @ncw, I was testing with rclone-v1.28-23-g6cc9c09β-linux-amd64 version; I'll test S3 to local and then local to S3 and report back. Binary with a little more debug would definitely be appreciated, thanks!

**Comment by ncw** [comment]
I put a test binary here

http://pub.rclone.org/rclone-s3-test/

It should create some logs like this!

```
2016/04/05 15:26:17 2.6gbfile: Multpart upload size 2831155200
2016/04/05 15:26:17 2.6gbfile: PartSize initial 5242880
2016/04/05 15:26:17 2.6gbfile: PartSize is now 5242880
```

**Comment by dkorunic** [comment]
@ncw Huh. Even with -v and logging everything to file, there aren't any such strings in the output. What I get is at best:

 *                                   D211028.mxf: 99% done. avg: 1379.9, cur:    0.0 kByte/s. ETA: 0s
 *                                   D211028.mxf: 99% done. avg: 1366.0, cur:    0.0 kByte/s. ETA: 0s
 *                                   D211028.mxf: 99% done. avg: 1352.2, cur:    0.0 kByte/s. ETA: 0s
 *                                   D211028.mxf: 99% done. avg: 1338.8, cur:    0.0 kByte/s. ETA: 0s
 *                                   D211028.mxf: 99% done. avg: 1325.6, cur:    0.0 kByte/s. ETA: 0s
 *                                   D211028.mxf: 99% done. avg: 1312.7, cur:    0.0 kByte/s. ETA: 0s
 *                                   D211028.mxf: 99% done. avg: 1300.1, cur:    0.0 kByte/s. ETA: 0s
 *                                   D211028.mxf: 99% done. avg: 1287.6, cur:    0.0 kByte/s. ETA: 0s
 *                                   D211028.mxf: 99% done. avg: 1275.5, cur:    0.0 kByte/s. ETA: 0s
 *                                   D211028.mxf: 99% done. avg: 1263.5, cur:    0.0 kByte/s. ETA: 0s
 *                                   D211028.mxf: 99% done. avg: 1251.8, cur:    0.0 kByte/s. ETA: 0s
 *                                   D211028.mxf: 99% done. avg: 1240.2, cur:    0.0 kByte/s. ETA: 0s
 *                                   D211028.mxf: 99% done. avg: 1228.9, cur:    0.0 kByte/s. ETA: 0s
 *                                   D211028.mxf: 99% done. avg: 1217.8, cur:    0.0 kByte/s. ETA: 0s
 *                                   D211028.mxf: 99% done. avg: 1206.9, cur:    0.0 kByte/s. ETA: 0s
 *                                   D211028.mxf: 99% done. avg: 1196.2, cur:    0.0 kByte/s. ETA: 0s
 *                                   D211028.mxf: 99% done. avg: 1185.7, cur:    0.0 kByte/s. ETA: 0s
 *                                   D211028.mxf: 99% done. avg: 1175.3, cur:    0.0 kByte/s. ETA: 0s
 *                                   D211028.mxf: 99% done. avg: 1165.2, cur:    0.0 kByte/s. ETA: 0s
 *                                   D211028.mxf: 99% done. avg: 1155.2, cur:    0.0 kByte/s. ETA: 0s
 *                                   D211028.mxf: 99% done. avg: 1145.4, cur:    0.0 kByte/s. ETA: 0s
...
2016/04/05 19:57:57 D211028.mxf: Failed to copy: MultipartUpload: upload multipart failed
        upload id: 2~IQkBzTaPq7AVS50Dajb8UF-KiqD6asm
caused by: TotalPartsExceeded: exceeded total allowed configured MaxUploadParts (10000). Adjust PartSize to fit in this limit
2016/04/05 19:57:57 D211028.mxf: Removing failed copy

or similar:

 *                                   D176573.mxf: 98% done. avg:  208.9, cur:    0.0 kByte/s. ETA: 0s
 *                                   D176573.mxf: 98% done. avg:  205.7, cur:    0.0 kByte/s. ETA: 0s
 *                                   D176573.mxf: 98% done. avg:  202.6, cur:    0.0 kByte/s. ETA: 0s
 *                                   D176573.mxf: 98% done. avg:  199.5, cur:    0.0 kByte/s. ETA: 0s
 *                                   D176573.mxf: 98% done. avg:  196.6, cur:    0.0 kByte/s. ETA: 0s
 *                                   D176573.mxf: 98% done. avg:  193.7, cur:    0.0 kByte/s. ETA: 0s
 *                                   D176573.mxf: 98% done. avg:  191.0, cur:    0.0 kByte/s. ETA: 0s
 *                                   D176573.mxf: 98% done. avg:  188.3, cur:    0.0 kByte/s. ETA: 0s
 *                                   D176573.mxf: 98% done. avg:  185.7, cur:    0.0 kByte/s. ETA: 0s
 *                                   D176573.mxf: 98% done. avg:  183.1, cur:    0.0 kByte/s. ETA: 0s
 *                                   D176573.mxf: 98% done. avg:  180.6, cur:    0.0 kByte/s. ETA: 0s
 *                                   D176573.mxf: 98% done. avg:  178.2, cur:    0.0 kByte/s. ETA: 0s
 *                                   D176573.mxf: 98% done. avg:  175.9, cur:    0.0 kByte/s. ETA: 0s
 *                                   D176573.mxf: 98% done. avg:  173.6, cur:    0.0 kByte/s. ETA: 0s
 *                                   D176573.mxf: 98% done. avg:  171.4, cur:    0.0 kByte/s. ETA: 0s
 *                                   D176573.mxf: 98% done. avg:  169.2, cur:    0.0 kByte/s. ETA: 0s
 *                                   D176573.mxf: 98% done. avg:  167.1, cur:    0.0 kByte/s. ETA: 0s
 *                                   D176573.mxf: 98% done. avg:  165.0, cur:    0.0 kByte/s. ETA: 0s
 *                                   D176573.mxf: 98% done. avg:  163.0, cur:    0.0 kByte/s. ETA: 0s
 *                                   D176573.mxf: 98% done. avg:  161.0, cur:    0.0 kByte/s. ETA: 0s
 *                                   D176573.mxf: 98% done. avg:  159.1, cur:    0.0 kByte/s. ETA: 0s
...
2016/04/05 20:25:17 D176573.mxf: Failed to copy: MultipartUpload: upload multipart failed
        upload id: 2~IQJmqAGSijxX6ldZWRRK68dShmnKM80
caused by: TotalPartsExceeded: exceeded total allowed configured MaxUploadParts (10000). Adjust PartSize to fit in this limit
2016/04/05 20:25:17 D176573.mxf: Removing failed copy

The set of parameters and arguments I'm using rclone with is fairly trivial:

./rclone -v --checkers 40 --no-gzip-encoding --retries 1 --transfers 60 --quiet sync store1_s3:Video store2_s3:Video

Any ideas?

**Comment by ncw** [comment]
Remove the `--quiet` and you should see the logs

**Comment by ncw** [comment]
Some other things to try - try with `--transfers 1` and see if that makes a difference.  You could also try with `--transfers 1 --dump-headers` which will make a lot of logs but you'll see exactly how big each chunk is and how many of them there are.

**Comment by dkorunic** [comment]
Debug information seems to indicate that PartSize stays at 5M:

```
2016/04/06 12:56:19 D210117.mp4: Multpart upload size 128299761
2016/04/06 12:56:19 D210117.mp4: PartSize initial 5242880
2016/04/06 12:56:19 D210117.mp4: PartSize is now 5242880
```

[ and a little bit later ]

```
Transferring:
 *                                   D210117.mp4: 20% done. avg:   12.8, cur:    0.0 kByte/s. ETA: 0s
 *                                   D236873.mp4: 95% done. avg:   57.8, cur:    0.0 kByte/s. ETA: 0s
2016/04/06 13:29:45 D210117.mp4: Failed to copy: MultipartUpload: upload multipart failed
        upload id: 2~shxOWpvPiA2QnPk5Rmyn5HoxmmejrHN
caused by: TotalPartsExceeded: exceeded total allowed configured MaxUploadParts (10000). Adjust PartSize to fit in this limit
2016/04/06 13:29:45 D210117.mp4: Removing failed copy
```

I can also confirm that, judging from the log, PartSize was never increased above 5M (aka the default value).

**Comment by ncw** [comment]
That is interesting information thank you. 128299761. / 5242880 = 24.47123737335205 which is a lot less that 10,000, indicating that 5M for partsize should be just fine.  However somehow we read 1000 parts from that file.

Is `D210117.mp4`  128,299,761 bytes long = 122 MBytes? If somehow rclone has the size wrong at that point then that would explain a lot of things!  It fits in with all the `99%` you put in your log above too.

Does `rclone lsl store1_s3:Video/D210117.mp4` agree that the size is 128,299,761 bytes?

Can you try just transferring a single file like this

```
./rclone --dump-headers  -v --checkers 1 --no-gzip-encoding --retries 1 --transfers 1 copy store1_s3:Video/D210117.mp4 store2_s3:Video
```

and see if it still reproduces the problem.  If it does can you send me the output (direct to nick@craig-wood.com is probably best).  You might want to remove the `Authorization:` lines.

If that doesn't reproduce the problem then try your normal sync with `--dump-headers` and send me the log.

Thanks for your help - hopefully we are getting somewhere now

Nick

**Comment by dkorunic** [comment]
The size is exactly 122 MB (128299761 bytes), and lsl and ls both agree about the size as well as regular s3cmd ls). I'll transfer just one file and send the output to your email ASAP. Thanks for your time!

**Comment by ncw** [comment]
> The size is exactly 122 MB (128299761 bytes), and lsl and ls both agree about the size as well as regular s3cmd ls).

That is relief!  There is something strange going on, but not that is good!

> I'll transfer just one file and send the output to your email ASAP. Thanks for your time!

Thanks and no problems

**Comment by dkorunic** [comment]
I'll comment here and email logs directly -- after getting correct Content-Length of 128299761 from the source, and getting 404 from the destination, it ended up uploading over and over, up to 4804 parts and still counting.

**Comment by ncw** [comment]
What seems to have happened is that it reads 5 x 5 MB chunks, then one chunk of 315 bytes and then all the chunks it reads after that are 0 bytes long.

This is clearly a bug, but in exactly what I'm not sure!

Can you download that file correctly using rclone, eg

```
./rclone --dump-headers  -v --checkers 1 --no-gzip-encoding --retries 1 --transfers 1 copy store1_s3:Video/D210117.mp4 /tmp/Video
```

If that downloads correctly then it is pointing the finger at the S3manager code which is part of the amazon go library for accessing s3.  If it doesn't then it is pointing the finger at the ceph server itself.

**Comment by ncw** [comment]
As well as the above, can you try this rclone: http://pub.rclone.org/rclone-s3-test2/

This has a fix to the S3manager code I mentioned.  I think what will happen is that it will return an error "Unexpected end of file", or rclone will complain about a corrupted upload.

I'm pretty sure that your download will be truncated when you try the download above which is a problem with the ceph server itself I think.

Thank you very much for your help

Nick

**Comment by dkorunic** [comment]
Hi Nick,

It's exactly how it's happening now and IMO, it's much better solution as it doesn't loop unnecessarily on the source S3 (and we're able to move on with the copying other files much faster). From what I'm seeing on Ceph/S3, some downloads are being EOF-ed from the Ceph due to corruption but the behaviour now is also consistent with s3cmd too (EOF on error). Thanks for your time and patience!

**Comment by ncw** [comment]
I'm glad we've got to the bottom of that - thank you very much for your help.

I've submitted a fix for the s3manager upstream here: aws/aws-sdk-go#620

Which should make it into the next rclone release.

**Comment by dkorunic** [comment]
Awesome work, thanks a lot!

**Comment by ncw** [comment]
This patch has been merged upstream and the fix will be in the next  binary release.

Thanks for your help

Nick
