### ISSUE TITLE
b2: large files support

### ISSUE THREAD

**Issue by hajes** [ncw/rclone#456]
I recently uploaded large video files to Backblaze but failed with following error.

`Failed to copy: Failed to upload: file size too big: 8046431535 (400 bad_request)`

I asked Backblaze guys and there is their reply

> Rclone does not currently support our Large File API calls. So either support for large files will need to be added, or the file will need to be broken up into smaller chunks prior to upload.

I found similar thread and thought it is resolved [https://github.com/ncw/rclone/issues/298#issuecomment-214501923](url)

------------------------------------------------------
rclone 1.29

Mac OS X 10.9.5

Backblaze B2

**Comment by ncw** [comment]
I'll do this as part of making rclone an official B2 integration

**Comment by i2plover** [comment]
Has this been added? Support for Large files

**Comment by ncw** [comment]
@i2plover not yet, sorry but it is on the list for the next release :-)

**Comment by i2plover** [comment]
@ncw Okay good :) Because I REALLY need this added. I need to backup my servers with it to B2, but the tar files are way over allowed size, so need the Large File support added.

**Comment by i2plover** [comment]
Any progress on this? Really really needing it :+1:

**Comment by mdeboer** [comment]
+1 on this one! 👍

**Comment by i2plover** [comment]
Really needing this :)

**Comment by Sneagan** [comment]
I need this as well. Is there a branch we can pull and take a look/help?

**Comment by ncw** [comment]
I'm intending to do this and submit rclone for b2 integration soon, however events keep catching up with me!

Any help would be much appreciated, so if anyone wants to help I can give pointers.

**Comment by ZacharyDuBois** [comment]
I'd love to see this too :)

**Comment by ncw** [comment]
Here is the first attempt at large file support. Any files over 5GB it will upload in chunks.  You can set the threshold for chunk uploading with `--b2-upload-cutoff` and the size of chunks with `--b2-chunk-size`.  Note that the chunks are buffered in memory so don't make them too big!  96M is the default (the minimum is 100,000,000 bytes).

You can test with files < 5GB by using `--b2-upload-cutoff 100M` say.

http://pub.rclone.org/v1.29-1-gbb75d80-58-g8139881%CE%B2/

Interested in any feedback - send a log file with `-v` if you find a problem!

Thanks

Nick

**Comment by mdeboer** [comment]
Thanks @ncw for rolling out this feature. I'll give this a try and report back!

**Comment by ncw** [comment]
@mdeboer thanks for testing!  Yes the large file upload is single threaded at the moment.  I'll make it multi threaded in another ticket - #531.  I wanted to make it work first before making it super fast!

rclone is capable of uploading many large files at once though (see `--transfers` flag).

A 503 error should cause it to retry the chunk as you've discovered.

This code will be in the 1.30 release which will be shortly

**Comment by ZacharyDuBois** [comment]
Woot! Sorry I wasn't much help (Been busy). I have subscribed to #531 for later use. Also, B2 recommends uploading files to multiple different upload URLs. You may want to talk to them about that.

**Comment by ncw** [comment]
@ZacharyDuBois No problems!  B2 now enforce a different upload URL per thread and rclone does that already :-)

**Comment by ZacharyDuBois** [comment]
I more so apply this to the bulk upload of smaller files (IE a whole directory or so). They said it is more efficient and better practice to use multiple upload URLs in a ticket they opened with me because my server was transferring (with rclone) using ~500-700 threads and they said it was hitting one upload URL.

**Comment by ncw** [comment]
@ZacharyDuBois rclone did that at one point but I fixed that a version or two ago.  Do you remember which version that was?

**Comment by ncw** [comment]
@ZacharyDuBois This was fixed in 6b6b43402b14a607695d9c05bff643c1837c81ea which was released in v1.28 so I'd be interested if you were using an earlier version to that or whether it is broken!

**Comment by ZacharyDuBois** [comment]
Not sure what I was running then - regardless they really need a better API. I'm just one person and I feel as if I am the only one to give them any feedback yet lol

**Comment by hajes** [comment]
there seems to be something wrong with large files support again. I used to have v1.30, tried latest version 1.32 and problem still there

simple command `rclone copy -vuc`

all was ok with `--b2-upload-cutoff 1G`

This week, I wanted to backup my video files ranging from 2 to 5GB. All files up to 4GB are without problem. Anything larger, rclone copy files with 0kBs

rclone v1.32 adds upload cutoff automatically I believe. My internet connection is able to upload 40-70GB/day...10GB of large files are uploaded whole week and nothing done.

It looks like B2 changed something because old strategy doesn't work anymore

**Comment by ncw** [comment]
@hajes sorry to hear that.  Can you make a new issue with a log with `-v` of it happening please?

Thanks

Nick

**Comment by hajes** [comment]
sometimes it shows funny speed numbers

there seems to be no apparent error. I see upload speed 1.2MB/s but it takes ages.

from screenshots...you can see 0kB/s then 15MBs (my official shared upload speed is 10Mbps/1.2MBs but sometimes goes to 2MBs). With such a speed, it would be already done in few hours.

Size of folder is 77GB...that's 1-2days max...it runs since last weekend and it is not done

[log.txt.zip](https://github.com/ncw/rclone/files/367224/log.txt.zip)
![screenshot 2016-07-16 09 57 11](https://cloud.githubusercontent.com/assets/18664079/16894385/1c1b39d4-4b55-11e6-9505-485bf7b6b4f7.png)


![screenshot 2016-07-16 12 56 48](https://cloud.githubusercontent.com/assets/18664079/16894386/1c69376a-4b55-11e6-8d7a-34556ba01bd9.png)

**Comment by hajes** [comment]
no Mac OS X upgrades, no new SW installed

all same since last successful B2 uploads

v1.32 didn't help because it is basically v1.3 with automatic B2 upload cutoff

**Comment by ncw** [comment]
@hajes can you stick that in an new issue please?
