### ISSUE TITLE
replace slashes and other special characters in file names

### ISSUE THREAD

**Issue by lvmm** [ncw/rclone#62]
I've got a file named "Call Log Export: 01/13/15 - 04/21/15". rclone syncs it successfully but treats slashes as directory separators and creates a long path with data in the file called '15'. Native windows google drive replaces special characters with underscores and creates a file named "Call Log Export_ 01_13_15 - 04_21_15" instead. Somehow I like this approach better.

**Comment by ncw** [comment]
You can have any characters at all in a drive file name.

There are quite a few characters you can't have in a windows file name ([see ms docs for more info](https://msdn.microsoft.com/en-us/library/aa365247))

Linux/OS X are much more forgiving - it is only `/` and NUL that you can't have in a file name.

One thing I could do is map the forbidden characters to unicode equivalents, eg I could map `/` to the unicode division slash which looks pretty similar and is allowed in filesystems.

```
/ => ∕
```

Or I could just replace all characters which can't be represented on the current filing system with `_` which would give the same result as the google drive sync.

This would mean making each fs declare which characters it couldn't deal with (or possibly whole names as (for example) `con` is an invalid file name in windows)

**Comment by lvmm** [comment]
If you want to suit everyone, make it configurable. I personally go for a more restrictive MS-style limitations - being able to create a file with a colon is great until you have to copy it to a FAT USB stick.

**Comment by ncw** [comment]
This was partially fixed in f50f353b5d7e76d8f666ac1383f5c23021b6ea34 the `:` gets escaped as `_` for windows file systems.

The path separators `/` are still an issue though - this needs to be fixed in the drive code.

**Comment by balazer** [comment]
There's an issue with the syncing of files named with a colon from Google Drive to Windows.  If the file already exists in Windows, the sync operation will delete it.

`rclone -v sync remote:test f:\test`

> F:\>rclone -v sync remote:test test
2017/02/25 12:07:06 rclone: Version "v1.35-40-gb6848a3ß" starting with parameters ["rclone" "-v" "sync" "remote:test" "test"]
2017/02/25 12:07:06 Local file system at \\?\F:\test: Modify window is 1ms
2017/02/25 12:07:06 Google drive root 'test': Reading ""
2017/02/25 12:07:07 Google drive root 'test': Finished reading ""
2017/02/25 12:07:07 Local file system at \\?\F:\test: Waiting for checks to finish
2017/02/25 12:07:07 Local file system at \\?\F:\test: Waiting for transfers to finish
2017/02/25 12:07:07 Local file system at \\?\F:\test: Replacing invalid characters in "\\test\\test: name" to "\\\\?\\F:\\test\\test_ name"
2017/02/25 12:07:07 test: name: Copied (new)
2017/02/25 12:07:07 Waiting for deletions to finish
2017/02/25 12:07:07 test_ name: Deleted
2017/02/25 12:07:07
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 1
Transferred:            1
Elapsed time:        1.3s
2017/02/25 12:07:07 Go routines at exit 7

**Comment by ncw** [comment]
I'm planning to fix all this properly for 1.37

**Comment by tst2005** [comment]
FYI, an other software replace the "/" by "%2F"

**Comment by aldones** [comment]
google-drive-ocamlfuse replaced "/" by "_", which sounds pretty good to me.
Having to mix it with rclone for thing to work at this point, with mixed results (since google-drive-ocamlfuse is a bit buggy, not to mention slow).

I tried looking at the rclone source code, with no success. Golang is absolutely new to me, and I'm an old C/GCC programmer. Despite my best intentions, I've been unable to even track the code to the point where it is breaking.

**Comment by ncw** [comment]
@aldones I have a plan to fix all of this which will probably take some time to implement!

In the mean time I'd replace `/` with `／` which is Unicode Character 'FULLWIDTH SOLIDUS' (U+FF0F) then I can make these transforms reversible.

Go is really easy to pick up for C programmers - the major thing that takes getting used to is the type declarations are backwards.  [The go tour](https://tour.golang.org/) is an excellent place to start for experienced programmers.  I think of Go as being mostly a super C with no memory management, closures and great concurrency.

To change this in `drive/drive.go` would do  `/` to   `／` in the `ListDir` function where it says `remote := job.Path + item.Title` (just change `item.Title`) and  `／` to `/` in the two places where `&Object{}`s are created.  So adding 3 [strings.Replace](https://golang.org/pkg/strings/#Replace) would do it probably!

**Comment by aldones** [comment]
I tried adding these 3 strings.Replace. A "lsd" on the drive root will show me the directory name with the / replaced by  U+FF0F. Unfortunately, it won't work past that. Even a "lsd" on the specific directory, either with / or with U+FF0F will return "directory not found."

I will keep tinkering, but I guess I will just have to wait for the official fix.

Thank you for your attention. I will check that Tour, and see that happens.

**Comment by lechup** [comment]
@aldones can You link You repo where You are trying to fix this?

My attempt is here: https://github.com/lechup/rclone/commit/19191b82f369544f7713a549048bb84977a52109

**Comment by aldones** [comment]
@lechup I don't have a github repo. But here is the unified diff:


[drive.go.diff.txt](https://github.com/ncw/rclone/files/1064469/drive.go.diff.txt)

**Comment by lechup** [comment]
@aldones I've updated my repo with Your diff, `rclone ls ` seems to work but still prints `/` instead of `／`, hm...

https://github.com/lechup/rclone/commit/257a20a0e11b921940e4b18b8be4e44914e8e57f

**Comment by ncw** [comment]
Looking at this again I think there is only one place that needs patching as all the `item.Title`s ultimately come from the `list()` function.  This should fix the can't find the directory problems too.

Untested:

```patch
diff --git a/drive/drive.go b/drive/drive.go
index 3a8aa0f1..32f92a7e 100644
--- a/drive/drive.go
+++ b/drive/drive.go
@@ -273,6 +273,7 @@ OUTER:
 			return false, errors.Wrap(err, "couldn't list directory")
 		}
 		for _, item := range files.Items {
+			item.Title = strings.Replace(item.Title, '/', '／', -1)
 			if fn(item) {
 				found = true
 				break OUTER
```

**Comment by lechup** [comment]
@ncw Thanks for invastigating it once again, I've applied Your patch, but still can't get it work....

Should all paths (dir and file names) be renamed in all functions so `parter/parter.png` file should be listed as `parter／parter.png` while using `ls` command and `test/test` directory should be listed as `test／test` directory while using `lsd` command?

```
lechup@lechup-ubuntu:~/gocode/src/rclone$ make clean
go clean ./...
find . -name \*~ | xargs -r rm -f
rm -rf build docs/public
rm -f rclone rclonetest/rclonetest
lechup@lechup-ubuntu:~/gocode/src/rclone$ make
touch fs/version.go
go install -v --ldflags "-s -X github.com/ncw/rclone/fs.Version=v1.36-167-g775f82d4-google_drive_slash_fix2" 
cp -av `go env GOPATH`/bin/rclone .
'/home/lechup/gocode/bin/rclone' -> './rclone'
lechup@lechup-ubuntu:~/gocode/src/rclone$ ./rclone lsd Asia2:/Test
          -1 2017-06-20 11:37:29        -1 test/test
lechup@lechup-ubuntu:~/gocode/src/rclone$ ./rclone ls Asia2:/Test
  1238946 parter/parter.png
lechup@lechup-ubuntu:~/gocode/src/rclone$ ./rclone --version
rclone v1.36-167-g775f82d4-google_drive_slash_fix2
```

Interestingly sync to local works but not as expected:
```
lechup@lechup-ubuntu:~/gocode/src/rclone$ ./rclone sync -v Asia2:/ ~/test/
lechup@lechup-ubuntu:~$ tree test
test
└── parter
    └── parter.png
```

expected:
```
test
└── parter／parter.png
```

PS: Just thinking, is dircache related stuff revelant here and could cause some glitches? Maybe is there any command to clear it?
PS2: If You want I can send You rclone config so You could test it Yourself without setting up Google Account.

**Comment by ncw** [comment]
I have done a revised patch which I have actually bothered to test this time!

Please try the binary here

https://pub.rclone.org/v1.36-199-g89d5491a-drive-slash%CE%B2/

(or on drive-slash branch)

It seems to work for me!

```
$ rclone ls drive:slash_test/
       92 z／slash
       92 has／slash/z

$ rclone ls drive:slash_test/has／slash
       92 z

$ rclone sync drive:slash_test /tmp/slash_test

$ tree /tmp/slash_test/
/tmp/slash_test/
├── has／slash
│   └── z
└── z／slash
```

What do you think?

**Comment by lechup** [comment]
@ncw thanks! it looks like it is working now, I'll test it on my end on bigger set of files.

Does this branch need some tests to get into master? https://github.com/ncw/rclone/compare/drive-slash

**Comment by ncw** [comment]
I've merged this to master now - you can find it here

https://beta.rclone.org/v1.36-209-gb44d0ea0/ (uploaded in 15-30 mins)

In an idea world this would have tests, but I only have integration tests for each remote and this doesn't fit into the framework.

**Comment by aldones** [comment]
Oh, don't worry. I will test the *&@#($ out of it. 
Will do my best to break it, and report back as soon as it either break, or I give up and we can claim a win.

Thank you.

**Comment by aldones** [comment]
So far, no luck breaking it. Working as expected, thank you.

One other thing I noticed regarding the drive code, is for directories ending in one or more spaces. The Google Drive Windows App will replace the ending spaces with "_", because Windows doesn't like directories ending in blank spaces. For Linux, it doesn't matter.

Maybe this is something that might be changed also, in the future? Compared to the "/" bug, now fix, this is very minor, since this other bug needs 2 things to trigger: the directory ending in 1 or more spaces, and rclone running on Windows, but, anyway, might be something to consider.

Anyway, I just moved the fbv44d0ea0 to my production environment, and lets see if it holds or breaks in the next few days.

Once again, thank you.

**Comment by nsuper** [comment]
rclone can't upload with filename contains `ầ & ề`

```
ầ & ề
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        1.2s
```

**Comment by ncw** [comment]
@nsuper rclone only transfers UTF-8 encoded filenames - check out the section in the docs about [filename encoding](https://rclone.org/local/#filenames).

**Comment by nsuper** [comment]
@ncw Thank you for your support. But `convmv` said `already UTF-8: /home/ubuntu/test/ầề`

```
~$ convmv -f UTF-16 -t utf8 -i '/home/ubuntu/test/   ầềm'
Starting a dry run without changes...
Skipping, already UTF-8: /home/ubuntu/test/   ầềm
No changes to your files done. Would have converted 0 files in 0 seconds.
Use --notest to finally rename the files.
```

How to get rclone full log to ensure rclone can read this file? Verbose mode is not enough.

Linux `file` command can read this file. Python, NodeJS can, only rclone can't :(

**Comment by ncw** [comment]
@nsuper thanks for checking the UTF-8 encoding.

I didn't manage to replicate this.

```
$ cd /tmp/
$ mkdir t2
$ cd t2
$ echo hello > 'ầ & ề'
$ ls
ầ & ề
$ cd ..
$ rclone copy -vv t2 drive:issue-62
2017/07/02 15:53:36 DEBUG : rclone: Version "v1.36-DEV" starting with parameters ["rclone" "copy" "-vv" "t2" "drive:issue-62"]
2017/07/02 15:53:36 DEBUG : drive: Saved new token in config file
2017/07/02 15:53:38 INFO  : Google drive root 'issue-62': Modify window is 1ms
2017/07/02 15:53:38 INFO  : Google drive root 'issue-62': Waiting for checks to finish
2017/07/02 15:53:38 INFO  : Google drive root 'issue-62': Waiting for transfers to finish
2017/07/02 15:53:41 INFO  : ầ & ề: Copied (new)
2017/07/02 15:53:41 INFO  : 
Transferred:      6 Bytes (1 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:        4.2s

2017/07/02 15:53:41 DEBUG : Go routines at exit 8
2017/07/02 15:53:41 DEBUG : rclone: Version "v1.36-DEV" finishing with parameters ["rclone" "copy" "-vv" "t2" "drive:issue-62"]
$ rclone ls drive:issue-62
        6 ầ & ề
$ 
```

Can you open a new issue please with a similar test script to the above showing the problem please?

**Comment by ncw** [comment]
@aldones - thanks for the note about directories ending in spaces on Windows - I didn't know that.  I've added that to #1477 where I'm thinking about such things.

**Comment by nsuper** [comment]
@ncw - I think it's a bug. 
Passed if upload a directory. 
Failed if upload single file!

- Upload a directory test/
```
rclone copy -c -vv /home/ubuntu/test drive:test2
2017/07/02 11:35:14 DEBUG : rclone: Version "v1.36-DEV" starting with parameters ["/home/ubuntu/bin/rclone" "copy" "-c" "-vv" "/home/ubuntu/test" "drive:test2"]
2017/07/02 11:35:15 INFO  : Google drive root 'test2': Modify window is 1ms
2017/07/02 11:35:15 INFO  : Google drive root 'test2': Waiting for checks to finish
2017/07/02 11:35:15 INFO  : Google drive root 'test2': Waiting for transfers to finish
2017/07/02 11:35:17 INFO  :    ầềm: Copied (new)
Transferred:   4.451 MBytes (1.165 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:        3.8s
```

- Upload a file: test/    ầềm
```
rclone copy -c -vv '/home/ubuntu/test/    ầềm' drive:test3
2017/07/02 11:39:59 DEBUG : rclone: Version "v1.36-DEV" starting with parameters ["/home/ubuntu/bin/rclone" "copy" "-c" "-vv" "/home/ubuntu/test/   ầềm" "drive:test3"]
2017/07/02 11:40:00 INFO  : Google drive root 'test3': Modify window is 1ms
2017/07/02 11:40:00 DEBUG :    ầềm: Excluded from sync (and deletion)
2017/07/02 11:40:00 INFO  : Google drive root 'test3': Waiting for checks to finish
2017/07/02 11:40:00 INFO  : Google drive root 'test3': Waiting for transfers to finish
2017/07/02 11:40:00 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        1.1s
```

**Comment by ncw** [comment]
@nsuper I can replicate that - can you make a new issue with that info in please!

**Comment by nsuper** [comment]
@ncw FYI #1515
