### ISSUE TITLE
Can't upload data using ACD and rclone mount (FUSE)

### ISSUE THREAD

**Issue by clanstyles** [ncw/rclone#669]
When filing an issue, please include the following information if
possible as well as a description of the problem.  Make sure you are
using the [latest version of rclone](http://rclone.org/downloads/).

> What is your rclone version (eg output from `rclone -V`)
> rclone v1.33
> 
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
> centos 7
> 
> Which cloud storage system are you using? (eg Google Drive)
> Amazon Cloud Drive
> 
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
> ./rclone mount amazon:/ ~/rclone-v1.33-linux-amd64/mnt/ --debug-fuse -v
> 
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
> 2016/09/01 01:39:00 &{0xc420192730 TestData/README.html}: Error detected after finished upload - waiting to see if object was uploaded correctly: Post https://content-na.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: http: ContentLength=436 with Body length 187028
> 2016/09/01 01:39:00 &{0xc420192730 TestData/README.html}: Object not found - waiting (1/24)
> 2016/09/01 01:39:00 fuse: <- Interrupt [ID=0xe Node=0x0 Uid=0 Gid=0 Pid=0] ID 0xd
> 2016/09/01 01:39:00 fuse: -> [ID=0xe] Interrupt
> 2016/09/01 01:39:05 &{0xc420192730 TestData/README.html}: Object not found - waiting (2/24)
> 2016/09/01 01:39:10 &{0xc420192730 TestData/README.html}: Object not found - waiting (3/24)
> 2016/09/01 01:39:15 &{0xc420192730 TestData/README.html}: Object not found - waiting (4/24)
> 2016/09/01 01:39:20 &{0xc420192730 TestData/README.html}: Object not found - waiting (5/24)
> 2016/09/01 01:39:25 &{0xc420192730 TestData/README.html}: Object not found - waiting (6/24)
> 2016/09/01 01:39:30 &{0xc420192730 TestData/README.html}: Object not found - waiting (7/24)
> 2016/09/01 01:39:35 &{0xc420192730 TestData/README.html}: Object not found - waiting (8/24)
> 2016/09/01 01:39:40 &{0xc420192730 TestData/README.html}: Object not found - waiting (9/24)
> 2016/09/01 01:39:46 &{0xc420192730 TestData/README.html}: Object not found - waiting (10/24)
> 2016/09/01 01:39:51 &{0xc420192730 TestData/README.html}: Object not found - waiting (11/24)
> 2016/09/01 01:39:56 &{0xc420192730 TestData/README.html}: Object not found - waiting (12/24)
> 2016/09/01 01:40:01 &{0xc420192730 TestData/README.html}: Object not found - waiting (13/24)
> 2016/09/01 01:40:06 &{0xc420192730 TestData/README.html}: Object not found - waiting (14/24)
> 2016/09/01 01:40:11 &{0xc420192730 TestData/README.html}: Object not found - waiting (15/24)
> 2016/09/01 01:40:16 &{0xc420192730 TestData/README.html}: Object not found - waiting (16/24)
> 2016/09/01 01:40:21 &{0xc420192730 TestData/README.html}: Object not found - waiting (17/24)
> 2016/09/01 01:40:26 &{0xc420192730 TestData/README.html}: Object not found - waiting (18/24)
> 2016/09/01 01:40:31 &{0xc420192730 TestData/README.html}: Object not found - waiting (19/24)
> 2016/09/01 01:40:36 &{0xc420192730 TestData/README.html}: Object not found - waiting (20/24)
> 2016/09/01 01:40:42 &{0xc420192730 TestData/README.html}: Object not found - waiting (21/24)
> 2016/09/01 01:40:47 &{0xc420192730 TestData/README.html}: Object not found - waiting (22/24)
> 2016/09/01 01:40:52 &{0xc420192730 TestData/README.html}: Object not found - waiting (23/24)
> 2016/09/01 01:40:57 &{0xc420192730 TestData/README.html}: Object not found - waiting (24/24)
> 2016/09/01 01:41:02 &{0xc420192730 TestData/README.html}: Finished waiting for object - returning original error: Post https://content-na.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: http: ContentLength=436 with Body length 187028
> 2016/09/01 01:41:02 TestData/README.html: WriteFileHandle.Flush error: Post https://content-na.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: http: ContentLength=436 with Body length 187028
> 2016/09/01 01:41:02 fuse: -> [ID=0xd] Flush error=EIO: Post https://content-na.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: http: ContentLength=436 with Body length 187028

**Comment by ncw** [comment]
I'm away at the moment - will investigate further next week. 

However I have a nasty feeling that uploads don't work with ACD via fuse because they need to know the file size in advance.

**Comment by ncw** [comment]
Yes I've confirmed this - you can't upload files to ACD with `rclone mount`. :-(  This is rather complicated to fix unfortunately - it might just be easier it I add a flag so rclone mount uses a temporary file for the upload.

**Comment by fjramons** [comment]
I am experiencing a quite similar issue with fuse mount, but the behaviour seems to depend on the operating system. In Ubuntu 14.04, fuse mount works fine (I can create or copy files without apparent restrictions), while fuse mount in Raspbian Jessie behaves as if it were a read-only filesystem. In both systems rclone copy/sync are working properly.

**Comment by Njcki** [comment]
Same issue here.
```
$ rclone -V
rclone v1.33-105-gd1080d5β
```

```
$ cp twrp_z00a_v24_repack.img ~/acd/
cp: impossibile creare il file regolare '/home/niccolo/acd/twrp_z00a_v24_repack.img': Errore di input/output
```

Hope you will fix it soon, meanwhile i'm going to use acd_cli to upload.

**Comment by breunigs** [comment]
Hm, I guess I *must* be missing something here. AmazonDrive does not require the size to be known in advance, apart from the "files over 12 GB might not work" check. Using this rather simple patch, I can do the following:

```
stefan@aard ~/code/gocode/src/github.com/ncw/rclone $ cp /opt/rclone ~/acd/                                            
stefan@aard ~/code/gocode/src/github.com/ncw/rclone $ md5sum /opt/rclone                                               
505cfe704e2f7faf5b84104e86f68323  /opt/rclone
stefan@aard ~/code/gocode/src/github.com/ncw/rclone $ md5sum ~/acd/rclone                                               
505cfe704e2f7faf5b84104e86f68323  /home/stefan/acd/rclone
stefan@aard ~/code/gocode/src/github.com/ncw/rclone $ rm ~/acd/rclone                                                  
stefan@aard ~/code/gocode/src/github.com/ncw/rclone $ cat /opt/rclone > ~/acd/rclone                                   
stefan@aard ~/code/gocode/src/github.com/ncw/rclone $ md5sum ~/acd/rclone                                              
505cfe704e2f7faf5b84104e86f68323  /home/stefan/acd/rclone
```

Overwriting doesn't work yet, but I haven't checked where this issue stems from. I first wanted to know what other problems you had in mind that would make write support complicated before fixing any of the probably simple bugs?

The patch is simply explained: instead of relying on `src` to give us a size, it simply checks if at least one byte can be read. The `PutSized` is only needed to create 0-byte files anyway.

```
diff --git a/amazonclouddrive/amazonclouddrive.go b/amazonclouddrive/amazonclouddrive.go
index 2a4d1a9..61ffde7 100644
--- a/amazonclouddrive/amazonclouddrive.go
+++ b/amazonclouddrive/amazonclouddrive.go
@@ -13,6 +13,7 @@ we ignore assets completely!
 */
 
 import (
+ "bytes"
        "encoding/json"
        "fmt"
        "io"
@@ -590,10 +591,14 @@ func (f *Fs) Put(in io.Reader, src fs.ObjectInfo) (fs.Object, error) {
        err = f.pacer.CallNoRetry(func() (bool, error) {
                start := time.Now()
                f.startUpload()
-           if src.Size() != 0 {
-                   info, resp, err = folder.Put(in, leaf)
-           } else {
+
+         buf := make([]byte, 1)
+         n, readErr := in.Read(buf)
+         if n == 0 && readErr == io.EOF {
                        info, resp, err = folder.PutSized(in, size, leaf)
+         } else {
+                 in = io.MultiReader(bytes.NewReader(buf), in)
+                 info, resp, err = folder.Put(in, leaf)
                }
                f.stopUpload()
                var ok bool
```

**Comment by ncw** [comment]
This should be fixed in http://beta.rclone.org/v1.34-22-g0b562bc/ (will be uploaded in 15-30 mins)

Please re-open if it doesn't work for you.

**Comment by clanstyles** [comment]
Upload works, the fuse mounts don't have any data in them. You can see them uploaded to amazon though.

**Comment by KarlDag** [comment]
Still an issue for me. I can mount my drive no issue, but when I try to copy a file to it I get the message "The item “Family photo” can’t be copied because there isn’t enough free space." The file is shown locally on my mount, but 0kb...

What is your rclone version (eg output from rclone -V)
rclone v1.34 (installed latest 1.34 beta, didn't change anything)

Which OS you are using and how many bits (eg Windows 7, 64 bit)
MacOS Sierra up-to-date

Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive

The command you were trying to run (eg rclone copy /tmp remote:tmp)
 rclone mount -v Amazon:/Videos/ ~/Users/myname/Desktop/


Log: 2016/12/31 14:33:07 rclone: Version "v1.34" starting with parameters ["rclone" "mount" "-v" "Amazon:/Videos/" "/Users/karldagenais/Users/karldagenais/Desktop/"]
2016/12/31 14:33:08 amazon drive root 'Videos': Modify window not supported
2016/12/31 14:33:08 amazon drive root 'Videos': Mounting on "/Users/karldagenais/Users/karldagenais/Desktop/"
2016/12/31 14:33:08 amazon drive root 'Videos': Root()
2016/12/31 14:33:08 : Dir.Attr
2016/12/31 14:33:14 .hidden: Dir.Lookup
2016/12/31 14:33:14 : Reading directory
2016/12/31 14:33:14 amazon drive root 'Videos': Reading ""
2016/12/31 14:33:15 amazon drive root 'Videos': Finished reading ""
2016/12/31 14:33:15 : Dir.ReadDirAll
2016/12/31 14:33:15 : Dir.ReadDirAll OK with 3 entries
2016/12/31 14:33:15 Plex Series: Dir.Lookup
2016/12/31 14:33:15 Plex Series: Dir.Lookup OK
2016/12/31 14:33:15 Plex Series: Dir.Attr
2016/12/31 14:33:15 Plex Movies: Dir.Lookup
2016/12/31 14:33:15 Plex Movies: Dir.Lookup OK
2016/12/31 14:33:15 Plex Movies: Dir.Attr
2016/12/31 14:33:15 Plex Family Movies: Dir.Lookup
2016/12/31 14:33:15 Plex Family Movies: Dir.Lookup OK
2016/12/31 14:33:15 Plex Family Movies: Dir.Attr
2016/12/31 14:33:15 : Dir.Attr
2016/12/31 14:33:15 : Dir.Attr
2016/12/31 14:33:15 : Dir.ReadDirAll
2016/12/31 14:33:15 : Dir.ReadDirAll OK with 3 entries
2016/12/31 14:33:20 : Dir.Attr
2016/12/31 14:33:20 Family photo.jpg: Dir.Lookup
2016/12/31 14:33:20 Family photo.jpg: Dir.Lookup
2016/12/31 14:33:20 Family photo.jpg: Dir.Lookup
2016/12/31 14:33:20 Family photo.jpg: Dir.Lookup
2016/12/31 14:33:20 Family photo.jpg: Dir.Lookup
2016/12/31 14:33:20 Family photo.jpg: Dir.Create
2016/12/31 14:33:20 Family photo.jpg: Dir.Create OK
2016/12/31 14:33:20 File.Attr
2016/12/31 14:33:20 Family photo.jpg: WriteFileHandle.Flush
2016/12/31 14:33:20 Family photo.jpg: WriteFileHandle.Flush ignoring flush on unwritten handle
2016/12/31 14:33:20 Family photo.jpg: WriteFileHandle.Release closing
2016/12/31 14:33:21 : Dir.Attr
2016/12/31 14:33:21 Family photo.jpg: WriteFileHandle.Release OK
2016/12/31 14:33:21 Family photo.jpg: File.Attr
2016/12/31 14:33:21 Family photo.jpg: File.Open
2016/12/31 14:33:21 Family photo.jpg: ReadFileHandle.Flush
2016/12/31 14:33:21 Family photo.jpg: ReadFileHandle.Flush OK
2016/12/31 14:33:21 Family photo.jpg: ReadFileHandle.Release closing
2016/12/31 14:33:21 Family photo.jpg: ReadFileHandle.Release OK
2016/12/31 14:33:21 Family photo.jpg: File.Attr
2016/12/31 14:33:21 Family photo.jpg: File.Open
2016/12/31 14:33:22 Family photo.jpg: ReadFileHandle.Flush
2016/12/31 14:33:22 Family photo.jpg: ReadFileHandle.Flush OK
2016/12/31 14:33:22 Family photo.jpg: ReadFileHandle.Release closing
2016/12/31 14:33:22 Family photo.jpg: ReadFileHandle.Release OK
2016/12/31 14:33:22 Family photo.jpg: File.Open
2016/12/31 14:33:22 : Dir.ReadDirAll
2016/12/31 14:33:22 : Dir.ReadDirAll OK with 4 entries
2016/12/31 14:33:22 Family photo.jpg: ReadFileHandle.Flush
2016/12/31 14:33:22 Family photo.jpg: ReadFileHandle.Flush OK
2016/12/31 14:33:22 Family photo.jpg: ReadFileHandle.Flush
2016/12/31 14:33:22 Family photo.jpg: ReadFileHandle.Flush OK
2016/12/31 14:33:22 Family photo.jpg: ReadFileHandle.Release closing
2016/12/31 14:33:22 Family photo.jpg: ReadFileHandle.Release OK
2016/12/31 14:33:22 Family photo.jpg: File.Attr
2016/12/31 14:33:22 .ql_disablethumbnails: Dir.Lookup
2016/12/31 14:33:22 .ql_disablecache: Dir.Lookup
2016/12/31 14:33:27 Family photo.jpg: File.Open
2016/12/31 14:33:27 Family photo.jpg: ReadFileHandle.Flush
2016/12/31 14:33:27 Family photo.jpg: ReadFileHandle.Flush OK
2016/12/31 14:33:27 Family photo.jpg: ReadFileHandle.Release closing
2016/12/31 14:33:27 Family photo.jpg: ReadFileHandle.Release OK
2016/12/31 14:33:39 : Dir.Attr
2016/12/31 14:33:54 Family photo.jpg: File.Attr
2016/12/31 14:33:54 : Dir.ReadDirAll
2016/12/31 14:33:54 : Dir.ReadDirAll OK with 4 entries
2016/12/31 14:33:54 Family photo.jpg: File.Open
2016/12/31 14:33:54 Family photo.jpg: ReadFileHandle.Flush
2016/12/31 14:33:54 Family photo.jpg: ReadFileHandle.Flush OK
2016/12/31 14:33:54 Family photo.jpg: ReadFileHandle.Release closing
2016/12/31 14:33:54 Family photo.jpg: ReadFileHandle.Release OK
2016/12/31 14:33:54 Family photo.jpg: File.Open
2016/12/31 14:33:54 Family photo.jpg: ReadFileHandle.Flush
2016/12/31 14:33:54 Family photo.jpg: ReadFileHandle.Flush OK
2016/12/31 14:33:54 Family photo.jpg: ReadFileHandle.Release closing
2016/12/31 14:33:54 Family photo.jpg: ReadFileHandle.Release OK
2016/12/31 14:33:54 Family photo.jpg: File.Attr
2016/12/31 14:33:54 Family photo.jpg: File.Open
2016/12/31 14:33:54 : Dir.Attr
2016/12/31 14:33:54 : Dir.ReadDirAll
2016/12/31 14:33:54 : Dir.ReadDirAll OK with 4 entries
2016/12/31 14:33:55 Family photo.jpg: ReadFileHandle.Flush
2016/12/31 14:33:55 Family photo.jpg: ReadFileHandle.Flush OK
2016/12/31 14:33:55 Family photo.jpg: ReadFileHandle.Release closing
2016/12/31 14:33:55 Family photo.jpg: ReadFileHandle.Release OK
2016/12/31 14:33:55 Family photo.jpg: File.Attr
2016/12/31 14:33:55 Family photo.jpg: File.Open
2016/12/31 14:33:55 Family photo.jpg: ReadFileHandle.Flush
2016/12/31 14:33:55 Family photo.jpg: ReadFileHandle.Flush OK
2016/12/31 14:33:55 Family photo.jpg: ReadFileHandle.Release closing
2016/12/31 14:33:55 Family photo.jpg: ReadFileHandle.Release OK
2016/12/31 14:33:55 Family photo.jpg: File.Attr
2016/12/31 14:33:55 Family photo.jpg: File.Open
2016/12/31 14:33:55 Family photo.jpg: ReadFileHandle.Flush
2016/12/31 14:33:55 Family photo.jpg: ReadFileHandle.Flush OK
2016/12/31 14:33:55 Family photo.jpg: ReadFileHandle.Release closing
2016/12/31 14:33:55 Family photo.jpg: ReadFileHandle.Release OK
