### ISSUE TITLE
SHA1 mismatch when copying large files (B2).

### ISSUE THREAD

**Issue by NewtsLament** [ncw/rclone#678]
When copying a large files (+500 MB) from a Backblaze B2 bucket to a local folder, the file copy fails with the error: 'Failed to copy: object corrupted on transfer - SHA1 mismatch (want "none" got "4481bb31c54b5078b16c3c3a010168897873c42e")'.

Looking at the source the "none" sha1 is supposed to be retrieved from B2 while "4481bb31c54b5078b16c3c3a010168897873c42e" is created from the received file.

Therefore I checked the remote sha1sum using "rclone sha1sum brive:testvlad/REC_0002.MOV" which returned "4481bb31c54b5078b16c3c3a010168897873c42e". So the file is synced ok, so something must be going wrong when retrieving the sha1sum from B2.

Rclone version: 1.33

OS: Debian Stretch (AMD64)

Cloud storage: Backblaze B2

Command causing issue: "rclone -v --transfers 32 --retries 10 copy brive:testvlad /home/kelvin/trive"

The tested file is 1 GB in size with the sha1 sum "4481bb31c54b5078b16c3c3a010168897873c42e".

See attached file for log with '-v' flag.
[rclonelog.txt](https://github.com/ncw/rclone/files/453093/rclonelog.txt)

**Comment by ncw** [comment]
Thanks for the report. Will investigate further early next week when I'm back from vacation.

**Comment by ncw** [comment]
I've fixed this - here is a beta with the fix in.

http://pub.rclone.org/v1.33-5-gb3d0848%CE%B2/

Please re-open the ticket if you find a problem with it.

**Comment by ivy** [comment]
I'm having this same issue with rclone v1.36, using Backblaze B2 underneath a crypt remote:

```
2017/06/04 15:59:51 ERROR : example.txt: Failed to copy: object corrupted on transfer - SHA1 mismatch (want "" got "b9ada2021a634f251fa3ee2b356f770efc99c236")
```

It looks like @NewtsLament saw `"none"` as the wanted hash, whereas I'm currently seeing `""`.

**Comment by ncw** [comment]
@ivy I fixed this again in 1d42a343d25b4ae6263fe2046c681f54ebee53dc - if you try the latest beta you should find it works fine.

**Comment by phillmac** [comment]
Still getting this issue on the most recent 1.37 beta release:

# rclone move --verbose b2:xtcrbackup/webserver/ b2:oasiscraft-backup/

2017/08/16 05:42:04 ERROR : 2017-03-25/accounts/dragonet.tar.gz: Failed to copy: object corrupted on transfer - SHA1 mismatch (want "" got "99e376f1ffbb4154924cb982382bdcd00451989b")
2017/08/16 05:42:04 ERROR : 2017-03-25/accounts/dragonet.tar.gz: Not deleting source as copy failed: object corrupted on transfer - SHA1 mismatch (want "" got "99e376f1ffbb4154924cb982382bdcd00451989b")

# rclone --version
rclone v1.37-093-gb510c70cß
- os/arch: linux/amd64
- go version: go1.8.3

**Comment by ncw** [comment]
@phillmac can you reproduce this reliably? How big are the files you are transferring?

If so can you paste a log with `-vv` please?

**Comment by ncw** [comment]
@phillmac I think I've found the problem - can you have a go with this please?

https://beta.rclone.org/v1.37-115-g8207af94/ (uploaded in 15-30 mins)

**Comment by phillmac** [comment]
@ncw Sorry for the late reply, just tested it and the issue seems to be
resolved.

**Comment by Archerious** [comment]
Still getting this error.

**Comment by ncw** [comment]
@Archerious can you make sure you are using a recent rclone ( [the latest release](https://rclone.org/downloads/)) and if you can still reproduce it then please make a [new issue on github](https://github.com/rclone/rclone/issues/new/choose) with full instructions on how to reproduce - thanks!

**Comment by Archerious** [comment]
Will do, as the issue is back :(.
