### ISSUE TITLE
--timeout option causing idle "i/o timeout"

### ISSUE THREAD

**Issue by markuscraig** [ncw/rclone#766]
Great work on rclone, I'm a big fan.  Here is my environment...

> Version = rclone v1.33-DEV
> OS = OSX 10.11.6 (El Capitan)
> Storage = Amazon Cloud Drive
> Command =
> 
>  rclone --verbose --retries 3 --max-size 50G --checkers 4 --transfers 1 --stats 10s copy /Volumes/PhotoArchive/Lightroom/2016 remote:Lightroom/2016

When copying with the above command, I noticed that "i/o errors" were occurring for large files whenever the file upload time crossed 5 minutes.  But the "--stats" option shows that data is being continuously uploaded (I/O is not idle).  Here is an example where data is uploading fine, but the upload is interrupted after 5 minutes and restarted again...

> 2016/10/04 13:27:26
> Transferred:   376.469 MBytes (1.315 MBytes/s)
> Errors:                 0
> Checks:              9736
> Transferred:            0
> Elapsed time:     4m46.2s
> Transferring:
>  *                2016-04-17/MontereyMinnows.mp4: 78% done. avg: 1420.9, cur: 1412.1 kByte/s. ETA: 1m13s
> 
> 2016/10/04 13:27:41
> Transferred:   394.625 MBytes (1.310 MBytes/s)
> Errors:                 0
> Checks:              9736
> Transferred:            0
> Elapsed time:      5m1.2s
> Transferring:
>  *                2016-04-17/MontereyMinnows.mp4: 82% done. avg: 1411.4, cur: 1283.5 kByte/s. ETA: 1m6s
> 
> 2016/10/04 13:27:55 pacer: Rate limited, sleeping for 947.77941ms (1 consecutive low level retries)
> 2016/10/04 13:27:55 pacer: low level retry 1/1 (error Post https://content-na.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: read tcp 192.168.0.11:56395->52.87.95.4:443: i/o timeout)
> 2016/10/04 13:27:55 2016-04-17/MontereyMinnows.mp4: Received error: Post https://content-na.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: read tcp 192.168.0.11:56395->52.87.95.4:443: i/o timeout - low level retry 1/10
> 2016/10/04 13:27:55 pacer: Resetting sleep to minimum 20ms on success
> #!/bin/sh
> 2016/10/04 13:27:56
> Transferred:   413.250 MBytes (1.307 MBytes/s)
> Errors:                 0
> Checks:              9736
> Transferred:            0
> Elapsed time:     5m16.2s
> Transferring:
>  *                2016-04-17/MontereyMinnows.mp4:  0% done. avg: 1842.7, cur:    0.0 kByte/s. ETA: -

I suspected the "--timeout" option which is "5m" by default.  When I change "--timeout" to 0 (zero), the "i/o timeout" error occurs immediately (endless loop, but should disable timeouts).  When I change "--timeout" to a long time (ie: "8h"), the large files upload successfully without being interrupted.

It appears that the "--timeout" option is falsely interrupting the transfer even though data is being continuously uploaded.  Any insight appreciated.  Thanks!

**Comment by ncw** [comment]
This is to do with the revamp of the timeout code in 0cb9bb3b54397ff2dd7a563194d1ec98ca9cedaa

The not turning timeouts off if 0 is a bug.

What I think is happening in your case is the read timeout is firing even though writes are going through just fine.

I'll confirm that and give the logic a little tweak, then post a beta for you to try.

**Comment by ncw** [comment]
http://pub.rclone.org/v1.33-41-g90aee8c-fix-timeout%CE%B2/

**Comment by ncw** [comment]
That is a beta for you to have a go with - I think it is fixed!

**Comment by markuscraig** [comment]
Awesome!

**Comment by felixbuenemann** [comment]
@ncw I am still seeing timeouts with that build over a high speed connection in the same AWS region:

```
rclone move test.img adfb:Test -v
2016/10/06 02:18:05 rclone: Version "v1.33-41-g90aee8c-fix-timeoutβ" starting with parameters ["rclone" "move" "test.img" "adfb:Test" "-v"]
2016/10/06 02:18:05 amazon drive root 'Test': Modify window not supported
2016/10/06 02:18:06 amazon drive root 'Test': Waiting for checks to finish
2016/10/06 02:18:06 amazon drive root 'Test': Waiting for transfers to finish
2016/10/06 02:19:05
Transferred:   4.370 GBytes (74.220 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m0.2s
Transferring:
 *                                      test.img: 100% done. avg: 76620.7, cur: 57323.3 kByte/s. ETA: 0s

2016/10/06 02:19:57 pacer: Rate limited, sleeping for 632.969758ms (1 consecutive low level retries)
2016/10/06 02:19:57 pacer: low level retry 1/1 (error Post https://content-na.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: net/http: timeout awaiting response headers)
2016/10/06 02:19:57 test.img: Received error: Post https://content-na.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: net/http: timeout awaiting response headers - low level retry 1/10
2016/10/06 02:19:57 pacer: Resetting sleep to minimum 20ms on success
2016/10/06 02:20:05
Transferred:   5.006 GBytes (42.616 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      2m0.2s
Transferring:
 *                                      test.img: 14% done. avg: 86719.7, cur: 52188.8 kByte/s. ETA: 1m15s

2016/10/06 02:21:05
Transferred:   8.740 GBytes (49.639 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      3m0.2s
Transferring:
 *                                      test.img: 100% done. avg: 67689.9, cur: 42451.7 kByte/s. ETA: 0s

2016/10/06 02:21:57 pacer: Rate limited, sleeping for 263.669287ms (1 consecutive low level retries)
2016/10/06 02:21:57 pacer: low level retry 1/1 (error Post https://content-na.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: net/http: timeout awaiting response headers)
2016/10/06 02:21:57 test.img: Received error: Post https://content-na.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: net/http: timeout awaiting response headers - low level retry 2/10
2016/10/06 02:21:57 pacer: Resetting sleep to minimum 20ms on success
2016/10/06 02:22:05
Transferred:   9.411 GBytes (40.107 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      4m0.2s
Transferring:
 *                                      test.img: 15% done. avg: 87326.3, cur: 76585.5 kByte/s. ETA: 50s

^C
```

After aborting I waited some time and then the file appeared in the cloud drive web ui.

Tested using a t2.large ec2 instance in us-east-1a on Ubuntu 16.04 amd64. Source was a on EFS.

**Comment by ncw** [comment]
That looks like a different problem!

I set the `ResponseHeaderTimeout` to the `--contimeout` value which is 1 minute by default.  I've seen lots of issues with Amazon being slow to process big files after upload, but them appearing in the web UI later. 

Perhaps I should be setting it to the `--timeout` value instead.  If you try with `--contimeout 5m` does it succeed?

```
	// ResponseHeaderTimeout, if non-zero, specifies the amount of
	// time to wait for a server's response headers after fully
	// writing the request (including its body, if any). This
	// time does not include the time to read the response body.
	ResponseHeaderTimeout time.Duration
```

**Comment by felixbuenemann** [comment]
@ncw It works on the first upload try with `--contimeout 5m`. Should I open another issue?

I'm not sure what causes the delay between upload and the file turning up in the UI. It could be that they are using S3 COPY in the background to convert a multipart upload into a single part upload with a valid MD5SUM in the ETag.

**Comment by ncw** [comment]
Thanks for testing. 

I'll fix on this issue don't worry about opening a new one. 

The speculation is that it is something to do with calculating the hash, yes.

**Comment by ncw** [comment]
I've fixed this now - find the beta in http://beta.rclone.org/v1.33-56-gd42b386/ (in about 15 minutes)

**Comment by felixbuenemann** [comment]
@ncm Thanks, it's now working fine without any switches.

**Comment by ncw** [comment]
@felixbuenemann thanks for testing

**Comment by ncm** [comment]
Hi Felix,

I suspect you must have been intending to write to someone else...

Nathan Myers
