### ISSUE TITLE
Encrypted ACD: ReadFileHandle.Read error: failed to authenticate decrypted block - bad password?

### ISSUE THREAD

**Issue by Trentflix** [ncw/rclone#802]
I keep getting the below error message with Encrypted Amazon Cloud Drive - I don't get it with Encrpyted Google when doing the exact same thing (just trying to access files from the mount - sometimes remotely). It will show up 4 times and won't open the file:

`File/Path/TEST.mkv: ReadFileHandle.Read error: failed to authenticate decrypted block - bad password?`

Ubuntu 14.04 x64
"v1.33-69-gd8d1102β"
rclone mount EACD: /path/to/mount/ --allow-other &

**Comment by DurvalMenezes** [comment]
This seems to be a duplicate of #677; Trent, can you please confirm?

**Comment by Trentflix** [comment]
It's the same error message, the difference is they are getting it when uploading files. I'm getting it when trying to play video files via the mount. I used rclone copy via the command line to upload the files without issue or errors.

**Comment by aneuploid1** [comment]
I am getting the same error on random videos. I am not even trying to play the videos. Plex is just scanning and bathing the metadata.

**Comment by aneuploid1** [comment]
I just updated my mac mini to 10.12.1 beta 5... reinstalled the latest rclone and I am having a LOT better performance.  I did have one instance of the "failed to authenticate decrypted block - bad password?" but it seems to be working better for some reason.

**Comment by jkaberg** [comment]
I'm also seeing this one while scanning over an encrypted drive

**Comment by jkaberg** [comment]
Seem's to happen a lot more often while seeking if that helps

**Comment by ncw** [comment]
Here is an experimental  fix for that error.  It will produce a different error instead of the spurious `failed to authenticate decrypted block` - something to do with the connection breaking would be my guess.

http://pub.rclone.org/v1.33-81-gef17f90-readfull-fix%CE%B2/

I'm on the trail of the underlying error, but I need to confirm I'm going in the right direction, so any testing appreciated.

**Comment by jkaberg** [comment]
@ncw Thanks for looking into this, here's a log: http://pastebin.com/YPbfWDV7

I only tested as far as getting one failed, let me know if you need several

**Comment by Trentflix** [comment]
I'm getting the same error message as before. It only happens on my Encrypted ACD mount though, not my Encrypted google Drive mount.

**Comment by aneuploid1** [comment]
I don't see a version for OSX

**Comment by ncw** [comment]
@jkaberg useful log thanks. I see you are using seeks which lead me into finding a data corruption problem with crypt+seek which I've now fixed.  Have a go with http://beta.rclone.org/v1.33-81-g9d2dd2c/ (will be uploaded in 15-30 minutes) and tell me if that makes a difference.

**Comment by jkaberg** [comment]
@ncw Unfortunately still the same error and just to be clear: the file in question play's fine from local disk (unencrypted ofcourse)

http://pastebin.com/DnTMqb0y

**Comment by jkaberg** [comment]
So after debuging this further it seems some files play just fine, but most won't (local playback works 100%). How can I debug this @ncw?

**Comment by ncw** [comment]
After looking at your logs, I have an idea... Are the files which don't play all bigger than 10 GB?  Can you try playing a file < 10GB (say 5GB) and compare with one > 10GB?

(10GB is the templink threshold which means these files are being fetched a different way - maybe that way doesn't support Range requests or something like that.  I can't test myself as my Internet connection has gone to pieces :-( )

**Comment by jkaberg** [comment]
I tried with a few, one at 6GB and another at 8GB which plays and seeks fine. And a few more around 14-15GB that errors out so you might be on to something here? :-)

**Comment by krog** [comment]
I can confirm your theory. I can play and seek videos smaller <9GB (default threshold afaik). Anything larger is fetched with templink and always fails when seeking.

**Comment by jkaberg** [comment]
Just for the fun of it I tried mounting with ```--acd-templink-threshold=20G``` but still same issue as here https://github.com/ncw/rclone/issues/204

Perhaps this is dead in the water then?

**Comment by ncw** [comment]
Great, looks like we are getting somewhere :-)

What I need now is someone to run `rclone mount` with `-v` and `--dump-headers` and try to play a bigger than 10 GB video and post those logs.  **Important** Make sure you remove the `Authorization:` lines from the log with eg `grep -v Authorization: <dirty-log >clean-log` before posting.

**Comment by jkaberg** [comment]
And here is one from me: https://goo.gl/Ahqjmt

**Comment by ncw** [comment]
@calisro The errors I see in your log all look like `read tcp 10.100.1.195:59112->54.165.17.201:443: use of closed network connection`

Can you open a new issue with that log please, and also put a description of your setup with nginx - if I can easily reproduce the problem locally it will be much easier for me to fix.

**Comment by ncw** [comment]
@jkaberg I can see what is happening there is that rclone tries to download the file with a `Range:` header using the templink.

This gets redirected to download directly via S3 as it is bigger than 10GB, however rclone doesn't put the `Range:` header back on at that point so it downloads from the beginning which isn't what the crypto expects, hence the bad password error.

Luckily I've already written code to do that in `rest.clientWithHeaderReset` so it will be a question of gluing A onto B and it should work.

I'll post a beta in a bit for you to try...

**Comment by jkaberg** [comment]
@ncw Standing by :-)

**Comment by ncw** [comment]
Here is a beta with that fix: http://beta.rclone.org/v1.33-82-g5986953/ (will be uploaded in 15-30 mins)

**Comment by krog** [comment]
Your fix looks perfect. With 1.33-82 I can play and seek in a file >10GB.

**Comment by calisro** [comment]
Also confirmed to work in my testing setup.

**Comment by jkaberg** [comment]
Confirmed, working fine here

**Comment by ncw** [comment]
Excellent :-)

**Comment by calisro** [comment]
@ncw No need to create a new issue.  I have narrowed the issue that I am having down to unionfs and I believe it is similar to Issue #823.

**Comment by ncw** [comment]
@calisro would probably be a good idea to confirm that the bactrace you see from `rclone mount` is the same as the on in that ticket.

**Comment by calisro** [comment]
@ncw Yes. It is the same.

**Comment by ncw** [comment]
I found a bit of missing locking in the FUSE module which can also produce this error message. Here is a beta with the fix - let me know if it works: http://beta.rclone.org/v1.33-83-g8710741/ (will be uploaded in 15-30 mins)

**Comment by Coornail** [comment]
I'm still seeing this error with many processes accessing files in 83.
Now the error messages are coming in pairs
```
2016/10/27 10:39:49 file1: ReadFileHandle.Read error: failed to authenticate decrypted block - bad password?
2016/10/27 10:39:49 file1: ReadFileHandle.Read error: failed to authenticate decrypted block - bad password?
2016/10/27 10:40:35 file2: ReadFileHandle.Read error: failed to authenticate decrypted block - bad password?
2016/10/27 10:40:35 file2: ReadFileHandle.Read error: failed to authenticate decrypted block - bad password?
...
```

**Comment by ncw** [comment]
@Coornail probably the best thing to do is to try to work out what is causing the issue in such a way I could reproduce it, then put that into a new issue, with a full log with -v from the latest beta.

Thanks 

Nick

**Comment by ncw** [comment]
I'm going to close this one now as this issue is fixed.
